### ISSUE TITLE
Add JUnit/Ant compatible XML reporter

### ISSUE THREAD

**Issue by phated** [theintern/intern#102]
Some CI servers, like Jenkins and Bamboo, require JUnit/Ant compatible XML reports be generated for test runs to be reported correctly.

Reference reporter from BusterJS - http://docs.busterjs.org/en/latest/modules/buster-test/reporters/#xml-reporter

**Comment by mathieumg** [comment]
@relcapp Sorry for the delay. Not yet, I've been nagging our admin to get our proper Bamboo setup and I'm still waiting for it. I'll report here as soon as I hear back and can test it.
