### ISSUE TITLE
Intern interactivity

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#1021]
The goal of this issue is to look into ways Intern could be made more interactive. One way in which Intern is currently interactive is the clickable links in the HTML report. A user may click a failing suite or test ID and cause Intern to rerun that particular test.

Some questions to answer:

* At what points in the lifecycle should Intern be interactive? (e.g., during a CLI test run, in the browser, ...)
* In what contexts should Intern be available? (CLI, browser, editor plugin, ...)
* What primitives would be required to enable interactivity? (e.g., prompt and input handling)
* How could reporters be made interactive?

**Comment by jason0x43** [comment]
There hasn't been a lot going on here, so I'll take a stab at this. These are just my thoughts based on how I use testing tools. Other viewpoints are encouraged.

## When should Intern be interactive

Currently, the only situation in which Intern is really interactive is the web-based unit test runner. Intern runs tests and presents the results as an HTML document. The user can interact with this document in a few ways -- click a test or suite to run just that test or suite, or hide and show failed tests.

For normal command line runs, I'm not sure there needs to be much interactivity by default. In general, test runs should not need human interaction or they'll be annoying to run.

Possibly Intern could support an initialization flow, where it would ask questions to create an `intern.json` file.

## What primitives would be required for interactivity

On the web side we're probably in good shape. DOM event listeners can just call Intern functionality.

On the command line, we could add simple prompting functionality to Intern, possibly based on Node's readline, or something higher level. The executor could then expose a prompt method that would output a message and wait for input.

## How could reporters be made interactive

Other than the web client reporter, I'm not sure when we would need interactivity in a reporter. However, if we added a prompt primitive to the executor _and_ made the event system wait for event handlers, reporters could easily halt the testing process to wait for user input.

**Comment by jason0x43** [comment]
Potential tasks...

## Serialize the event handling process

See #1054. The idea would be to ensure that events are emitted and handled sequentially, which would give event handlers the ability to halt the testing process. This would allow custom reporters (or built in logic) to pause Intern to ask for user input.

**Comment by aciccarello** [comment]
For myself, I don't really expect a test runner to be interactive with the exception of having a watch mode. Debugging is the biggest way that I want to "interact" with test results.

In VS Code CLI results, I'll often click on the path links for a failing test. Jest has a nice feature where the test file path is a different color making it easy to find in the stack trace. Intern's reporter already seems pretty good but it is something to consider.

A VS Code extension sounds like a cool idea. I've used the Jest extension and it can be handy. At times it is a little clunky trying to dig into errors so it would be worth looking at that interaction. There were a few times where the extension would get hung up and the passing indicators got out of sync so stress testing the extension on a large code base is important. Some way to disable or reset it would also be good.

**Comment by jason0x43** [comment]
Closing as discovered.

Outcomes:

* Add menu/response functionality (#1130)
* Create a VSCode extension (#1131)
