### ISSUE TITLE
IE11 feature detection tests stalls on 'foo' after maximizing the window

### ISSUE THREAD

**Issue by jake-harrington** [theintern/intern#1043]
Description: During the feature detection tests before my functional tests run IE11 is stalling at the purple "foo" step in the test. After 'foo' displays it maximizes the window before it stalls so maybe it's related to that.

Steps to reproduce:
Run the attached tests (`npm run server` then `npm test`)

Expected result: Feature detection should complete fairly quickly.
Actual result: Feature detection stalls for about ten minutes, then continues to the functional tests.

Intern version: 4.4.3

Any additional information:
Selenium 3.141.59, IE driver 3.14.
![image](https://user-images.githubusercontent.com/39064853/61228375-ca1e0080-a6eb-11e9-926c-c63c464a9980.png)
[intern-test.zip](https://github.com/theintern/leadfoot/files/3393033/intern-test.zip)

**Comment by jason0x43** [comment]
Resolved in a671b7f

This fix will also be ported to theintern/leadfoot#187
