### ISSUE TITLE
Verify Intern 4.x compatibility with MS Edge Chromium release

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#1048]
Now that Edge Chromium is out, verify that Intern 4 and 5-pre work with it.

**Comment by jason0x43** [comment]
Browser name should be MicrosoftEdge, browser version should be 'insider preview'.

We should pick something better for the version.

**Comment by devpaul** [comment]
Edge 79 works w/ Intern (5.x-pre) on master using environment `{ "browser": "edge", "version": "insider preview" } w/ selenium.

![image](https://user-images.githubusercontent.com/331431/73092148-45315200-3e99-11ea-9502-acc7b5623bc6.png)

**Comment by devpaul** [comment]
Edge 79 works w/ Intern 4.x using environment `{ "browser": "edge", "version": "insider preview" }` w/ local selenium.

![image](https://user-images.githubusercontent.com/331431/73092956-d05f1780-3e9a-11ea-8292-f3f56382a4d2.png)

**Comment by devpaul** [comment]
Everything looks good. We'll come back and review the environment specification for Edge Chromium on Intern 5.x
