### ISSUE TITLE
Typo in JSON schema

### ISSUE THREAD

**Issue by TimurDela** [theintern/intern#1134]
## Expected behavior

The config.json schema should suggest only valid reporters.

## Current behavior

A typo line 614 of `schema/config.json` lists **jsunit** instead of **junit** as an available reporter.

## Possible solution

Correct that typo

## Steps to reproduce (for bugs)

1. …
2. …
3. …

## Environment

Intern version:
Node version:
NPM version:
Browser version:

**Comment by jason0x43** [comment]
Good catch!
