### ISSUE TITLE
Documentation example code uses `getPlugin` instead of `getInterface`

### ISSUE THREAD

**Issue by msssk** [theintern/intern#1162]
There are various bits of documentation with code like:

```javascript
const { suite, test } = intern.getPlugin('interface.tdd');
```

It should use `getInterface` instead of `getPlugin`:

```javascript
const { suite, test } = intern.getInterface('interface.tdd');
```

The problem also exists in https://github.com/theintern/intern-tutorial

**Comment by jason0x43** [comment]
All the documentation uses `getPlugin`; this is intentional (https://github.com/theintern/intern/issues/875).

In Intern 5 the interfaces will be available directly on the executor, so you won't even need getPlugin for that.

**Comment by msssk** [comment]
So I guess the problem is the opposite:
https://theintern.io/docs.html#Intern/4/api/lib%2Finterfaces%2Fobject
https://theintern.io/docs.html#Intern/4/api/lib%2Finterfaces%2Ftdd
These both demonstrate `getInterface`

**Comment by jason0x43** [comment]
Oops, I thought I had gotten rid of all the references to getInterface. Apparently I missed some.
