### ISSUE TITLE
Create json-stream reporter for Grunt task

### ISSUE THREAD

**Issue by pifantastic** [theintern/intern#120]
Currently, the intern grunt task checks the output of the reporter for `pas` or `fail` and uses `grunt.log.{ok|error}`. This is rather limiting as a reporter should have the freedom of using both `pass` or `fail` in its output language, regardless of the actual test result. Additionally, it's hard to know what chunk of data will be making it's way stdout at any one time.

Ideally, I think the intern grunt task would just pass stdout straight through, without altering the output. That probably means using `grunt.log.write` instead of `grunt.log.ok` or `grunt.log.error`. The `ok` and `error` methods also trim(), which can be annoying when trying to format things nicely.

**Comment by jason0x43** [comment]
Just cleaning things up...

A better solution now would be for the grunt task to directly register listeners with the Intern executor. If that seems worthwhile, we can open a new issue along those lines.
