### ISSUE TITLE
Make all reporters configurable

### ISSUE THREAD

**Issue by williamrjribeiro** [theintern/intern#141]
Is it possible to pass Istanbul configurations via the 'intern' Grunt task?
If not yet then consider this a feature request/enhancement(?).

It could be something like this:
 ```
intern: {
  options: {
    istanbul: {
      cover: 'path/to/cover/file',
      report: 'path/to/report/file'
      thresholds:
            lines: 95,
            statements: 95,
            branches: 95,
            functions: 95
    }
  }
}
```
For my projects, a high code coverage is really important. Therefore, if the thresholds are not met, the build must fail. As far as I can see, this is not possible out-of-the-box yet.

Thanks.

**Comment by sjdemartini** [comment]
I'd love to be able to set the output directory for the reports. Very much looking forward to this functionality!

**Comment by kevin-miles** [comment]
+1 for configurable output directory

**Comment by csnover** [comment]
Reporters in Intern 3 are configurable. For reporters that support writing to files, you’ll be able to specify the output file with the `filename` option, and output directory using `directory`. For coverage reporters you can specify the low/high threshold using the `watermarks` option. I’m working on updating the user guide now for the new reporters so you’ll be able to go there to see what to do when Intern 3 is released.
