### ISSUE TITLE
Make instrumentation optional

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#150]
Instrumentation causes problems with TDD because it makes stack trace line numbers invalid. It can be disabled by excluding all files from instrumentation (`excludeInstrumentation: /.*/`), but it would be more straightforward to have a simple `disableInstrumentation` flag, or an 'instrument' flag with instrumentation disabled by default.

**Comment by wkeese** [comment]
FYI, looks like this eventually implemented (although Colin initially closed the ticket as invalid).

Version 3 lets you set `excludeInstrumentation: true`, see https://theintern.github.io/intern/#common-config.
