### ISSUE TITLE
Calling require() of modules imported by intern returns empty object

### ISSUE THREAD

**Issue by nstepien** [theintern/intern#155]
I made a test case here:
https://github.com/MayhemYDG/intern-test
1. The test imports `aa` by using `'intern/node_modules/dojo/node!../aa'`.
2. The module `aa` imports `bb` via `require()`, it works as expected.
3. The module `bb` imports `aa` via `require()`, `aa` is an **empty object**.

This seems to happens every time a module was already imported by `dojo/node`.

**Comment by kksd** [comment]
`Set module.exports = aa; before calling require('./bb')` - what is the catch for this one? @csnover
