### ISSUE TITLE
Silent failure using `Date` in config file for IE <10

### ISSUE THREAD

**Issue by mambocab** [theintern/intern#230]
I'm using the geezer branch. I configured my Intern tests so each test would have a unique name usingn `Date.now()`. In my Intern test config file:

``` js
define({
    ...
    capabilities: {
        'selenium-version': '2.41.0',
        'name': 'mambocab  ' + Date.now()
    },
    ...
});
```

This works fine, even on the geezer branch, for ECMAScript 5 browsers. However, when `Date` isn't available in older browser, the test run just hangs without reporting any errors.

I have no problems with the failure itself, but it would have been easier to debug with some kind of error reporting. Is that feasible?

**Comment by csnover** [comment]
This should be fixed in master.
