### ISSUE TITLE
Loading module request fails

### ISSUE THREAD

**Issue by mzedeler** [theintern/intern#238]
I've tried setting up a minimal test demonstration, but I'm stuck when I try to run tests.

What I get is:

```
Listening on 0.0.0.0:9000
Starting tunnel...
Error: Failed to load module request from /tmp/local-selenium-intern/request.js (parent: tests/functional)
  at <node_modules/intern/node_modules/dojo/dojo.js:757:12>
  at <fs.js:207:20>
  at Object.oncomplete  <fs.js:107:15>
```

What I expect is that internal modules (such as `request` doesn't require any explicit configuration for them to load correctly).

The example provided is very basic and can be tested using just `npm install && npm start``:

https://github.com/mzedeler/local-selenium-intern/tree/request-broken

**Comment by Suyogsawant11** [comment]
Request module not abel to load

Listening on 0.0.0.0:9000
Error: Failed to load module https from /home/Sites/Projects/p1/p11/intern_tests/https.js (parent: intern/node_modules/dojo/request/node)
  at <../node_modules/intern/node_modules/dojo/loader.ts:831:119>
  at <fs.js:207:20>
  at Object.oncomplete  <fs.js:107:15>

**Comment by Suyogsawant11** [comment]
you can even try this 

to load http module first - 
var http = require('intern/dojo/node!http')
var request = http.request // you will able to access request
