### ISSUE TITLE
Intern unit tests intermittently hang against BrowserStack/IE

### ISSUE THREAD

**Issue by wkeese** [theintern/intern#253]
When using Intern to run a unit test against IE in BrowserStack, the unit test seems to complete but the intern command never returns.  Instead it keeps resending the following URL once a minute:

Get URL⇒ http://localhost:9000/__intern/client.html?config=deliteful%2Ftests%2Fintern.browserstack-ie&reporters=webdriver&baseUrl=%2F&sessionId=133633c91ec11dbbb9fa9904476866c2dab4a9a4

Happens intermittently w/the latest intern (2.0.3).

To reproduce:

```
$ git clone https://github.com/wkeese/deliteful.git
$ cd deliteful
$ git checkout intern2
$ npm install
$ bower install
$ export BROWSERSTACK_USERNAME=...
$ export BROWSERSTACK_ACCESS_KEY=...
$ grunt test:browserstack-ie
```

(except filling in your user name and access key, as shown on https://www.browserstack.com/automate)

You can check https://www.browserstack.com/automate to see the progress.   It will intermittently hang, so if the final command completes for you, trying running it a few more times until you see the problem.

**Comment by csnover** [comment]
I haven’t heard about this being a problem in quite a while so I am going to close this. Please feel free to open a new ticket or reply with reproduction case if this is still a problem!
