### ISSUE TITLE
Share a standard Reporter interface?

### ISSUE THREAD

**Issue by JamesMGreene** [theintern/intern#257]
We on the [QUnit](http://qunitjs.com/) team have been [discussing](https://github.com/jquery/qunit/issues/531) the possibility of working with other JS test frameworks (e.g. Mocha, Jasmine, Intern, etc.) to agree upon a standard Reporter interface so that we could hopefully share Reporter plugins between testing frameworks.

This would most likely come in the form of an EventEmitter interface with an agreed upon minimum viable set of standardly-named events and associated standard set of data/details provided to each.

Would you guys be interested in discussing this further with us?

If so, I've added @csnover to "Team Intern" on https://github.com/js-reporters/js-reporters. Let me know if anyone else should be added.

**Centralized Discussions:** https://github.com/js-reporters/js-reporters/issues/

Cross-reference issues:
 - https://github.com/jquery/qunit/issues/531  (original discussion)
 - https://github.com/visionmedia/mocha/issues/1326
 - https://github.com/pivotal/jasmine/issues/659

cc: @jzaefferer @Krinkle @leobalter

**Comment by csnover** [comment]
We’ve introduced a new reporter interface for Intern 3. Unfortunately the js-reporters thing kind of fizzled out, but we can revisit this in the future if anything ends up coming out of that project.
