### ISSUE TITLE
Grunt task duplicates assertion errors.

### ISSUE THREAD

**Issue by Blasz** [theintern/intern#260]
I am running a test suite using the intern grunt task.

As the test executes, errors are reported if an assertion fails, e.g.:

```
>> Test main - widgets - nz_cred_snapshot.php FAILED on chrome 37.0.2062.102 on XP:
AssertionError: Table should have data: expected false to be truthy
  at new CompatCommand  <node_modules/intern/runner.js:203:14>
  at CompatCommand.Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:525:10>
  at Test.test  <tests/intern/functional/widgets/widgets.js:21:33>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:236:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>
  at runTest  <node_modules/intern/lib/Suite.js:235:46>
  at <node_modules/intern/lib/Suite.js:248:7>
  at process._tickCallback  <node.js:419:13>
```

I assume this is standard behaviour, even though the stacktrace is unecessary and adds verbosity to the reporter output (but this should hopefully be resolved with the new runner reporter mentioned in https://github.com/theintern/intern/issues/258#issuecomment-54494591).

Now, the issue is when running via grunt, when the test completes all those assertion errors and the stacktraces are then output again at the end of the task, polluting the test result outputs with duplicated errors.

There's also an 'aborted due to warnings' message at the end as well, e.g.:

```
Test main - widgets - nz_cred_snapshot.php FAILED on chrome 37.0.2062.102 on XP:
AssertionError: Table should have data: expected false to be truthy
  at new CompatCommand  <node_modules/intern/runner.js:203:14>
  at CompatCommand.Command.then  <node_modules/intern/node_modules/leadfoot/Command.js:525:10>
  at Test.test  <tests/intern/functional/widgets/widgets.js:21:33>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:236:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>
  at runTest  <node_modules/intern/lib/Suite.js:235:46>
  at <node_modules/intern/lib/Suite.js:248:7>
  at process._tickCallback  <node.js:419:13> Use --force to continue.

Aborted due to warnings.
```

I can only assume the duplication is unintentional as I see no real reason for it.

**Comment by sholladay** [comment]
@csnover do you still have the same feelings about this? My team constantly asks why Intern spits out duplicate errors. And when in a non-colored terminal (default for many SSH connections to a server), it can be easy to overlook the fact that there are exactly half as many errors as there appear.

In addition, I'm not aware of any other projects that behave this way - other test frameworks or tools like [jscs](https://github.com/jscs-dev/grunt-jscs "Project page for the jscs Grunt task.") or [jshint](https://github.com/gruntjs/grunt-contrib-jshint "Project page for the jshint Grunt task."). Both of those have binaries that are generally ignorant of Grunt, but still don't exhibit this behavior when using their Grunt tasks.

**Comment by csnover** [comment]
I guess I was having a bad day. :disappointed:
