### ISSUE TITLE
collect coverage for unloaded files

### ISSUE THREAD

**Issue by devangnegandhi** [theintern/intern#267]
This is in relation to the following stackoverflow topic:
http://stackoverflow.com/questions/22827169/coverage-for-files-not-loaded

As mentioned in your reply there, I have a custom reporter ready that collects zero coverage for unloaded files. But for it to work, it needs the `getInstrumenter()` method exposed from the `lib/utils.js` file.

Alternatively, I also have an implementation on my local repo that will allow intern to collect zero coverage information for all unloaded files, regardless of the reporter. It can be feature controlled using a new flag in the config file if needed. This way, anyone who may want to use this feature can use it with the reporter they prefer.

In either case, there needs to be some code changes. I am OK with any of these two implementations. Your thoughts?

**Comment by jason0x43** [comment]
Intern supports this now with the `coverage` config property.
