### ISSUE TITLE
Chai can fail to load if also installed as a sibling of Intern

### ISSUE THREAD

**Issue by necolas** [theintern/intern#271]
More of an FYI about a situation I just ran into. It seems to be that if you install both intern and chai in your project, npm tries to be clever by symlinking `node_modules/intern/node_modules/chai` to `node_modules/chai`. The result is that this part of the example config…

https://github.com/theintern/intern/blob/4a6512b408304d83e30d8dadf01055823f36d12c/client.html#L24

…produces this error:

``` bash
/project/node_modules/intern/node_modules/dojo/dojo.js:757
                    throw new Error('Failed to load module ' + module.mid + ' from ' + url +
                          ^
Error: Failed to load module intern/node_modules/chai/chai from /project/node_modules/intern/node_modules/chai/chai.js (parent: intern/chai)
    at /project/node_modules/intern/node_modules/dojo/dojo.js:757:12
    at fs.js:207:20
    at Object.oncomplete (fs.js:107:15)
```

**Comment by smebberson** [comment]
I just came up against this issue too. I had chai already installed, and the installed Intern. I had the same error `Error: Failed to load module intern/node_modules/chai/chai`.

I run my tests inside a Docker container. My host doesn't have Node.js installed at all.

To rectify this, I uninstalled chai as an npm module, and reinstalled Intern. This time, it actually had chai within it's own node_modules folder.
