### ISSUE TITLE
JUnit reporter issues with Jenkins

### ISSUE THREAD

**Issue by Blasz** [theintern/intern#275]
This is a compilation of issues I have found with the JUnit reporter when testing with jenkins.

### Unit test results are duplicated.

【 code  】
- For a test suite with one test case, tested across three browsers, I get six test case results. Each of the test suite xml entries in report.xml corresponding to an actual unit test suite are preceded by one of:
 - `<testsuite name="firefox 31.0 on XP"...>`
 - `<testsuite name="chrome 37.0.2062.102 on XP"...>`
 - `<testsuite name="internet explorer 11 on WINDOWS"...>`
 - `<testsuite name="firefox 31.0 on XP"...><testsuite name="unit tests" ...><testsuite name="main"...>`
 - `<testsuite name="chrome 37.0.2062.102 on XP"...><testsuite name="unit tests" ...><testsuite name="main"...>`
 - `<testsuite name="internet explorer 11 on WINDOWS"...><testsuite name="unit tests" ...><testsuite name="main"...>`
【 end code 】

### No browser specifity reported

Jenkins seems to ignore nested testsuite elements and as such any browser specificity is lost in its junit test result output. Jenkins is grouping all testsuites into one package called (root). This can be split out per browser by using the classname attribute as specified here: http://nelsonwells.net/2012/09/how-jenkins-ci-parses-and-displays-junit-output/

I will potentially make a pull request to fix this but would like to know what the current JUnit reporter output is being tested against so that regressions aren't introduced.

**Comment by kennytrytek-wf** [comment]
It's not just an issue with Jenkins. As @nicknisi mentioned in #312, it happens anywhere. As part of fixing this, the README should be updated. It currently shows sub-suites as valid JUnit output, but that is not supported in the JUnit XSD.

[Current intern-tutorial README](https://github.com/theintern/intern-tutorial#step-3-write-a-unit-test):
![intern_doc](https://cloud.githubusercontent.com/assets/1466480/5808173/4ecd374a-9ff0-11e4-863c-ed7fb30a1d93.png)

[JUnit XSD](http://windyroad.com.au/dl/Open%20Source/JUnit.xsd):
![junit_xsd](https://cloud.githubusercontent.com/assets/1466480/5808175/532e745c-9ff0-11e4-8c34-2cea37f5fb53.png)

I followed the tutorial for creating unit tests, and that results in this invalid output:
```
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
    <testsuite name="Node.js" failures="0" skipped="0" tests="1" time="0.005">
        <testsuite name="hello" failures="0" skipped="0" tests="1" time="0.002">
            <testcase name="greet" time="0" status="0"/>
        </testsuite>
    </testsuite>
</testsuites>
```


[The expected output](https://raw.githubusercontent.com/theintern/intern/master/tests/unit/data/lib/reporters/junit/expected.xml) for the junit reporter also does not meet the spec:
```
<?xml version="1.0" encoding="UTF-8" ?>
<testsuites>
    <testsuite name="chrome 32 on Mac" failures="2" skipped="1" tests="5"
               time="1.234">
        <testsuite name="suite1" failures="2" skipped="1" tests="5"
                   time="1.234">
            <testcase name="test1" time="0.045" status="0"/>
            <testcase name="test2" time="0.045" status="1">
                <error message="Oops" type="Error">Error: Oops
                    at Test.registerSuite.basic tests ...
                </error>
            </testcase>
            <testcase name="test3" time="0.045" status="1">
                <failure message="Expected 1 + 1 to equal 3"
                         type="AssertionError">AssertionError: Expected 1 + 1 to
                    equal 3
                    at Test.registerSuite.basic tests ...
                </failure>
            </testcase>
            <testcase name="test4" time="0.045" status="0">
                <skipped>No time for that</skipped>
            </testcase>
            <testsuite name="suite5" failures="0" skipped="0" tests="1"
                       time="0.045">
                <testcase name="test5.1" time="0.04" status="0"/>
            </testsuite>
        </testsuite>
    </testsuite>
</testsuites>
```

**Comment by csnover** [comment]
@kennytrytek-wf The internal workings of Intern are not restricted to the limitations of any output format. The information in the tutorial regarding subsuites is correct.

Also, there are at least two JUnit XSDs floating around on the Web, neither of which are written as official or authoritative, and [this closed Jenkins ticket](https://issues.jenkins-ci.org/browse/JENKINS-6545) indicated that JUnit itself supports nesting and at some other producers create nested files, and that Jenkins was enhanced to support such nested suites.

If the suites need to be nested in the output XML in order to be maximally compatible, please submit a patch. Thanks!

**Comment by kennytrytek-wf** [comment]
@csnover The incompatibility occurs because the suites **are** nested, and that is not supported by the Python xunitparser module. http://git.p.engu.in/laurentb/xunitparser/

I am working on submitting a patch to xunitparser, in hopes that it will be flexible enough to support it. Personally, I don't like the idea of a testsuite inside a testsuite, but that seems to be the way the tide is pushing, so I'll go with it.

**Comment by csnover** [comment]
Sorry, I meant “flattened”. :)

**Comment by jason0x43** [comment]
Closing this since it's (potentially) an issue with with certain JUnit parsers rather than with Intern.
