### ISSUE TITLE
Failed to load module [object Object] from /[object Object].js

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#317]
There seems to be a strange issue with module name serialization when running on Sauce Labs. 

```
Listening on 0.0.0.0:9000
Starting tunnel...
Using no proxy for connecting to Sauce Labs REST API.
**********************************************************
A newer version of Sauce Connect (build 1589) is available!
Download it here:
https://saucelabs.com/downloads/sc-4.3.5-osx.zip
**********************************************************
Started scproxy on port 55446.
Starting secure remote tunnel VM...
Secure remote tunnel VM provisioned.
Tunnel ID: 5151695f80f049b7a51daa482ba6b741
Secure remote tunnel VM is now: booting
Secure remote tunnel VM is now: running
Remote tunnel host is: maki76252.miso.saucelabs.com
Using no proxy for connecting to tunnel VM.
Starting Selenium listener...
Establishing secure TLS connection to tunnel...
Selenium listener started on port 4445.
Connection established.
Ready
Initialised internet explorer 10 on WINDOWS
Initialised chrome 35.0.1916.153 on Linux
undefined: Failed to load module [object Object] from /[object Object].js (parent: *13) at http://localhost:9000/__intern/node_modules/dojo/dojo.js:731:7
No stack or location
No unit test coverage for internet explorer 10 on WINDOWS
internet explorer 10 on WINDOWS: 0/0 tests failed
Initialised firefox 33.0.3 on LINUX
undefined: Failed to load module [object Object] from /[object Object].js (parent: *13)
Error: Failed to load module [object Object] from /[object Object].js (parent: *13)
  at HTMLScriptElement.handler  <__intern/node_modules/dojo/dojo.js:731:13>
No unit test coverage for chrome 35.0.1916.153 on Linux
chrome 35.0.1916.153 on Linux: 0/0 tests failed
undefined: Failed to load module [object Object] from /[object Object].js (parent: *13)
  at injectUrl/handler  <__intern/node_modules/dojo/dojo.js:731:13>
No unit test coverage for firefox 33.0.3 on LINUX
firefox 33.0.3 on LINUX: 0/0 tests failed

TOTAL: tested 3 platforms, 0/0 tests failed; fatal error occurred

```

on Intern 2.2.2

I'm closing this because I cannot reproduce this anymore, but maybe someone else will find this.

**Comment by agray** [comment]
I am got this today.  Could this issue please be reopened:

    Starting tunnel...
    , build 1285 bd6579a
    Using no proxy for connecting to Sauce Labs REST API.
    **********************************************************
    A newer version of Sauce Connect (build 1630) is available!
    Download it here:
    https://saucelabs.com/downloads/sc-4.3.6-win32.zip
    **********************************************************
    24 Jan 17:54:21

    Started sc proxy on port 7416.
    24 Jan 17:54:21-Please wait for 'you may start your tests' to start your tests.
    24 Jan 17:54:Starting secure remote tunnel VM...
    Secure remote tunnel VM provisioned.
    Tunnel ID: eda5d37fd09a41cb96b345d82ef0b5ac
    Secure remote tunnel VM is now: running
    Remote tunnel host is: maki77010.miso.saucelabs.com
    Using no proxy for connecting to tunnel VM.
    Starting Selenium listener...
    Establishing secure TLS connection to tunnel...
    Selenium listener started on port 4444.
    24Jan17:54:34-Sauce Connect is up, you may start your tests.
    24 J
    Connection established.
    Ready
    Initialised internet explorer 11 on WINDOWS
    Initialised internet explorer 10 on WINDOWS
    Initialised internet explorer 9 on WINDOWS
    undefined: Failed to load module angular/angular from /angular/angular.js (parent: *33)
    Error: Failed to load module angular/angular from /angular/angular.js (parent: *33)
     at handler <__intern\node_modules\dojo\dojo.js:731:7>
    Initialised firefox 28.0 on MAC
    No unit test coverage for internet explorer 11 on WINDOWS
    internet explorer 11 on WINDOWS: 0/0 tests failed
    undefined: Failed to load module angular/angular from /angular/angular.js (parent: *33)
     at http://localhost:9000/__intern/node_modules/dojo/dojo.js:731:7
    No stack or location
    No unit test coverage for internet explorer 10 on WINDOWS
    internet explorer 10 on WINDOWS: 0/0 tests failed
    undefined: Failed to load module angular/angular from /angular/angular.js (parent: *33) 
     at http://localhost:9000/__intern/node_modules/dojo/dojo.js:731
    No stack or location
    undefined: Error: Failed to load module angular/angular from /angular/angular.js (parent: *33) 
     at http://localhost:9000/__intern/node_modules/dojo/dojo.js:731
     at .run/window.onerror <__intern\lib\realClient.js:57>
    No unit test coverage for internet explorer 9 on WINDOWS
    internet explorer 9 on WINDOWS: 0/0 tests failed
    No unit test coverage for firefox 28.0 on MAC
    firefox 28.0 on MAC: 0/0 tests failed
    Initialised firefox 28.0 on WINDOWS
    Initialised chrome 39.0.2171.65 on Mac OS X
    Initialised chrome 39.0.2171.65 on Windows NT
    Initialised firefox 28.0 on LINUX
    undefined: Error: Failed to load module angular/angular from /angular/angular.js (parent: *33)
     at http://localhost:9000/__intern/node_modules/dojo/dojo.js:731
     at .run/window.onerror <__intern\lib\realClient.js:57>
    undefined: Failed to load module angular/angular from /angular/angular.js (parent: *33)
    Error: Failed to load module angular/angular from /angular/angular.js (parent: *33)
     at HTMLScriptElement.handler <__intern\node_modules\dojo\dojo.js:731:13>
    No unit test coverage for firefox 28.0 on WINDOWS
    firefox 28.0 on WINDOWS: 0/0 tests failed
    undefined: Failed to load module angular/angular from /angular/angular.js (parent: *33)
    Error: Failed to load module angular/angular from /angular/angular.js (parent: *33)
     at HTMLScriptElement.handler <__intern\node_modules\dojo\dojo.js:731:13>
    No unit test coverage for chrome 39.0.2171.65 on Mac OS X
    chrome 39.0.2171.65 on Mac OS X: 0/0 tests failed
    No unit test coverage for chrome 39.0.2171.65 on Windows NT
    chrome 39.0.2171.65 on Windows NT: 0/0 tests failed
    undefined: Error: Failed to load module angular/angular from /angular/angular.js (parent: *33)
     at http://localhost:9000/__intern/node_modules/dojo/dojo.js:731
     at .run/window.onerror <__intern\lib\realClient.js:57>
    No unit test coverage for firefox 28.0 on LINUX
    firefox 28.0 on LINUX: 0/0 tests failed
    Initialised safari 6.0.5 on MAC
    Initialised safari 7.0.6 on MAC
    undefined: Error: __Failed to load module angular/angular from /angular/angular.js (parent: *33)__
     at http://localhost:9000/__intern/node_modules/dojo/dojo.js:731
    No stack or location
    undefined: __Error: Failed to load module angular/angular from /angular/angular.js (parent: *32)__
     at http://localhost:9000/__intern/node_modules/dojo/dojo.js:731
    No stack or location
    No unit test coverage for safari 6.0.5 on MAC
    safari 6.0.5 on MAC: 0/0 tests failed
    No unit test coverage for safari 7.0.6 on MAC
    safari 7.0.6 on MAC: 0/0 tests failed
    Initialised chrome 39.0.2171.71 on Linux
    undefined: __Failed to load module angular/angular from /angular/angular.js (parent: *33)__
    Error: __Failed to load module angular/angular from /angular/angular.js (parent: *33)__
     at HTMLScriptElement.handler <__intern\node_modules\dojo\dojo.js:731:13>
    No unit test coverage for chrome 39.0.2171.71 on Linux
    chrome 39.0.2171.71 on Linux: 0/0 tests failed
     ---------------------|-----------|-----------|-----------|-----------|
     File | % Stmts |% Branches | % Funcs | % Lines |
    ---------------------|-----------|-----------|-----------|-----------|
     adm-zip\ | 3.55 | 0.36 | 0 | 3.72 |
     adm-zip.js | 3.42 | 0.77 | 0 | 3.5 |
     zipEntry.js | 5.08 | 0 | 0 | 5.5 |
     zipFile.js | 2.53 | 0 | 0 | 2.65 |
     adm-zip\headers\ | 5.34 | 0 | 0 | 5.34 |
     entryHeader.js | 3.13 | 0 | 0 | 3.13 |
     index.js | 100 | 100 | 100 | 100 |
     mainHeader.js | 6.06 | 0 | 0 | 6.06 |
     adm-zip\methods\ | 1.4 | 0 | 0 | 1.49 |
     deflater.js | 0.38 | 0 | 0 | 0.38 |
     index.js | 100 | 100 | 100 | 100 |
     inflater.js | 3.25 | 0 | 0 | 3.81 |
     adm-zip\util\ | 16.04 | 3.64 | 4.17 | 16.67 |
     constants.js | 100 | 100 | 100 | 100 |
     errors.js | 100 | 100 | 100 | 100 |
     fattr.js | 17.39 | 12.5 | 0 | 17.39 |
     index.js | 100 | 100 | 100 | 100 |
     utils.js | 9.09 | 2.13 | 7.69 | 9.59 |
    ---------------------|-----------|-----------|-----------|-----------|
    All files | 3.06 | 0.41 | 0.46 | 3.21 |
    ---------------------|-----------|-----------|-----------|-----------|
     TOTAL: tested 11 platforms, 0/0 tests failed; fatal error occurred

**Comment by csnover** [comment]
@agray The issue problem you are encountering has nothing to do with this ticket. Please do a quick read through the first bullet on our [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md). If you aren’t sure your problem is actually a bug, please ask for help in one of the [other support channels](https://github.com/theintern/intern/wiki/Support) first. Thanks!
