### ISSUE TITLE
Include TypeScript d.ts with Intern releases

### ISSUE THREAD

**Issue by pocesar** [theintern/intern#318]
Typescript have the option to output to AMD using a command line flag, which would, in theory, make creating tests for CommonJS people (like me) less painful. But it's impossible to load things like 

```typescript
import bdd = require('intern!bdd');
import expect = require('intern/chai!expect');
``` 

what is the best approach? no typings for intern yet?

**Comment by csnover** [comment]
TypeScript typings for Intern were added at https://github.com/theintern/intern/commit/2cff175ee479866fcced1ce24b9584488400f062 and will be available in the next release!
