### ISSUE TITLE
Reporters Should Show Test Summary Last

### ISSUE THREAD

**Issue by Walexander** [theintern/intern#327]
I use a 15-20 line high tmux pane to run unit tests during TDD.  This allows me to see the results of the latest change without leaving the editor.  When a reporter shows the code coverage results after the test summary, the test results are scrolled out of view.

Here's a screen shot showing the problem.
[Hidden Intern Output](https://www.dropbox.com/s/x0x3cglljwwwel8/Screenshot%202015-01-02%2020.43.49.png?dl=0)

Command line tools tend to print summary information to the console in reverse order of importance.  Code coverage reporting is undoubtedly a great feature and I recognize it's important to make sure it's available out-of-the-box. But the test results are the most important piece of information the intern provides during TDD.  It seems reasonable for them to be printed last.

**Comment by anatoliyarkhipov** [comment]
I agree with that. It would be nice to add a parameter to the reporters config. Maybe, something like:
```javascript
{
  reporters: [
    { id: 'console', coveragePosition: 'top|bottom|null' }
  ]
}
```

I also was trying to implement a custom reporter and override the original `console` reporter to prevent the rendering of coverage, but I can't load the original because it requires the `dojo/lang` module from `intern/node_modules/dojo` and I can't understand how to properly define paths.

**Comment by anatoliyarkhipov** [comment]
As I just learned, it's possible to prevent displaying of coverage by adding this line to the `all.js` (your main test script, which loads others):

`global.__internCoverage = undefined`

**Comment by jason0x43** [comment]
You can also set `excludeInstrumentation: true` in your intern config to entirely disable code coverage. Since the main goal seems to be to disable coverage information, I'm closing this issue. We can reopen it if people really need output reorganization.
