### ISSUE TITLE
Can you add DalekJs to the compare section?

### ISSUE THREAD

**Issue by rahul286** [theintern/intern#334]
Similar to - https://github.com/theintern/intern/issues/232

Can you please add http://dalekjs.com/ to http://theintern.io/#compare ?

**Comment by csnover** [comment]
DalekJS seems to be mostly a dead project, with a “don’t use this in production” warning, so I would just recommend…not using it. Given its relative lack of popularity and the limited amount of space on the Web site this information won’t be presented there, but for the sake of completeness, here are the results (based on reviewing their documentation):

<table>
	<tbody>
		<tr>
			<th>Feature</th>
			<th><a href="https://github.com/theintern/intern">Intern</a></th>
			<th><a href="http://dalekjs.com/">DalekJS</a></th>
		</tr>
		<tr>
			<th scope="row">Includes unit testing</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Includes functional testing</th>
			<td class="yes">Yes</td>
			<td class="yes">Yes</td>
		</tr>
		<tr>
			<th scope="row">Code coverage analysis</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">True browser events</th>
			<td class="yes">Yes</td>
			<td class="yes">Yes</td>
		</tr>
		<tr>
			<th scope="row">Native AMD support</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Stand-alone browser support</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Node.js support</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Source map support</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Any assertion library</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Default test interface</th>
			<td class="yes">TDD, BDD, object</td>
			<td class="maybe">Object</td>
		</tr>
		<tr>
			<th scope="row">Extensible test interfaces</th>
			<td class="yes">Yes</td>
			<td class="maybe">No</td>
		</tr>
		<tr>
			<th scope="row">Extensible reporters</th>
			<td class="yes">Yes</td>
			<td class="no">Yes</td>
		</tr>
		<tr>
			<th scope="row">Asynchronous support</th>
			<td class="yes">Promises</td>
			<td class="no">Custom API</td>
		</tr>
		<tr>
			<th scope="row">Selenium support</th>
			<td class="yes">Yes</td>
			<td class="maybe">Incomplete</td>
		</tr>
		<tr>
			<th scope="row">Fixes Selenium bugs</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Tests native mobile apps</th>
			<td class="yes">Yes</td>
			<td class="yes">Yes</td>
		</tr>
		<tr>
			<th scope="row">Built-in CI support</th>
			<td class="yes">Yes</td>
			<td class="maybe">Partial</td>
		</tr>
		<tr>
			<th scope="row">Built-in Sauce Labs integration</th>
			<td class="yes">Yes</td>
			<td class="no">Extension</td>
		</tr>
		<tr>
			<th scope="row">Built-in BrowserStack integration</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Built-in TestingBot integration</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Built-in Travis CI integration</th>
			<td class="yes">Yes</td>
			<td class="no">No</td>
		</tr>
		<tr>
			<th scope="row">Grunt support</th>
			<td class="yes">Yes</td>
			<td class="maybe">Extension</td>
		</tr>
	</tbody>
</table>

**Comment by rahul286** [comment]
@csnover thanks for your time and advice. :-)
