### ISSUE TITLE
support timeout for ES6 promises

### ISSUE THREAD

**Issue by wkeese** [theintern/intern#337]
For example, on Chrome or using a shim like lie, try this code:

        "test Promises": function () {
            this.timeout = 100;
            return new Promise(function (resolve) {
                setTimeout(resolve, 20000);
            });
        },

It will not timeout after 100ms.   Apparently setting `this.timeout` only works if the Promise returned by the test is a dojo/Deferred, or perhaps it only works if the promise returned has a `reject()` and/or `cancel()` method.  But ES6 Promises don't have either.

If you continue to use dojo Deferred, then you can simply decorate the functions return value using when().

**Comment by csnover** [comment]
This will be resolved; for the moment you should be able to just `var dfd = this.async(100); dfd.resolve(new Promise(…));`.

**Comment by Arnavion** [comment]
The workaround doesn't work. The deferred resolves itself with the promise, instead of waiting for the promise to be resolved and taking its state, so the test passes immediately instead of waiting for the timeout and failing. Instead, I had to do the equivalent of:

```javascript
var dfd = this.async(100);
new Promise(...).then(dfd.resolve.bind(dfd), dfd.reject.bind(dfd));
return dfd.promise;
```
