### ISSUE TITLE
Allow specifying proxyPort and proxyUrl as command line arguments for intern-runner

### ISSUE THREAD

**Issue by mgingras** [theintern/intern#338]
I've written a nodeJS app to split up my functional suites and spawn child processes to start an intern-runner to run each suite concurrently against a docker images housing a selenium hub, registered with ~25 docker images with selenium nodes. 

To run concurrently each intern-runner needs its own config file so it has a unique port which, while it is possible to generate these programmatically, it is not ideal. By being able to pass in a proxyPort command line argument this would be avoidable.

**Comment by vladikoff** [comment]
```javascript
define([
  'intern/lib/args'
],
function (args) {

  var config = {
    proxyPort: args.proxyPort || 9090,
   ....
  }

  return config
});
```
Does something like this not work?

**Comment by mgingras** [comment]
:+1: That does work. Thank you.
