### ISSUE TITLE
Feature Request: Automatic retries for failed tests

### ISSUE THREAD

**Issue by sholladay** [theintern/intern#340]
### Problem
Some types of tests, particularly functional tests and any that rely upon a network, are prone to sporadic reliability problems. For users of Continuous Delivery systems, this is extremely undesirable. People get e-mailed, passwords are needed to cleanup the logs, etc.

### Solution
Some opt-in machinery to automatically retry failed tests, which will help smooth over minor timing glitches.

**Example**:
An `intern.js` configuration file could have:
````javascript
...
// Default : 1
maxTries : 3
...
````
... and that would cause any given test to be able to run up to 3 times total.

**Comment by csnover** [comment]
Yes, this is a possibility. In the interim you can just write a simple helper function to perform a retry. Something like this might work (not tested):

```js
function retry(maxRetries, test) {
  var numExecutions = 0;

  return function () {
    var self = this;
    var args = arguments;

    function retry(lastError) {
      var dfd = new Deferred();
      var promise;

      if (++numExecutions <= maxRetries) {
        var result;
        try {
          result = test.apply(self, args);
          dfd.resolve(result);
        }
        catch (error) {
          result = error;
          dfd.reject(result);
        }

        promise = dfd.promise.otherwise(retry);
      }
      else {
        dfd.reject(lastError);
        promise = dfd.promise;
      }

      return promise;
    }

    return retry();
  };
}

registerSuite({
  foo: retry(3, function () {
    // this test will be run up to 3 times
  })
});
```

**Comment by sholladay** [comment]
Great! And thanks for the example snippet.

**Comment by vladikoff** [comment]
@jason0x43 this can be closed I think

**Comment by sholladay** [comment]
Yeah, I take it back. Tried to be level headed about it, but this is the making of a footgun.

**Comment by neilk** [comment]
It's generally a bad idea to retry tests a lot. But in case anyone else really needs this (I do, for a temporary situation), here's a simple `retry` implementation that is working for me.

```
 function retry (maxTries, p) {
    var tries = 0;
    var iter = function() {
      tries++;
      return p().catch(function(error) {
        console.log(">>> Test errored on try " + tries + "/" + maxTries)
        if (tries <= maxTries) {
          return iter();
        } else {
          return Promise.reject(error);
        }
      });
    };
    return iter();
  }
```
