### ISSUE TITLE
Support setting this.timeout for the Test in beforeEach

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#342]
Tracking bug for: Support setting `this.timeout` for a Test in `beforeEach`

Currently setting `this.timeout` in `beforeEach` does not work. 
```
beforeEach: function () {
      // Set value
      this.timeout = 90000;

      return client.signUp(email, PASSWORD);
    },

'reset password, verify same browser': function () {
      console.log('this.timeout: %s', this.timeout);  // timeout is 30000 in the test

      return FunctionalHelpers.openFxaFromRp(self, 'signin')
        .getCurrentUrl()
        .then(function (url) {
            /// ....
        })
```

Ref: https://github.com/mozilla/fxa-content-server/issues/2078

**Comment by jason0x43** [comment]
In an upcoming release the test object will be passed to `beforeEach` and `afterEach`, at which point you could set `test.timeout`.

**Comment by vladikoff** [comment]
Thank you @jason0x43 !

**Comment by csnover** [comment]
https://github.com/theintern/intern/commit/0450494c616d7dcdd1360b6425c7667c1c6513d8

**Comment by zaach** [comment]
I'm on 3.0 and this doesn't seem to work for me, e.g.:

```
    afterEach: function (test) {
      console.log('test', test);
      return FunctionalHelpers.clearBrowserState(this);
    },

    'some test yadada': function () {
    .....
```

Is logging `test undefined`.

**Comment by vladikoff** [comment]
@zaach does it work in `beforeEach` ?

**Comment by zaach** [comment]
No, it's undefined there too.

**Comment by vladikoff** [comment]
Looking at the tests for the PR https://github.com/theintern/intern/commit/0450494c616d7dcdd1360b6425c7667c1c6513d8 it seemed to work for that.

Our `beforeEach` is here https://github.com/mozilla/fxa-content-server/blob/master/tests/functional/sign_in.js#L39 

@csnover any idea?

**Comment by csnover** [comment]
yes, it is the aspect call in the interface that does not pass the arguments correctly.

**Comment by vladikoff** [comment]
@csnover should this be reopened?

**Comment by csnover** [comment]
No, this ticket is about timeouts.

**Comment by csnover** [comment]
I’m finishing unit tests for a fix so it’ll be addressed soon.

**Comment by csnover** [comment]
Oh, just to mention in the meantime if you Just Can’t Wait, this problem is isolated to the test interface so you can write and use a custom one that is fixed temporarily (by changing the `aspect` calls).

**Comment by vladikoff** [comment]
No it's ok, no rush :dancer:  Thanks Colin!!
