### ISSUE TITLE
Defining a loader map property of ‘*’ prevents intern runner from loading dojo node module

### ISSUE THREAD

**Issue by plumlee** [theintern/intern#348]
A user-defined loader `map` property with a `*` property means you have to redefine the `intern/dojo` path yourself.  If not, you get the following when trying to run a test:
```
$ ./node_modules/.bin/intern-runner config=test/config/intern-functional
FATAL ERROR
Error: Failed to load module intern/dojo/node from /Users/path/to/repo/node_modules/intern/dojo/node.js (parent: intern/dojo/node!38!*)
  at <node_modules/intern/node_modules/dojo/dojo.js:757:12>
  at <fs.js:208:20>
  at Object.oncomplete  <fs.js:108:15>
```

I’m using a base configuration for intern like so:

```
    loader: {
        map: {
            '*': {
                'chai'       : '../../../node_modules/chai/chai',
                'sinon'      : '../../../node_modules/sinon/pkg/sinon',
                'sinon-chai' : '../../../node_modules/sinon-chai/lib/sinon-chai'
            }
        }
    },
```

Then I override particular settings for each kind of test I run (unit, functional) by extending this config. When running a functional test like using the command and the test example below, I get the error shown above.

This line - https://github.com/theintern/intern/blob/2.2.2/runner.js#L83 - doesn’t preserve the default mapping that intern expects, as defined earlier in the same file: https://github.com/theintern/intern/blob/2.2.2/runner.js#L13

Seems like runner.js should load with that base config, then reload itself and merge my config with the defaults for  `map` to preserve the needed intern paths.

Feels like it could get really complicated, trying to figure out what mappings the user might have overwritten, and what mappings intern should keep. I’m wondering if the simplest fix is to add a line of documentation here: https://github.com/theintern/intern/wiki/Configuring-Intern#loader
that states you must map the `intern/dojo` path if you defined a mapping for ‘*’, or maybe that you must redefine any intern paths that you want to reuse, such as for chai or dojo loaded by intern. 

 In the end, it’s not really a bug so much as a non-obvious possible side effect of defining your own loader configuration. I don’t think a user should have to know how intern defined its own paths internally and when those have to be redefined, but it’s not out of the question to expect a user to understand the implications if it’s noted in the documentation.

I’m happy to throw up a test repo if that would make this clearer. Also, if you’ll let me know what solution you’d prefer, I’ll do a pull request.

**Comment by csnover** [comment]
I’ll make sure users aren’t able to clobber the built-in star map but just FYI you should probably be using `paths` since you are trying to remap module IDs to different physical paths. (Probably so should Intern, but at some point I think there was a reason why node_modules was being treated as part of the module ID.)

**Comment by plumlee** [comment]
Thanks for the heads up. I was using map because it seemed to be the simplest way to just put ‘sinon’ in a define statement, versus having to do ‘PATH/sinon’, but sounds like that’s a misuse. I reread the docs on AMD and see where that’s not the purpose.
