### ISSUE TITLE
Can not run unit tests that have "dijit/nls/common.js" and "dijit/nls/loading" as dependencies

### ISSUE THREAD

**Issue by fuje** [theintern/intern#349]
When running intern-runner in a unit test that have a component that have "dijit/Dialog" as one of its dependencies, I'm getting the following error:

```
FATAL ERROR
undefined: deps.map is not a function
  at resolveDeps  <__intern\node_modules\dojo\dojo.js:678:4>
  at defineModule  <__intern\node_modules\dojo\dojo.js:693:5>
  at injectModule/onLoadCallback  <__intern\node_modules\dojo\dojo.js:649:7>
  at injectUrl/handler  <__intern\node_modules\dojo\dojo.js:728:7>
  at xhr  <main\webapp\js\dojo\dojo\request\xhr.js:176:1>
  at _5  <main\webapp\js\dojo\dojo\text.js:12:27>
  at .load  <main\webapp\js\dojo\dojo\text.js:87:8>
  at injectPlugin  <__intern\node_modules\dojo\dojo.js:608:5>
  at execModule/<  <__intern\node_modules\dojo\dojo.js:543:7>
  at forEach  <__intern\node_modules\dojo\dojo.js:220:4>
  at execModule  <__intern\node_modules\dojo\dojo.js:535:5>
  at checkComplete/<  <__intern\node_modules\dojo\dojo.js:582:7>
  at guardCheckComplete  <__intern\node_modules\dojo\dojo.js:566:4>
  at checkComplete  <__intern\node_modules\dojo\dojo.js:574:4>
  at injectModule/onLoadCallback  <__intern\node_modules\dojo\dojo.js:656:7>
  at injectUrl/handler  <__intern\node_modules\dojo\dojo.js:728:7>
```

Assuming we have the dijit package loaded by our configuration file, a simple test like this is going to throw the error above:
```javascript
define([
    'intern!object',
    'intern/chai!assert',
    'dijit/Dialog'
], function (registerSuite, assert, errorHandler) {

	registerSuite({
        name: 'error handler test',
        
        'verify ': function() {
            // test here
        }
    });
	
});
```

After debugging, I found that the Intern default AMD Loader can not load "dijit/nls/common.js" and  "dijit/nls/loading" modules, that are dependencies of the "dijit/Dialog" module.

__Reproduced this issue using:__
__Dojo 1.10.3__
__Dijit 1.10.3__
__Intern 2.2.2__

Case needed, I can put the test project that I used in a repository. 
Thanks in advance.

**Comment by csnover** [comment]
It looks like there might be a bug in the built-in loader, I still need to investigate; you might try using `useLoader` to switch to the Dojo 1 loader in the meantime. Look to [dojo-boilerplate](https://github.com/csnover/dojo-boilerplate/blob/master/tests/intern.js) to learn how to do this.

**Comment by csnover** [comment]
It looks like I am not going to have time to investigate this for quite a while, so I would definitely appreciate it if anyone could work on tracking down what is going on here.

**Comment by RoystonS** [comment]
We're happily creating Dialogs in our unit tests, and components derived from Dialogs (with Intern 2.2.2), so I don't think it's quite as simple as Dialog being a problem.

We've certainly seen the error you give before: it's usually emitted by Intern when it comes across a module with a define call that doesn't have a dependency array as its first parameter.

On the face of it, loading one of the nls files such as nls/common.js would cause this to break, as it defines a map with no dependencies array - and if you brought it in directly it would - but Dialog.js loads it through the i18n plugin, via dojo/i18n!./nls/common, which loads it in a different way which shouldn't trip up the Intern loader.

Do you have some other module that is loading NLS files without going through the dojo/i18n plugin?

**Comment by jason0x43** [comment]
I haven't been able to reproduce this just by loading `dijit/Dialog`. Loading a module without a dependency array shouldn't be a problem; the default Intern config uses that format, and loading `nls/common` directly in a test doesn't break Intern's loader (at least not in the simple case below):

```js
define([
	'intern!object',
	'intern/chai!assert',
	'dijit/nls/common'
], function (registerSuite, assert, common) {
	registerSuite({
		name: 'something',

		aTest: function () {
			assert.ok(common);
		}
	});
});
```

**Comment by brakon** [comment]
I can reproduce the same error message by adding a test that uses "supertest" to simulate a request to a kraken/express app.
```
TypeError: undefined is not a function
  at Parser.<anonymous>  <node_modules/engine-munger/node_modules/localizr/node_modules/findatag/lib/parseStream.js:89:15>
  at Parser.g  <events.js:199:16>
  at Parser.emit  <events.js:104:17>
  at Parser.end  <node_modules/engine-munger/node_modules/localizr/node_modules/findatag/lib/parser.js:300:10>
```

Example of the test setup:
```
define(['intern/dojo/node!kraken-js', 'intern/dojo/node!express', 'intern/dojo/node!supertest', 'intern!bdd'], function (kraken, express, request, bdd) {
```

From what I've seen, it seems that even though we load kraken-js with intern/dojo/node so it supports commonJS modules, it is showing "define" as available when require'ing krakenjs dependent modules, for which some have if (typeof define !== 'undefined' && define.amd) { which basically mixes behaviors.

**Comment by brakon** [comment]
I see that intern does hide "define" for the right reason, but somehow, when doing through internal require calls on the dependencies, it is having the "define" function available making it think its an AMD loader, when it should actually be a Node/CommonJS loader.
```
// Some modules attempt to detect an AMD loader by looking for global AMD `define`. This causes issues
// when other CommonJS modules attempt to load them via the standard Node.js `require`, so hide it
// during the load
```

**Comment by csnover** [comment]
@brakon That error isn’t even close to the same as the one in the OP? Why do you think it has anything to do with loading Node.js modules? The loading has finished successfully by that point, something in your code is passing `undefined` as a callback to a transform stream.

**Comment by brakon** [comment]
This is an issue with how intern loads node/commonJS modules and the async library.

We load kraken in the intern test by doing:
var kraken = require('intern/dojo/node!kraken-js');

This is loading multiple dependencies including the v0.2 of the "async" module (caolan/async)
The async module does 
```
if (typeof define !== 'undefined' && define.amd) {
        define([], function () {
            return async;
        });
    }
    // Node.js
    else if (typeof module !== 'undefined' && module.exports) {
        module.exports = async;
    }
```

And it seems "define" exists in this context,  even though we told Intern to load kraken as a common js module. Hence require(async) becomes {} when called, since it doesn't expose the module.exports given "define" exists.

Options here:
- Why does intern allow define to exist for loading dependencies of a module loaded with dojo/node
- Dont use v0.2 of async for modules that will be tested with Intern (newest version of async first check for module.exports rather than checking for "define" first.
  ** 0.2 is broadly use so it limits the use of intern

**Comment by csnover** [comment]
@brakon The issue you are describing has nothing to do with the original report in this ticket. Please feel free to create a new ticket, though what you say is happening would only happen if that other module was dynamically loaded (i.e. not in the factory function of the dependent module) and there is no way for us to guard against that, so I don’t think there is any action that we could take.

**Comment by brakon** [comment]
Yes that seems to be the case, I will submit a request for kraken to update the version of the async library for the newest one that doesn't check for AMD first.
Thanks for the help

**Comment by csnover** [comment]
Closing due to no response from OP. Please let us know if this is still a problem by answering the earlier questions and we will reopen the ticket. Thanks!
