### ISSUE TITLE
Configurable Test.timeout with intern-runner

### ISSUE THREAD

**Issue by samplesizeofone** [theintern/intern#350]
Please consider providing an interface to change `Test.timeout` ( https://github.com/theintern/intern/blob/master/lib/Test.js#L22 ) when running tests via intern-runner.

In my case, the fixed value of 30,000 is low enough that tests intermittently fail on SauceLabs, BrowserStack, and crossbrowsertesting.com (and on rare occasion locally) with:

```
Initialised internet explorer 10 on WINDOWS
Test main - hero - visible FAILED on internet explorer 10 on WINDOWS:
CancelError: Timeout reached on main - hero - visible
Error: Timeout reached on main - hero - visible
  at Error  <anonymous>
  at new ErrorCtor  <node_modules/intern/node_modules/dojo/errors/create.js:13:21>
  at null._onTimeout  <node_modules/intern/lib/Test.js:180:38>
  at Timer.listOnTimeout [as ontimeout]  <timers.js:112:15>
```

When the timeout is raised to 90,000, my tests run reliably. There may be contributing factors in my setup that cause the timeout value to be exceeded, but I think configurable timeout values are a good thing in the general case.

**Comment by csnover** [comment]
You can set the timeout by setting `this.timeout` from within a test. Is there something more that you need?

**Comment by samplesizeofone** [comment]
Oh, I didn't realize `this.timeout` was the same as `Test.timeout`, though now that you point it out, it is abundantly clear :-)

I'll go ahead and pivot my request to be for a built-in, global setting in addition to the ability to set the timeout per-test. If a global setting doesn't make sense, feel free to close this ticket and I'll work at the per test level and/or see about setting `Test.prototype.timeout` somewhere reasonable.

Thanks!
