### ISSUE TITLE
pretty reporter needs to work better with Travis

### ISSUE THREAD

**Issue by csnover** [theintern/intern#358]
Right now we end up dumping tons of stuff out because it doesn’t understand the Erase Display control code and the reporter runs on an interval instead of redrawing once an event occurs. It also looks like download % output is wrong.

**Comment by csnover** [comment]
According to a Travis engineer the only ANSI codes that work are colours, \r, and Clear Line.

**Comment by jason0x43** [comment]
Just out of curiosity, why use the pretty reporter on Travis?

**Comment by csnover** [comment]
Because the default runner reporter is ugly and confusing.

**Comment by csnover** [comment]
I just updated the Runner reporter for now, this can be revisited later if someone wants to try.
