### ISSUE TITLE
Normalize excludeInstrumentation paths

### ISSUE THREAD

**Issue by csnover** [theintern/intern#360]
When running on Windows, the behaviour of `excludeInstrumentation` is confusing because it operates on paths and the resolved paths on that platform use backslash instead of forward slash.

**Comment by csnover** [comment]
There are only two places in the code that use `excludeInstrumentation` and in both cases it should be easy to just run `.replace(/\\/g, '/')` on the path being passed to it.

**Comment by Arnavion** [comment]
The code coverage report also shows filenames with backslashes on Windows right now, so doing it just for excludeInstrumentation is not ideal. Perhaps normalize filenames to forward slashes as soon as you get them?

**Comment by csnover** [comment]
The output for coverage reporters is handled by Istanbul so I’m not sure how much control we have there—at least, not without breaking those reporters. Is there a particular problem with the filenames in the coverage reports having backslashes?

**Comment by Arnavion** [comment]
It would be inconsistent - filenames are considered to be separted by / for the code coverage regex even though the report shows them with backslashes.
