### ISSUE TITLE
Arbitrary chevrons added in custom reporter

### ISSUE THREAD

**Issue by MartinDoyleUK** [theintern/intern#367]
When consistently using `console.log` in my custom reporter for Intern I arbitrarily but consistently have the line modified in that it seems to trim the line and then prefix it with two chevrons (`>>`). This happens when I output a test result (e.g. from "/test/pass") and also in the `stop()` method when I output the following string `"========\nFAILURES\n========"` it comes out as `"========\n>> FAILURES\n========"`, where the chevrons in this instance are also red.

If I could understand what was happening, I would try and create a pull request, but I can't find where in the codebase this may be happening.

**Comment by jason0x43** [comment]
It sounds like you're running Intern via its Grunt task. When you run Intern with Grunt, the Grunt task processes everything logged to the console. When it sees PASS or FAIL messages it sets the Grunt logging state to 'ok' or 'error', and Grunt decorates the output.

In a future version of Intern we'll use a dedicated reporter for the Grunt task that allows it to mark up output more intelligently. With the current version, the easiest solution is to refrain from using text matching the regexes `/\bPASS/` or `/\bFAIL/` unless you want the decorations.

**Comment by MartinDoyleUK** [comment]
Thank you so much for this ... I hadn't even considered that Grunt was hijacking my output. Your patience and help is very gratefully welcomed!
