### ISSUE TITLE
Taking a screenshot of any failing test

### ISSUE THREAD

**Issue by nwhite89** [theintern/intern#368]
It would be nice if it is possible to setup intern to take and save a screenshot when ever a single test fails and not have to write it within the test is this currently possible or could this be a possible add-on for the future?

**Comment by RoystonS** [comment]
FYI, we tried to do this with a reporter a while back, but reporters currently have to run synchronously, so we couldn't do it that way.  (We'd request that a screenshot be taken, but the test would have been cleared down and the next test running by the time the screenshot happened.)

As a workaround, we ended up wrapping and intercepting 'bdd.js' with our own custom version that wraps all tests with an extra handler that takes a screenshot when erroring.  (That can work with, and return, promises, so we can block the teardown and next test until the screenshot completes.)

**Comment by dylans** [comment]
This is a pretty frequently asked question, see the following links for some suggestions:
https://stackoverflow.com/questions/27850786/take-screenshot-for-failed-test-in-internjs
https://stackoverflow.com/questions/22531122/how-do-i-take-a-screenshot-and-write-to-a-file-in-intern-javascript-testing
https://stackoverflow.com/search?q=[intern]+screenshot

**Comment by nwhite89** [comment]
@dylans yeah I did come across both of them however, the soultions mean you have to write the screenshot for every test whereas really it would be better to add it to ``afterEach`` for the registered suite, or even better being able to have something in the overall intern configuration

**Comment by nwhite89** [comment]
So I have done this @RoystonS you may be interested, this needs doing in every place you set up a suite but is much more desirable than writing the code for every test.

```js
var counter = -1,
    suite = {
        beforeEach: function () {
            counter++;
        },
        afterEach: function () {
            var currentTest = this.tests[counter];
            if (!currentTest.error) {
                return;
            }
            this.remote
                .takeScreenshot().then(function (buffer) {
                    if (!fs.existsSync(path)) {
                        fs.mkdirSync(path);
                    }
                    fs.writeFileSync('/tmp/' + currentTest.name + '.png', buffer);
                });
        }
    };
```

**Comment by dylans** [comment]
@nwhite89 I also mentioned it as I'm hoping someone will be inspired to work on a patch / pull request, in case we don't have time to get to it soon!

**Comment by nwhite89** [comment]
I see @dylans, would you see this as a top configuration of intern passing the location you wish to write the screenshots? because I could try look at it at some point to do a PR into intern.

**Comment by RoystonS** [comment]
@nwhite89 The workaround we have means we don't touch any of our tests except for having all our test files bring in our own version of the 'bdd.js' interface file.  In that, we provide an alternative version of 'it' which delegates onto the real bdd it function, but wraps the function passed to take screenshots where errors are occurring.  We definitely didn't want to have to add afterEach calls to all of our suites.  (We were using an alternative bdd.js file anyway in order to provide ourselves with useful 'xit/xdescribe' functions (like Jasmine provides) which makes it easy to disable individual tests.)

But yes, ideally Intern would provide its own first class support for this directly, especially as it's not possible to do this with the existing reporter APIs.

**Comment by dylans** [comment]
@nwhite89 yes, a configuration setting for the location would be great

**Comment by nwhite89** [comment]
@dylans ok cool sounds good to me I'll try take a look at it next week :+1:

**Comment by csnover** [comment]
Reporters in Intern 3 will be able to asynchronously pause the flow of the test system in order to do things like request screenshots when a test fails!
