### ISSUE TITLE
After and Before each not passed the test

### ISSUE THREAD

**Issue by nwhite89** [theintern/intern#369]
It seems quite confusing to me that within the ``beforeEach`` and the ``afterEach`` functions are fired they're not passed as an argument the test that has just fired / about to be fired. Instead you have to do something with a counter checking through an array of tests

**Comment by csnover** [comment]
This has already been fixed in https://github.com/theintern/intern/commit/0450494c616d7dcdd1360b6425c7667c1c6513d8 and will be part of Intern 3!
