### ISSUE TITLE
Feature Request: collapsible suites in client.html UI

### ISSUE THREAD

**Issue by albell** [theintern/intern#374]
This is the one aspect of Intern I wish were more like Qunit :open_mouth:

Things get trickier to inspect visually as the number of tests climbs into the thousands.

Simple accordions would work. The idea, as in Qunit, would be to initially collapse all suites that have all contained tests passing. Any test that fails would have all ancestor suites initially expanded, to show the error.

BTW - Amazing work, you guys. Thank you.

**Comment by csnover** [comment]
I have no objections to adding this at all, anything to improve the user experience is great, but I did also want to confirm you do see the checkbox for hiding all successful tests at the top of the list of tests?

**Comment by baloneysandwiches** [comment]
Yeah, I've been using it. :smile: It just would be nice to have the option to go a bit more granular, dialing in between "show everything" and "just the failures" when the failure pattern isn't totally clear. It works well, but the option to inspect specific suites would be nice convenience, especially in large suites with multiple subsuites and sub-sub-suites etc.
