### ISSUE TITLE
More intuitive configuration names.

### ISSUE THREAD

**Issue by sholladay** [theintern/intern#377]
Intern 3.0 seems to be making a big deal about the first-time user. So even though this is nitpicky and also a breaking change, I thought it may be worth mentioning. When starting to use Intern, one of the first barriers I hit was understanding the intention behind each configuration option. It was relatively easy to find examples with names that Intern cared about, but it was hard to know exactly what data format was expected or in what scenarios it was needed (ran into lots of issues with the environments objects, for example).

The documentation is improving a *ton* on this front, so thanks and cheers for that! But I want to propose a few things:

1. The current `useLoader` becomes `loader`
2. The current `loader` becomes `loaderOptions`
3. The current `grep` becomes `filter` (or similar)

As a newcomer to AMD, especially given that every example config file I saw used only `loader` and did not use `useLoader`, it was very confusing as to what kind of behavior I was changing. The thought process was along the lines of, "Huh? I thought Intern loads what I need with this define([...], fn) thing?" And seeing {package: 'myPackage'} made it seem like it was very important data that I had to populate. Eventually I discovered that I didn't even need it for my use case with functional testing, which is what I came to Intern for.

If the same exact example config said `loaderOptions`, it would be significantly more intuitive what was going on and whether it mattered. It would also be more consistent with configuring Dig Dug via `tunnel` and `tunnelOptions`, etc.

As for `grep`, why limit to a regex? I want to specify an array of test name strings or simpler regexs, etc. This could be so much more powerful, so I vote to name it after what seems like the actual intention, rather than an analogy based on the current implementation.

**Comment by dylans** [comment]
These are good suggestions, and I agree it makes things clearer and more consistent. I'm not sure if we have time to address this prior to Intern 3.0 as we're very close to release, meaning I probably wouldn't block a release for these changes, but they're worth considering if easy and if time permits.

**Comment by sholladay** [comment]
Thanks and yeah, that's understandable. Since I'm guessing this would have to either land now or wait quite a long time (next major), I hereby offer to handle all documentation changes if the code gets refactored.

**Comment by csnover** [comment]
`loader` is currently destined to change to `loaderConfig`, and `useLoader` to `loaders`, in Intern 3. Is this better?

`grep` is named what it is because that is the name used by other test systems for the same functionality. A regular expression gives you all the power of a list of arrays (use an expression group) plus fuzzy matching so is more powerful than using an array without any added complexity in the test system to support parsing multiple data structures from command-line, etc.

**Comment by sholladay** [comment]
Good enough for me. Although I will point out that [anymatch](https://www.npmjs.com/package/anymatch "Documentation for the anymatch library.") is perfect for this sort of thing, for projects that desire flexibility.

**Comment by csnover** [comment]
OK. Trying to avoid changing any more things for 3.0; if you want to submit a ticket/PR for the other one we can probably do it later.
