### ISSUE TITLE
browser fails to start tests when there are too many suites in configuration because url gets too long

### ISSUE THREAD

**Issue by bartoszkaczorek** [theintern/intern#379]
Hi,

When there are too many suites in intern configuration, the url will get very long (it's adding &suites=... parameter for each test suite) and browser will fail to start the tests. 
To avoid it currently I'm creating a parent suite that imports all of my suites, and put only that parent inside intern configuration.
	
Thanks,
Bart

**Comment by dylans** [comment]
This is one of the reasons why we will typically do something like https://github.com/dojo/dojo/blob/master/tests/unit/all.js within our tests (the other reason being that it's nice to not have to modify the configuration file each time we run a test). Other people have also written code that uses Node's fs module to load each test within a directory, as documented at https://theintern.github.io/intern/#option-suites

At a minimum, the documentation on this issue should probably more clearly state that if you have a large number of tests to run, you need to take one of these approaches.

**Comment by csnover** [comment]
No, @dylans, this was a bug introduced in the 2.2 lifecycle. The suites from the configuration aren’t supposed to be forwarded into the arguments but that started happening because the override order was reversed. This won’t happen in 3.0.

**Comment by dylans** [comment]
Ok then, glad that wasn't intentional!

**Comment by csnover** [comment]
This has been fixed as part of the refactor for Intern 3!
