### ISSUE TITLE
locvinfo reporter does not exist

### ISSUE THREAD

**Issue by bartoszkaczorek** [theintern/intern#380]
Hi,

In the user guide there is a "lcovinfo" reporter listed, but intern fails when trying to use it. Was it supposed to be "lcovhtml" reporter? (it is not listed, but works fine)

https://theintern.github.io/intern/#reporter-lcov

Thanks,
Bart

**Comment by dylans** [comment]
@bartoszkaczorek yes, it's lcovhtml. We'll get the guide updated, thanks for the report.
