### ISSUE TITLE
Config option "leaveRemoteOpen" is not easy to use.

### ISSUE THREAD

**Issue by sholladay** [theintern/intern#397]
After running a browser test that fails, I almost always want the browser to remain open, if possible. Therefor, the "leaveRemoteOpen" option is critical for me. However, it is confusing that it cannot be set from within the `intern.js` configuration file, unlike every other option I am aware of.

I assume this was done to save time, on the theory that you wouldn't want to leave it around. But in my case, people try to put it in there anyway and I end up having to tell them it goes in `Gruntfile.js` instead and they give me a weird look before shaking their fist.

My team uses a Grunt watch task to run Intern tests when any code changes. The fact that Intern has consolidated configuration makes this a real pleasure, as we can edit that file with Sublime Text (etc.), hit `Command + S`, and _boom_ ... with no arrow-ing around on the terminal.

Please support the standard config hierarchy, if at all possible, for `leaveRemoteOpen`. Thanks!

**Comment by csnover** [comment]
Intern 3 normalizes all arguments by mixing them into the configuration data, so this should already work as expected in the next release.

**Comment by sholladay** [comment]
That is fantastic. Little things like this go a long way. :+1:
