### ISSUE TITLE
Improve handling of Sauce Labs hangs

### ISSUE THREAD

**Issue by csnover** [theintern/intern#4]
For whatever reason, Sauce Labs VMs sometimes manage to get stuck, and then session times out but we aren’t aware of it because there is no error notification. We need to implement a hang detection and retry mechanism. There are at least two conditions:
1. Sauce Connect forcibly closes the socket
2. The VM just sits there doing nothing until the session times out

**Comment by agray** [comment]
I think I just experienced this issue.  Jenkins 1.597 connecting to SauceLabs building Intern angular-example.

Jenkins console:
    C
    o
    n
    n
    e
    c
    t
    i
    o
    n
    e
    s
    t
    a
    b
    l
    i
    s
    h
    e
    d
    .
    Ready
    Error: socket hang up
     at createHangUpError <http.js:1477:15>
     at Socket.socketOnEnd <http.js:1573:23>
     at Socket.g <events.js:180:16>
     at Socket.emit <events.js:117:20>
     at <_stream_readable.js:944:16>
     at process._tickCallback <node.js:442:13>
     TOTAL: tested 0 platforms, 0/0 tests failed; fatal error occurred
    npm ERR! Test failed. See above for more details.
    Build step 'Execute Windows batch command' marked build as failure 
    buildstep.4Finished: FAILURE

**Comment by csnover** [comment]
This ticket is about Sauce Labs tunnel hanging the test process without throwing an error. An error is being thrown in your case, so it is not related to this issue.

**Comment by agray** [comment]
Any suggestions on where the error is emanating from so I can follow up
with someone else?
