### ISSUE TITLE
Newer versions of Chai cannot be loaded using module map in RequireJS

### ISSUE THREAD

**Issue by csnover** [theintern/intern#400]
Chai uses component for builds, and component uses the incorrect 3-argument define call when using a UMD wrapper, so it’s impossible to load chai using `map` in RequireJS (it always ends up being `undefined`).

Refs chaijs/chai#362.

**Comment by csnover** [comment]
For the moment, using a GitHub fork archive until the issue is resolved upstream.

**Comment by vladikoff** [comment]
:cry:
