### ISSUE TITLE
Exit code 0 returned when ClientSuite session creation error occurs

### ISSUE THREAD

**Issue by csnover** [theintern/intern#401]
When e.g. the ClientSuite just does not run at all due to a session creation failure or some other failure, the executor is not successfully communicating that there was a serious error.

**Comment by jonlong** [comment]
I believe I'm still seeing this error after an update to `3.0.1`.

Here's where `3.0.1` is installed on my CI:
![image](https://cloud.githubusercontent.com/assets/482527/9705544/79f2b3d2-5495-11e5-872d-7242b302a605.png)

And here's where it fails with exit code `0` (I'm still trying to figure out how to make local selenium work with my CI — hence the error):
![image](https://cloud.githubusercontent.com/assets/482527/9705539/573a8ac2-5495-11e5-89fa-725775aedec2.png)
