### ISSUE TITLE
SauceLabs marked test as passed when it failed to load test file

### ISSUE THREAD

**Issue by bartoszkaczorek** [theintern/intern#403]
Hi,

I have came across an issue, where intern failed to load test file for some reason and in the command line output it displayed "Fatal error" and "Failed to load file: ..." (don't remember exact messages) and in the end it was 0/0 tests failed. Sauce labs job was marked as passed in that situation (I'm guessing because it didn't load any tests it assumed none tests failed), but I would expect it to be marked as "error".

Thanks,
Bart

**Comment by csnover** [comment]
Can you please try with Intern 3? When there is a suite error it should not report success.

**Comment by csnover** [comment]
Uh, sorry, Intern 3 is the master branch.

**Comment by bartoszkaczorek** [comment]
I'm using intern 2.2.2 - I'm installing it using npm and it says 2.2.2 is the latest currently, will try with 3 when I get updated.

**Comment by csnover** [comment]
Yeah you will just need to change the dependency temporarily to `theintern/intern#master` to test.

**Comment by csnover** [comment]
Yeah you will just need to change the dependency version temporarily to `theintern/intern#master` to test.

**Comment by csnover** [comment]
Since I haven’t heard anything else in a few weeks I will assume this is working properly. Please comment again if this is not working right in Intern 3.
