### ISSUE TITLE
provide a way to stop intern server via URL

### ISSUE THREAD

**Issue by bartoszkaczorek** [theintern/intern#404]
Hi,

Could you provide a way to stop intern server via URL? I.e. by invoking request "localhost:4444/stop" - I would find it very useful. Few times I have came across situation where intern tests failed due to some fatal error, but intern server was not stopped (I'm guessing because of that error) - I couldn't find a way to stop it other than killing process, and it would be nice to have a possibility to stop it in a more graceful way. It would be useful for task automation as well.

Thanks,
Bart

**Comment by csnover** [comment]
Killing the process with SIGINT is the most graceful and correct way to stop a test run. If the proxy were going to be designed to allow a kill (and the proxy runs on 9000 by default, 4444 is the WebDriver server which Intern has no control over), it would probably just send a SIGINT internally anyway. So I’m not super sure what this provides except for an HTTP-based way to kill an Intern server.

Are any other people interested in this?

**Comment by csnover** [comment]
Seems that there is no interest in this so I am going to close this ticket for now. We can always reopen in the future if it turns out there is a lot of interest in such a feature.
