### ISSUE TITLE
Intern 3: closing tunnel with ^C marks the first test as passed

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#406]
![](http://v14d.com/i/5572105337635.png)

Noticed this in 2 projects. I started my tests and then shut down the tunnel very quickly. That marked one of the first tests as passing. I can create a quick demo if hard to reproduce or track this bug.

**Comment by jason0x43** [comment]
I haven't seen this myself, at least not with current versions of Intern. I'm closing this for now, but feel free to reopen if this is still an issue.
