### ISSUE TITLE
QUnit interface: config.urlConfig implementation

### ISSUE THREAD

**Issue by apsdehal** [theintern/intern#412]
We need an implementation of QUnit.config.urlConfig in QUnit interface, so as move one step forward to QUnit interface completion.

This is not necessary as of now and is needed only in the case tests are run from browser.

**Comment by csnover** [comment]
The UI is separated from the rest of the test system so I don’t know how this is possible or appropriate in the Intern architecture, can you please provide some use cases that make sense in the context of the way Intern runs?

**Comment by arschmitz** [comment]
I don't think we actually need this. All I think we really need as far as configuration via the url is to be able to set the jQuery version we are testing against.

**Comment by csnover** [comment]
OK, I will close this for now, please let me know if it turns out to be necessary later. You should be able to use [custom arguments](https://theintern.github.io/intern/#custom-args) to specify the version by URL.
