### ISSUE TITLE
Feature request: Fail-fast option

### ISSUE THREAD

**Issue by sholladay** [theintern/intern#413]
### Problem
For users of Continuous Integration / Delivery systems, the excess testing and build time caused by multiple test failures can be very undesirable, such as for a shared dev branch where speed is important and time-to-deploy is compounded and queued many times over. It can also consume precious resources from per-hour test clouds like BrowserStack and SauceLabs.

### Solution
Provide an opt-in configuration option to halt at the first test failure. A relevant reference is the [fail_fast](https://www.relishapp.com/rspec/rspec-core/v/2-0/docs/configuration/fail-fast) option for RSpec or Mocha's `--bail`.

### Suggested requirements
 - When a test fails, all further tests and suites are aborted.
 - Any tests not run due to a test failure are counted as skipped.
 - When tests are skipped due to a test failure, a warning is logged to explain them.
 - This option is off by default, to avoid confusion.

Stretch goal: make it configurable so that it can be told to only abort the rest of the current suite or only the rest of the unit tests, but not functional tests, etc.

**Comment by vladikoff** [comment]
Good suggestion, I do agree that this is gonna useful for CI, especially if you retry tests with something like `travis_retry`.


<img src="http://static.comicvine.com/uploads/scale_super/5/52246/2060390-i_like_it.jpg" width=150 />

**Comment by sholladay** [comment]
It can be even better. If Intern natively [supports retries](https://github.com/theintern/intern/issues/340), it doesn't have to repeat the entire lot of suites or even restart the process. In my ideal setup, CI would probably retry a test once or twice before considering it truly failed and once that had been decided, would not continue. So combining these is indeed powerful, especially if it's handled within Intern itself.

**Comment by vladikoff** [comment]
@csnover in https://github.com/theintern/intern/issues/368#issuecomment-88585145 you mentioned that in Intern 3 it should be possible to pause flow, what this help this issue?

**Comment by csnover** [comment]
Yes it will help, it should be much easier to bail out of running any more tests now

**Comment by vladikoff** [comment]
any pointers on how to do that? I think @miketaylr wanted to hook that up

**Comment by csnover** [comment]
In `lib/Suite.js`, if a test fails and fast fail is turned on then don’t run any more tests. This changed code also needs to account for sub-suites: a parent suite should not continue to run either if a child suite failed. That’s pretty much it.

**Comment by airtonix** [comment]
Any way I can enable fail fast but not have my terminal spammed with all the skipped tests?

**Comment by jason0x43** [comment]
That's the spirit!

That's a good idea -- having an option to hide skipped tests would actually be pretty handy.
