### ISSUE TITLE
loaderConfig issues in Intern 3.

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#418]
In master on [selftest.intern.js](https://github.com/theintern/intern/blob/master/tests/selftest.intern.js#L20) the loader is configured via `loader`, but in [example.intern.js](https://github.com/theintern/intern/blob/master/tests/example.intern.js#L39) the attribute name is `loaderConfig`.  The documentation states that it is now `loaderConfig` in 3.0 but it seems only `loader` is detected in master and 3.0.0-rc.1.

**Comment by csnover** [comment]
The documentation should say `loaderOptions`.

**Comment by kitsonk** [comment]
@csnover I went and looked again, it does say `loaderOptions`, it is [example.intern.js](https://github.com/theintern/intern/blob/master/tests/example.intern.js#L39) that says `loaderConfig` which doesn't work.  `loaderOptions` works fine.
