### ISSUE TITLE
Platform part of the "tests failed" report is missing how many tests were skipped

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#421]
Description: Platform part of the "tests failed" report is missing how many tests were skipped

### Steps to reproduce: Platform "tests failed" report is missing how many tests were skipped

1. run some tests with the `grep` option, I used `npm run test-functional grep="sync reset password, verify same browswer"` 
2. Got output: 
```
> fxa-content-server@0.39.0 test-functional /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> intern-runner config=tests/intern_functional "grep=sync reset password, verify same browswer"

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (cf6916d0-9e34-47f6-b3cf-85688b7abb77)
Waiting for email at: http://127.0.0.1:9001/mail/signin0.31952479644678533
Waiting for email at: http://127.0.0.1:9001/mail/signin0.2677939438726753
Waiting for email at: http://127.0.0.1:9001/mail/signin0.4526257694233209
Waiting for email at: http://127.0.0.1:9001/mail/signin0.8374885404482484
✓ firefox on any platform - Firefox Desktop Sync reset password - sync reset password, verify same browswer (4.933s)
No unit test coverage for firefox on any platform
firefox on any platform: 0/264 tests failed


TOTAL: tested 1 platforms, 0/264 tests failed (263 skipped)
```

### Expected result:
The reporter before the `TOTAL` should include skipped tests or just say how many tests ran:
`firefox on any platform: 0/1 tests failed` or  `firefox on any platform: 0/264 tests failed (263 skipped)`
### Actual result:
Says `firefox on any platform: 0/264 tests failed` and does not include skipped tests.

Intern version: Intern 3 at Git Hash : 42aebd9beb942a11e2c6e6d7687c70a1c22b9bf7

Any additional information: None

**Comment by csnover** [comment]
Please feel free to submit a pull request to add the missing information!

**Comment by sholladay** [comment]
I will chip in to fix this within the next day or so. The offending code is [line 167](https://github.com/theintern/intern/blob/master/lib/reporters/Runner.js#L167) in `lib/reporters/Runner.js`
