### ISSUE TITLE
google fonts coming in 404 in client.html

### ISSUE THREAD

**Issue by httpete** [theintern/intern#424]
Description:

We have a secure environment, and I can't load ANY external resources. Can we disable somehow or maybe bundle in the google fonts to make client.html look so pretty? It really slows down the client.html test page, since it waits for the google font to 404.

Intern version: 3.0 RC1

Any additional information:

**Comment by csnover** [comment]
We’ve discussed this internally and won’t be adding font bundling since the edge case nature of this problem doesn’t really justify the extra space that these fonts would take for *every* Intern user. You could write and use a [custom](https://theintern.github.io/intern/#custom-reporters) version of the HTML reporter that includes the fonts if this is a significant problem for your organisation.

**Comment by httpete** [comment]
Then don't add the font from google at all please, it's not worth it. Secure environments are the new norm - people will not be able to import things from the interwebs. It makes the whole test client.html hang..

**Comment by httpete** [comment]
@csnover @dylans if there is any way I could gently bump on this - it is going to make adoption harder in my org. The html browser reporter is so nice, and just because we are adding fonts from google I have to jump through hoops. It looks sweet without the fonts, it is so subtle.

**Comment by dylans** [comment]
I created a fairly simple PR for this. See my notes and question. I agree that this makes Intern simpler for people to use inside the firewall for testing.

**Comment by httpete** [comment]
Thank you. This is a good heads up - we are now in a COMPLETE secure VED virtual dev env. I think this will happen to more organizations - the hacking out there is EPIC and is getting worse. We are now in a locked - no interwebs access environment. Makes life wicked hard.

**Comment by dylans** [comment]
It's been reported that this causes an issue when trying to run tests on a simulated slow connection to more accurately reflect mobile testing on a slow network.

**Comment by httpete** [comment]
The sizzle of the font isn't worth this IMHO

**Comment by httpete** [comment]
I am preparing to showcase this, and I have to wait till this times out until I can show the sexy ui inside my protected corporate environment :-(

**Comment by jason0x43** [comment]
The google fonts were removed in 0fb9352b.
