### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by marklague** [theintern/intern#429]
I tried installing intern both locally and globally and I've been getting this error 

>C:\Users\mlague\Documents\NetBeansProjects>npm install intern
>npm WARN excluding symbolic link query -> vendors/jquery/src/
>npm WARN excluding symbolic link query -> vendors/jquery/src/
>
>intern@2.2.2 install C:\Users\mlague\Documents\NetBeansProjects\node_modules\intern
>node support/fixdeps.js
>
>fs.js:717
>  return binding.symlink(preprocessSymlinkDestination(destination, type),
>                 ^
>Error: EPERM, operation not permitted 'c:\Users\mlague\Documents\NetBeansProjects\node_modules\intern\node_modules\dojo'
>    at Object.fs.symlinkSync (fs.js:717:18)
>    at C:\Users\mlague\Documents\NetBeansProjects\node_modules\intern\support\fixdeps.js:33:6
>    at Array.forEach (native)
>    at Object.<anonymous> >(C:\Users\mlague\Documents\NetBeansProjects\node_modules\intern\support\fixdeps.js:14:28)
>    at Module._compile (module.js:456:26)
>    at Object.Module._extensions..js (module.js:474:10)
>   at Module.load (module.js:356:32)
>    at Function.Module._load (module.js:312:12)
>    at Function.Module.runMain (module.js:497:10)
>    at startup (node.js:119:16)
>npm ERR! Windows_NT 6.1.7601
>npm ERR! argv "C:\\webApps\\nodeJS\\\\node.exe" "C:\\webApps\\nodeJS\\node_modules\\npm\\bin\\npm-cli.js" "install" "intern"
>npm ERR! node v0.11.0
>npm ERR! npm  v2.11.1
>npm ERR! code ELIFECYCLE
>
>npm ERR! intern@2.2.2 install: `node support/fixdeps.js`
>npm ERR! Exit status 8
>npm ERR!
>npm ERR! Failed at the intern@2.2.2 install script 'node support/fixdeps.js'.
>npm ERR! This is most likely a problem with the intern package,
>npm ERR! not with npm itself.
>npm ERR! Tell the author that this fails on your system:
>npm ERR!     node support/fixdeps.js
>npm ERR! You can get their info via:
>npm ERR!     npm owner ls intern
>npm ERR! There is likely additional logging output above.
>
>npm ERR! Please include the following file with any support request:
>npm ERR!     C:\Users\mlague\Documents\NetBeansProjects\npm-debug.log

**Comment by csnover** [comment]
Could you please try again running a stable and recent version of Node.js? Node 0.12.5 is the latest version, you are running 0.11.0 according to that log, which is over two years old and an unstable version.

**Comment by sholladay** [comment]
`EPERM` means your permissions are not good enough to make that symlink. Most likely, some part of the path doesn't have write permissions, which are necessary for this to work. Ideally, `fixdeps.js` would validate the symlink is able to be created before attempting it and throwing a more friendly error if not. But still, it's probably an issue with your environment.

If you look and the permissions appear okay, it might be due to account ownership of the directory, etc.

**Comment by sholladay** [comment]
There are also [known bugs](http://stackoverflow.com/questions/26269462/how-do-i-correct-intern-npm-install-failure-in-fixdeps-js) with path resolution in Node 0.11.x, so the suggestion to upgrade is not for nothing. ;)

**Comment by marklague** [comment]
I updated node to v0.12.5 and re-run the install successfully.

Now, I remember that I downgraded the node version because of a conflict while installing Karma. I completely forgot about that.

Thanks to all.
