### ISSUE TITLE
SauceLabsTunnel tries to connect locally

### ISSUE THREAD

**Issue by CRogers** [theintern/intern#432]
I'm trying to use the SauceLabsTunnel. My [intern-ete-remote.js](https://github.com/CRogers/gates/blob/7c264470b4db21bcb9dab81ef196f19a6441cc13/intern-config/intern-ete-remote.js) looks like this:

```javascript
define({
  environments: [
    { browserName: 'chrome' },
    { browserName: 'firefox' }
  ],

  tunnel: 'SauceLabsTunnel',
  tunnelOptions: {
    username: 'crogers-gates',
    accessKey: '93ff0070-1fd7-4f8c-9fad-a6e8ed200696'
  },

  functionalSuites: [ 'build/tests/functional/test' ],

  reporters: [ 'console' ],

  excludeInstrumentation: /./
});
```

But when I try running

```bash
./node_modules/.bin/intern-runner config=intern-config/intern-ete-remote.js
```

I get this error:

```
FATAL ERROR
Error: [POST http://(redacted)@localhost:4444/wd/hub/session] connect ECONNREFUSED
Error: connect ECONNREFUSED
  at exports._errnoException  <util.js:746:11>
  at TCPConnectWrap.afterConnect [as oncomplete]  <net.js:1000:19>
FATAL ERROR
Error: [POST http://(redacted)@localhost:4444/wd/hub/session] connect ECONNREFUSED
Error: connect ECONNREFUSED
  at exports._errnoException  <util.js:746:11>
  at TCPConnectWrap.afterConnect [as oncomplete]  <net.js:1000:19>
```

It looks like intern is trying to connect locally, even though I've specified a tunnel to use. Any idea what's going on?

*The example repo I'm using is [here](https://github.com/CRogers/gates/tree/7c264470b4db21bcb9dab81ef196f19a6441cc13) and you can try it out by doing `npm install --save-dev && ./gulp ete-remote`*

**Comment by CRogers** [comment]
(I'm using intern 2.2.2)

**Comment by CRogers** [comment]
I tried this on 3.0.0-rc.2 and it worked. It is very borked though and 2.2.2.

**Comment by jason0x43** [comment]
If you're using Node.js 0.12, there is a bug in the version of [Dig Dug](https://github.com/theintern/digdug)  used by Intern 2.2.2 that can allow Intern to try to access the SauceLabs tunnel before it is fully established. Intern 3 uses a more recent version of Dig Dug.

Note that the Sauce Labs Connect system works by running a server at localhost:4444 for clients to communicate with Sauce Labs through. Intern connects to this local server, so seeing that address pop up in status messages isn't anything to worry about.

**Comment by vasikarla** [comment]
CRogers : As a security precaution try to mask the user name and api key from the code snippet.

**Comment by csnover** [comment]
This is a known issue that is already fixed in Intern 3.
