### ISSUE TITLE
Bundling chromedriver

### ISSUE THREAD

**Issue by tmcw** [theintern/intern#437]
Would it be possible to [bundle the npm binary wrapper of chromedriver](https://www.npmjs.com/package/chromedriver) to make it easier to use chrome as a testbed?

**Comment by kitsonk** [comment]
I suspect this is better left as a dev dependency of the containing project.  Adding the package, along with Intern, is trivial.  Hard bundling the dependency means that Intern will assume all users will require Chrome and ChromeDriver to do testing, an assumption/assertion that is probably not good to make.  Also, there are many use cases where local Web Driver testing is never used and again.  In addition there would be the need to try to keep up with version updates of a package that is not actually required to make Intern work.

Why is `npm install intern chromedriver --save` less easy?

**Comment by vladikoff** [comment]
-1 on this, we do not run tests in Chrome and do not the driver installed all the time.

If you need things auto installed see https://www.npmjs.com/package/selenium-standalone

**Comment by csnover** [comment]
This is exactly what the [Dig Dug](https://github.com/theintern/digdug) library is for. Create a new Dig Dug tunnel that downloads and runs ChromeDriver, then every user can also have access to ChromeDriver simply by specifying tunnel: 'ChromeDriver' or whatever. The code for downloading and spawning is already there so this would be a very trivial enhancement to that library.

**Comment by csnover** [comment]
Please see https://github.com/theintern/digdug/issues/19
