### ISSUE TITLE
Bug on Doc Site - CORS item not readable. Chrome

### ISSUE THREAD

**Issue by httpete** [theintern/intern#439]
![bug](https://cloud.githubusercontent.com/assets/1200635/8664408/e5d13af4-29a4-11e5-8c50-66aa11a2f272.png)

**Comment by jason0x43** [comment]
It seems like this may be tied to the max-height CSS transition. I've been able to reproduce this sporadically in IE and Chrome, but only in a VM and only at 125% zoom. Turning off the animation *seems* to resolve the issue.

**Comment by jason0x43** [comment]
The doc site has been overhauled, so this is no longer an issue.
