### ISSUE TITLE
chai!expect typings expect a string

### ISSUE THREAD

**Issue by devpaul** [theintern/intern#443]
I am using Intern 3.0.0-rc3 and am trying to use expect to make a numeric assertion:

```
    import expect = require('intern/chai!expect');
    expect(result.length).to.equal(1);  // result is an array
```

While building I get the error:

```
    error TS2345: Argument of type 'number' is not assignable to parameter of type 'string'.
```

I followed this through and found `intern.d.ts` types `chai!expect` as `chai.Expect` from `chai.d.ts`:

```
    declare module 'intern/chai!expect' {
	var expect: chai.Expect;
	export = expect;
    }
```

in `chai.d.ts` expect is defined as:

```
    interface Expect extends LanguageChains, NumericComparison, TypeComparison, Assertions
```

The only one of those extended interfaces that defines a method type is `TypeComparison`:

```
    interface TypeComparison {
        (type: string, message?: string): Expect;
        instanceof: InstanceOf;
        instanceOf: InstanceOf;
    }
```

But it should probably define the `type` as `any` instead of `string`. I made this change locally and I was able to compile.

There are also a couple typings floating around in `chai.d.ts` that may also be relevant, but I'm not sure how they're intended to be used and it's getting late:

```
    export function expect(target: any, message?: string): Expect;
```

```
    interface ExpectStatic {
        (target: any): Expect;
    }
```

**Comment by kitsonk** [comment]
The typings come from [borisyankov/DefinitelyTyped](https://github.com/borisyankov/DefinitelyTyped) and I can see that the current [typings for chai](https://github.com/borisyankov/DefinitelyTyped/blob/master/chai/chai.d.ts#L123) reflect what is contained in Intern.  I suspect there will need to be a PR on DefinitelyTyped to fix it.

Of course temporarily you could work around it by casting to ExpectStatic.

**Comment by devpaul** [comment]
Now that I've had a chance to look at it fresh, I think Intern's declaration of `intern/chai!expect` is actually wrong. It says it's typed as Expect, but that would suggest you could use assertions directly off expect like `expect.equals(1)` which doesn't make sense and isn't reflected by chai (https://github.com/chaijs/chai/blob/master/lib/chai/interface/expect.js#L8-L10)

It looks like if we updated to the current typings [we could use ExpectStatic](https://github.com/borisyankov/DefinitelyTyped/blob/master/chai/chai.d.ts#L21-L22) in the `intern/chai!expected` declaration.
