### ISSUE TITLE
Update Istanbul to 0.3.17+

### ISSUE THREAD

**Issue by csnover** [theintern/intern#445]
From @siboulet:

> Latest version of Istanbul (0.3.17) has an updated esprima dependency which apparently has better support for ES6. Any chances we can get an Istanbul version bump to 0.3.17 for Intern 3.x? gotwarlost/istanbul#66

**Comment by benlangfeld** [comment]
Is there any chance this could be backported to Intern 2.x? 3.x hangs when run against Selenium (try bumping https://github.com/theintern/intern-examples/blob/master/phantomjs-example/package.json#L8 and this becomes very clear; separate issue coming up soon for that) and I need this change for ES6 compat in Candy.

**Comment by benlangfeld** [comment]
Demonstration of the breakage with Intern 3.0.0 is at https://github.com/theintern/intern-examples/pull/25.

**Comment by csnover** [comment]
Sorry, no more updates to Intern 2.x are planned. If you are having trouble with Intern 3, please open some tickets so those bugs can be fixed. Thanks!
