### ISSUE TITLE
WebDriver constructor options will always throw if empty

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#452]
I noticed in the [WebDriver](https://github.com/theintern/intern/blob/c3ead65e576aad4bc3fa7ea7f292493232ca071e/lib/reporters/WebDriver.js#L20) reporter that it has a logic error in the constructor.

```javascript
	function WebDriver(config) {
		config = config || {};

		this.sequence = 0;
		this.url = require.toUrl('intern/');
		this.publishHandle;
		this.writeHtml = config.writeHtml !== false;
		this.sessionId = config.internConfig.sessionId;
		this.waitForRunner = config.waitForRunner;

		if (this.writeHtml) {
			this.reporterNode = document.createElement('div');
			document.body.appendChild(this.reporterNode);
			this.suiteNode = this.reporterNode;
		}

		if (this.waitForRunner) {
			this.enqueue = util.createQueue(4);
		}
	}
```

When the constructor is not called with an argument, the config is initialised with a empty object (`config = config || {}`) but then when attempting then `this.sessionId = config.internConfig.sessionId;` but of course `internConfig` will never be a property, and therefore this line will always throw.  I wasn't sure of the intent, so I haven't addressed it in the the PR for #435.

**Comment by csnover** [comment]
I’m OK with this the way it is, it will start crashing if `internConfig` goes away which is good since that would indicate a refactor took place that needed to fix up this code.
