### ISSUE TITLE
Progress for downloading the tunnel - issue with CR/LF

### ISSUE THREAD

**Issue by dandv** [theintern/intern#454]
On windows, when Intern installs the tunnel, every progress line ends with a LF (at least in [ConEmu](http://conemu.github.io/)):

![image](https://cloud.githubusercontent.com/assets/33569/9052001/bddd3b10-3a16-11e5-98cc-b05fa6bdc9aa.png)

On Ubuntu, this isn't a problem, but `BrowserStackLocal v3.7` does get overwritten:

![image](https://cloud.githubusercontent.com/assets/33569/9052012/e42cac4c-3a16-11e5-8ab8-571b5e77a532.png)

**Comment by csnover** [comment]
Progress lines are terminated with a CR, not an LF. This character returns the cursor to the start of the line without advancing a line. I’m not aware of any system that doesn’t support this (and I know for a fact that Windows does). Could you please try from cmd.exe directly?

**Comment by dandv** [comment]
Sure. Unfortunately the problem persists:

![crlf](https://cloud.githubusercontent.com/assets/33569/9053282/e499995e-3a27-11e5-96c7-1ea05378d8d5.gif)

**Comment by csnover** [comment]
Guess someone’s going to be booting into Windows tomorrow… :disappointed:

**Comment by kitsonk** [comment]
I have seen it before myself on OSX as well. :sob: I will try to reproduce.

**Comment by csnover** [comment]
I’m able to reproduce the issue on Windows. It seems likely that this is a Node.js bug. I can use `type` on the command-line to type a file with `\r` and it correctly overwrites the line but if I have Node.js output the exact same data with `process.stdout.write(require('fs').readFileSync('testfile'))` it seems to morph the line endings into `\r\n`. Continuing to investigate.

**Comment by csnover** [comment]
So, this is apparently thanks to [meddling from libuv](https://github.com/libuv/libuv/blob/v1.x/src/win/tty.c#L1883-L1900). To work around, we would need to create our own raw writable stream on fd 1 and send that to reporters instead… unfortunately doing this would break any reporters that actually need some of the *other* terminal emulation functionality from libuv. :\

**Comment by csnover** [comment]
I submitted a patch upstream to libuv and put a hacky workaround into ReporterManager that appears to correct the problem. Please try running with `theintern/intern#3.0` and verify that everything is working as expected.
