### ISSUE TITLE
test "teardown" runs out of sync with grepped tests 

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#458]
Each suite before the "grepped" suite runs its teardown while the "grepped" suite is running.

### STR
 
1. ` java -jar selenium-server-standalone-2.46.0.jar` AKA start selenium

2. `git clone https://github.com/vladikoff/fxa-content-server.git` + `cd fxa-content-server `

3. `git checkout  teardown-armageddon`

4. 
```npm install intern bower zaach/node-XMLHttpRequest.git#onerror firefox-profile@0.3.3 request@2.40.0 sync-exec@0.5.0 convict@0.8.0```

5. `bower install`

6. `npm run test grep="Firefox Desktop Sync sign_in"`

### Actual

```
➜  fxa-content-server git:(teardown-armageddon) ✗ npm run test grep="Firefox Desktop Sync sign_in"

> fxa-content-server@0.42.0 test /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> intern-runner config=tests/intern "grep=Firefox Desktop Sync sign_in"

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (2b108f9b-8afd-4fa9-b8dd-a14c0863a784)
teardown: sign_in.js
teardown: sign_in_cached.js
✓ firefox on any platform - Firefox Desktop Sync sign_in - sign in verified (2.201s)
✓ firefox on any platform - Firefox Desktop Sync sign_in - unverified (2.277s)
✓ firefox on any platform - Firefox Desktop Sync sign_in - as a migrating user (1s)
teardown: sync_sign_in.js
teardown: sign_up.js
teardown: sync_sign_up.js
im running tests in sync_settings.js, please leave me alone :(
✓ firefox on any platform - Firefox Desktop Sync sign_in - sign in, change the password (1.671s)
im running tests in sync_settings.js, please leave me alone :(
✓ firefox on any platform - Firefox Desktop Sync sign_in - sign in, delete the account (1.92s)
No unit test coverage for firefox on any platform
firefox on any platform: 0/278 tests failed
```

### Expected
```
➜  fxa-content-server git:(teardown-armageddon) ✗ npm run test grep="Firefox Desktop Sync sign_in"

> fxa-content-server@0.42.0 test /Users/vladikoff/mozilla/fxa-local-dev/fxa-content-server
> intern-runner config=tests/intern "grep=Firefox Desktop Sync sign_in"

Creating Firefox profile...
Listening on 0.0.0.0:9090
Tunnel started
‣ Created session firefox on any platform (2b108f9b-8afd-4fa9-b8dd-a14c0863a784)
✓ firefox on any platform - Firefox Desktop Sync sign_in - sign in verified (2.201s)
✓ firefox on any platform - Firefox Desktop Sync sign_in - unverified (2.277s)
✓ firefox on any platform - Firefox Desktop Sync sign_in - as a migrating user (1s)
im running tests in sync_settings.js, please leave me alone :(
✓ firefox on any platform - Firefox Desktop Sync sign_in - sign in, change the password (1.671s)
im running tests in sync_settings.js, please leave me alone :(
✓ firefox on any platform - Firefox Desktop Sync sign_in - sign in, delete the account (1.92s)
No unit test coverage for firefox on any platform
firefox on any platform: 0/278 tests failed
```
(teardown should not be running and clearing my cache or doing other things)

## Version of intern 3.0.0

**Comment by vladikoff** [comment]
Branch link: https://github.com/vladikoff/fxa-content-server/commit/573e231efd6071a394749a6751897615719e99db

**Comment by vladikoff** [comment]
There seems to be the same issue with "setup", but not "beforeEach"

**Comment by vladikoff** [comment]
@csnover I added an easier STR:

```
git clone https://github.com/vladikoff/intern-quick-test.git -b teardown
cd intern-quick-test
npm i 
npm test grep="suite2"
```

you can see that teardown of suite1 will be called https://github.com/vladikoff/intern-quick-test/commit/dfe892e43cb41f542fb628f0778842519ee34581#diff-9ef56bfba62c04cd5f2daa7c9b0b24fbR17

**Comment by csnover** [comment]
Following the reproduction instructions I end up with a browser trying and failing to load http://127.0.0.1:3030/clear

**Comment by csnover** [comment]
@vladikoff Could you please provide a test case that I can run, or better instructions on how to use the original test case successfully? As discussed in IRC the reduced case at https://github.com/theintern/intern/issues/458#issuecomment-128130141 isn’t valid because it’s just showing that setup/teardown do run for all suites because they may have subsuites that match the grep. (If you’d like, open a separate ticket for the change to the `grep` algorithm to suppress those extra calls and I will make that change.)

**Comment by vladikoff** [comment]
> (If you’d like, open a separate ticket for the change to the grep algorithm to suppress those extra calls and I will make that change.)

Yeah let's do that, I will reopen this one once I have an easy way of reproducing the issue. 

Thanks!
