### ISSUE TITLE
License for theintern.github.io?

### ISSUE THREAD

**Issue by geekdave** [theintern/intern#462]
Didn't see a license in the website repo: https://github.com/theintern/theintern.github.io

Is it MIT/BSD?  Would love to leverage some of the work there (specifically the comparison chart) for some other open source projects, if you're open to it!

Thanks!

EDIT: Apologies for submitting this in a _different_ repo, but the repo in question does not accept issues and I thought it would be presumptuous to submit a PR for a license of my choosing :)

**Comment by csnover** [comment]
The Web site is currently rights reserved. Could you maybe provide more information about what you are trying to do? Depending upon what you are doing you may be able to just do it, or I imagine we can come up with something.

**Comment by csnover** [comment]
I’m going to close this ticket just so it is not active on the list of things since it isn’t a bug/enhancement request for Intern, but I still await more details.

**Comment by geekdave** [comment]
Just really liked your comparison chart and was interested in borrowing the
styling to use on our own site. So many times in open source it's difficult
to articulate the commonalities and differences between two similar
projects so stuff like this really helps!
