### ISSUE TITLE
Option for not use color output

### ISSUE THREAD

**Issue by muzuiget** [theintern/intern#473]
I have read the commit https://github.com/theintern/intern/commit/746f147e7d375ed4a15a6f623fd9643cdea5f982 and the issues in it's commit message.

The testing report output may not print on terminal, it maybe save to data or pass to other viewer, for example, use Ansible call intern.

Istanbul use [suppport-color](https://www.npmjs.com/package/supports-color), and it can use `FORCE_COLOR` environment variable. And there are also a review comment point this out in #423, no idea why this ignored.

**Comment by csnover** [comment]
Sorry, I don’t understand this request. If you don’t want colour output, don’t set FORCE_COLOR and use a reporter that doesn’t generate such output, or strip the ANSI codes by piping output through `sed -e 's/\x1b\[[;0-9]*[a-zA-Z]//g'` or similar.

If you can be clearer about what it is that you care about and it is something that we can reasonably implement I will be happy to reopen this ticket.
