### ISSUE TITLE
Support running on multiple browsers simultaniously

### ISSUE THREAD

**Issue by saulshanabrook** [theintern/intern#474]
Does intern having multiple browsers in a single test? For example, if I wanted to test my chat app to make sure that if I entered a message in one browser that it appeared on another connected browser.

Webdriverio calls this feature [multiremote](http://webdriver.io/guide/usage/multiremote.html).

**Comment by csnover** [comment]
The shortest answer is no, it doesn’t. However, there is nothing special that would stop you from starting a second session and managing that relationship yourself.

In any case, I am really not sure of how useful this actually is; given how seriously limited browser instances are on cloud providers, you’re almost certainly better off testing just client-to-server interactions anyway. This seems like more of a gimmick feature that appears cool on the surface but actually just introduces additional points of failure into testing for no benefit.
