### ISSUE TITLE
'Run failed due to one or more suite errors' error is not helpful

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#475]
### STR
```
git clone https://github.com/vladikoff/intern-quick-test.git -b unk-error
cd intern-quick-test 
npm i
npm test
```
### Actual
```
➜  intern-quick-test git:(master) ✗ npm test

> intern-quick-test@1.0.0 test /Users/vladikoff/dev/intern-quick-test
> intern-runner config=intern.js

Error: Run failed due to one or more suite errors
  at emitLocalCoverage  <node_modules/intern/lib/executors/Executor.js:338:18>
  at finishSuite  <node_modules/intern/lib/executors/Executor.js:355:15>
  at <node_modules/intern/lib/executors/Executor.js:362:7>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:354:15>
npm ERR! Test failed.  See above for more details.
```

### Expected

`due to one or more suite errors` should have a pointer of what went wrong.

### Code

This is just throwing the error below:

```javascript
function emitLocalCoverage() {
					var error = new Error('Run failed due to one or more suite errors');

					var coverageData = (function () { return this; })()[self.config.coverageVariable];
					if (coverageData) {
						return self.reporterManager.emit('coverage', null, coverageData).then(function () {
							if (hasError) {
								throw error;
							}
						});
					}
					else if (hasError) {
						return Promise.reject(error);
					}
				}
```

**Comment by csnover** [comment]
That error says that because it’s expected that the actual problem is expected to have been already reported by a reporter. In any case I can’t reproduce any issue with the test case you provided in latest 3.0 branch so please confirm this is still a problem?

**Comment by csnover** [comment]
Closing due to no response. If you are able to provide the requested information and this is still a problem I will reopen the ticket. Thanks!

**Comment by LingSpb** [comment]
I face the quite same problem. The test just stopped after running several testcases, sometimes after 100, sometimes 200 or 300.
I use intern 3.0.5 + Windows Server 2012R2 + Chrome, Firefox (maxConcurrency = 1)
Error message as following
>[16:20:59]Error: One or more suite errors occurred during testing
>[16:20:59]  at <..\node_modules\intern\lib\executors\Executor.js:301:13>
>[16:20:59]  at <..\node_modules\intern\node_modules\dojo\Promise.ts:393:15>
>[16:20:59]  at runCallbacks  <..\node_modules\intern\node_modules\dojo\Promise.ts:11:11>
>[16:20:59]  at <..\node_modules\intern\node_modules\dojo\Promise.ts:317:4>
>[16:20:59]  at run  <..\node_modules\intern\node_modules\dojo\Promise.ts:237:7>
>[16:20:59]  at <..\node_modules\intern\node_modules\dojo\nextTick.ts:44:3>
>[16:20:59]  at process._tickCallback  <node.js:355:11>

Sometimes:
>[14:50:28]Error: Run failed due to one or more suite errors
>[14:50:28]  at emitLocalCoverage  <..\node_modules\intern\lib\executors\Executor.js:351:18>
>[14:50:28]  at finishSuite  <..\node_modules\intern\lib\executors\Executor.js:368:15>
>[14:50:28]  at <..\node_modules\intern\lib\executors\Executor.js:376:8>
>[14:50:28]  at <..\node_modules\intern\node_modules\dojo\Promise.ts:393:15>
>[14:50:28]  at runCallbacks  <..\node_modules\intern\node_modules\dojo\Promise.ts:11:11>
>[14:50:28]  at <..\node_modules\intern\node_modules\dojo\Promise.ts:317:4>
>[14:50:28]  at run  <..\node_modules\intern\node_modules\dojo\Promise.ts:237:7>
>[14:50:28]  at <..\node_modules\intern\node_modules\dojo\nextTick.ts:44:3>
>[14:50:28]  at process._tickCallback  <node.js:355:11>

**Comment by csnover** [comment]
As I mentioned earlier, any suite error should be reported by one of your reporters, so if you don’t see any other error, please provide your reporters configuration.

**Comment by LingSpb** [comment]
Sorry for the late reply. For the error, I use TeamCity reporter.
