### ISSUE TITLE
Intern loader fails when loading thousands of test modules

### ISSUE THREAD

**Issue by bartoszkaczorek** [theintern/intern#478]
### Overview

Intern runner crashes when running more than 6000 test files on chrome. I was able to run it fine with 5000 test files, but it crashed when trying to run 6000 test files. It displayed error saying _Failed to load module test/unit/example05650Tests from /test/unit/example05650Tests.js_ - I checked the file and it exist on disk. 

### Console output

【 code console 】
Listening on 0.0.0.0:9000
Tunnel started
? Created session chrome on WINDOWS (ee0f727d-d790-4379-8ce5-bd5a68ae0c34)
Suite chrome on WINDOWS - unit tests FAILED
Error: Failed to load module test/unit/example05650Tests from /test/unit/example
05650Tests.js (parent: test/config/.generated/all.js)
 at HTMLScriptElement.handler  <__intern\node_modules\dojo\loader.js:517:27>
No unit test coverage for chrome on WINDOWS
chrome on WINDOWS: 0/0 tests failed

TOTAL: tested 1 platforms, 0/0 tests failed; fatal error occurred
【 end code 】

### Environment details

Intern: 3.0.0
node.js: v0.12.7
Platform: Windows 7
Browser: Chrome 44.0.2403.157

### Steps to reproduce

1. Clone bug repository:

`git clone https://github.com/bugs-intern/bug-intern-loader-fails-when-loading-thousands-of-test-modules.git`
2. Install dependencies:

`cd bug-intern-loader-fails-when-loading-thousands-of-test-modules`

`npm install`
3. Edit file _test/support/options.json_ if you wish to increase test files count
4. Start selenium standalone server on port 4444:

`npm run start-selenium`
5. Run tests:

`npm test`

**Comment by csnover** [comment]
Do you actually have a real world use case where you need to load over 5000 modules or are you just creating synthetic tests until things break?

**Comment by bartoszkaczorek** [comment]
We have around 2000 test modules in one of our projects and that's where we started to see issues with firefox - considering we have that amount of tests we could also hit 5000 at some point as well.

**Comment by jason0x43** [comment]
Closing this since it's Intern 3-specific, and Intern 4's module handling is significantly different.
