### ISSUE TITLE
Safari on Mac ScriptTimeout /output

### ISSUE THREAD

**Issue by galas0330** [theintern/intern#481]
Suite safari 8 on MAC - unit tests FAILED
ScriptTimeout: [POST http://localhost:4444/wd/hub/session/4f800a41-3c8c-484a-b97a-188d1283f21d/execute / {"script":"return (function getCoverageData(coverageVariable) {\n\t\tvar coverageData = (function () { return this; })()[coverageVariable];\n\t\treturn coverageData && JSON.stringify(coverageData);\n\t}).apply(this, arguments);","args":["__internCoverage"]}] Timed out awaiting response to command "executeScript" after 30000 ms (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 30.00 seconds
Build info: version: '2.47.1', revision: '411b314', time: '2015-07-30 03:03:16'
System info: host: 'steves-imac.home', ip: '192.168.1.12', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.5', java.version: '1.8.0_60'
Driver info: org.openqa.selenium.safari.SafariDriver
Capabilities [{browserName=safari, takesScreenshot=true, javascriptEnabled=true, version=8.0.8, cssSelectorsEnabled=true, platform=MAC, secureSsl=true}]
Session ID: null
 at ProxiedSession._post  <node_modules/intern/node_modules/leadfoot/Session.js:59:30>
 at ProxiedSession.Session.execute  <node_modules/intern/node_modules/leadfoot/Session.js:583:15>
 at ProxiedSession.lang.mixin.get  <node_modules/intern/lib/ProxiedSession.js:81:17>
 at Command.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:635:19>
 at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
 at run  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
 at <node_modules/intern/node_modules/dojo/nextTick.ts:44:3>
 at process._tickCallback  node.js:355:11
 at Command.target.(anonymous function) [as get]  <node_modules/intern/node_modules/leadfoot/Command.js:610:11>
 at ClientSuite.lang.mixin.run  <node_modules/intern/lib/ClientSuite.js:146:6>
 at runWithCatch  <node_modules/intern/lib/Suite.js:314:21>
 at next  <node_modules/intern/lib/Suite.js:322:18>
 at <node_modules/intern/lib/Suite.js:345:6>
 at new Promise  <node_modules/intern/node_modules/dojo/Promise.ts:411:3>
 at runTests  <node_modules/intern/lib/Suite.js:278:12>
 at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
 at runCallbacks  <node_modules/intern/node_modules/dojo/Promise.ts:11:11>
 at <node_modules/intern/node_modules/dojo/Promise.ts:317:4>

My full error output. The Safari browser opens, does nothing for about 30 seconds, displays this message, then performs the full test as expected (still passing). 

Safari extension 2.45.0
Selenium standalone 2.47.1
Max OS Yosemite 10.10.5   .... That is my info. Hope to hear from you!

**Comment by csnover** [comment]
There is probably not anything that can be done about this in Intern; the SafariDriver extension is unmaintained and is increasingly buggy as Safari gets new versions. You can set `excludeInstrumentation: true` to bypass this specific problem, but this will lose you code coverage everywhere.

**Comment by vladikoff** [comment]
>There is probably not anything that can be done about this in Intern; the SafariDriver extension is unmaintained and is increasingly buggy as Safari gets new versions. You can set excludeInstrumentation: true to bypass this specific problem, but this will lose you code coverage everywhere.

I think I told @galas0330 to try `excludeInstrumentation: true` on IRC and didn't work either, @galas0330 please confirm. 

@csnover could it be possible to `catch` `getCoverageData` in Safari only and report that coverage is not supported. Where coverage in other browsers would still work...

**Comment by galas0330** [comment]
Confirmed, exclude instrumentation produced the same result. Thanks for
your help guys

**Comment by jason0x43** [comment]
Closing this since it sounds like it's been resolved for...a while now.
