### ISSUE TITLE
Running the browser client in Chrome fails when Basic Auth is enabled

### ISSUE THREAD

**Issue by oskargustafsson** [theintern/intern#483]
For some reason the `Authorization: Basic ...` request header isn't present when requesting `node_modules/intern/client.js`, which causes the request to fail with a 401 response

In Firefox everything works as it should

**Comment by csnover** [comment]
How are you running the client? If you aren’t doing anything funny like editing client.html, seems most possible that Chrome has a bug in its handling of the [`crossOrigin` property](https://html.spec.whatwg.org/multipage/infrastructure.html#cors-settings-attribute) and is not sending Authorization header even though the script is loading to the same domain so the CORS flag should not apply. You can check it by commenting out the `node.crossOrigin = 'anonymous'` line in the loader.js and see if it works then.

**Comment by csnover** [comment]
I’m closing this ticket due to no response in two weeks. If you reply with the requested information I will reopen it. Thanks!
