### ISSUE TITLE
Intern hangs when environments array is empty

### ISSUE THREAD

**Issue by herby** [theintern/intern#487]
Also, because of #486 it actually hangs also when environments in config file is empty and environments in gruntfile is one-element.

**Comment by herby** [comment]
Does this also fix the hanging itself (without taking #486 in regard)?

**Comment by herby** [comment]
Reopen, pls.

`intern` still hangs when environment is empty / not specified in both config and gruntfile.

**Comment by csnover** [comment]
Sorry about that. Writing code when you’re sick is a bad idea :)
