### ISSUE TITLE
"Cannot find the Node.js require" since 3.0.1

### ISSUE THREAD

**Issue by stas-vilchik** [theintern/intern#491]
My environment has recently updated to 3.0.1(it's ok with 3.0.0) and I'm started to see the error:

    Error: Cannot find the Node.js require
    @http://localhost:3000/__intern/node_modules/dojo/node.js:14:9
      at execModule  <__intern/node_modules/dojo/loader.js:332:22>
      at checkComplete/<  <__intern/node_modules/dojo/loader.js:374:21>
      at guardCheckComplete  <__intern/node_modules/dojo/loader.js:361:9>
      at checkComplete  <__intern/node_modules/dojo/loader.js:366:9>
      at injectModule/onLoadCallback  <__intern/node_modules/dojo/loader.js:428:17>
      at injectUrl/handler  <__intern/node_modules/dojo/loader.js:514:21>

I run my tests by grunt task and use three reporters: `Runner`, `Lcov`, `LcovHtml`.

So there are two problems:
* the failure itself
* the execution of tests fails silently, so I found the problem accidentally

**Comment by dylans** [comment]
Which version of Node.js? It's possible this was fixed by 3.0.2 ( https://github.com/theintern/intern/releases/tag/3.0.2 ), see #489

**Comment by stas-vilchik** [comment]
Just tried with 3.0.2, it still fails.

Node.js v0.12.2

**Comment by kitsonk** [comment]
Do you have `useLoader` set in your Intern configuration?  If you aren't using another loader, just remove that (assuming you migrated from Intern 2).

**Comment by stas-vilchik** [comment]
@kitsonk no, I don't use `useLoader`. And I've never used Intern 2, I started with 3.0.0.

For the reference, my config is [here](https://github.com/SonarSource/sonarqube/blob/master/server/sonar-web/test/intern.js).

**Comment by csnover** [comment]
`lang.deepMixin` doesn’t work “right” in the case that a target object is an array and a source object is an object. It mixes the object properties onto the array. So what happens here is that the `reporters` argument is `{ id: 'WebDriver' }`, but the config has `reporters: [ { id: 'Runner' }, { id: 'Lcov' }, { id: 'LcovHtml' } ]`. The PreExecutor needs to promote arguments to arrays earlier than it is.

**Comment by csnover** [comment]
Thanks for having public code, that made it easy to find this bug, which has been reported a couple times in comments but never with an actual test case.

**Comment by stsvilik** [comment]
I'm still running into this issue when running a test against local Selenium:
```
Error: Cannot find the Node.js require
  at <__intern/browser_modules/dojo/node.js:14:15>
  at execModule  <__intern/browser_modules/dojo/loader.js:332:62>
  at <__intern/browser_modules/dojo/loader.js:374:21>
  at guardCheckComplete  <__intern/browser_modules/dojo/loader.js:361:9>
  at checkComplete  <__intern/browser_modules/dojo/loader.js:366:32>
  at onLoadCallback  <__intern/browser_modules/dojo/loader.js:428:17>
  at HTMLScriptElement.handler  <__intern/browser_modules/dojo/loader.js:514:65>
```

**Comment by jason0x43** [comment]
Ensure that none of your unit tests are using Node modules (including uses of `dojo-node`).

**Comment by stsvilik** [comment]
@jason0x43 I am using dojo-node which I thought was supported.

**Comment by dylans** [comment]
dojo-node is a module to load CJS/Node.js modules within AMD inside of a Node.js environment. It does not allow you to load Node.js modules to run inside a browser. It is used for either loading modules for command-line tests, or for Intern's server for executing remote tests against a Selenium grid. When you use it in unit tests, you should use the dojo/has module before loading it. 

See https://theintern.github.io/intern/#testing-commonjs-code and an example of dojo/has usage for Node.js at https://github.com/theintern/intern/blob/master/tests/unit/all.js#L15

While dojo/node and dojo/has are well documented at Dojo, we should probably add a brief explanation of this within the guide.

**Comment by jason0x43** [comment]
As @dylans says, dojo-node is supported, but it only works when tests are run in Node.js (not in browsers). Unit tests run in Node.js when you use `intern-client`, and functional tests always run in Node.js.

**Comment by stsvilik** [comment]
In node client everything runs fine, but running intern-remote invokes unit-tests as well, do you suggest commenting them out, or have two config files?

**Comment by jason0x43** [comment]
Use `dojo/has` to automatically filter out suites based on the environment, or use `this.skip`.

```js
suites: [
    'tests/unit/moduleA',
    'intern/dojo/has!host-node?intern/dojo/node!tests/unit/moduleB'
]
```

or

```js
'some test': function () {
    // Use some environment specific test, such as has('host-node') or a check for process
    if (typeof process === 'undefined') {
        this.skip('needs Node.js');
    }
    // test
}
```
