### ISSUE TITLE
click() on a dojo widget doesn't work in Firefox

### ISSUE THREAD

**Issue by LingSpb** [theintern/intern#494]
You can run the simple test script as below. It works well in Chrome and IE, but not in Firefox.
In Firefox, whenever I call `click()`, it actually attempts to click, after that the element is focused but never checked (as expected for the action `click`).
```javascript
bdd.beforeEach(function(){
     //Open dojo demo page
     return this.remote.get("http://demos.dojotoolkit.org/demos/form/demo.html");
});

bdd.it("click on a widget", function(){
    var widget = this.remote.findByCssSelector("[widgetid=\"it\"]");
    //Click on the checkbox "IT"
    return widget.click()
        .getProperty("className")
        .then(function(className){
            expect(className).to.contain("dijitChecked");
        });
});
```

**Comment by csnover** [comment]
Thanks for the report, this is probably upstream bug https://github.com/SeleniumHQ/selenium/issues/813 which should be fixed in Selenium 2.48.0. In the meantime if you click on `[id=it]` instead of `[widgetid=it]`, the click will be correctly registered.
