### ISSUE TITLE
can't use requirejs as loader in Node

### ISSUE THREAD

**Issue by wkeese** [theintern/intern#496]
Specifying `loaders: { "host-node": "requirejs/require.js" }` doesn't work.  It gives a cryptic error message that:

```
$ node ./node_modules/.bin/intern-runner config=tests/intern.local.js
TypeError: Cannot read property 'config' of undefined
  at <node_modules/intern/lib/executors/PreExecutor.js:497:27>
  at <node_modules/intern/node_modules/dojo/Promise.ts:393:15>
  at Object.run [as _onImmediate]  <node_modules/intern/node_modules/dojo/Promise.ts:237:7>
  at processImmediate [as _immediateCallback]  <timers.js:330:15>
```

The problem is centered around these lines in `swapView()`:

```js
var amdRequire = require(id);

// The Dojo 1 loader does not export itself, it only exposes itself globally; in this case
// `amdRequire` is an empty object, not a function. Other loaders return themselves and do not
// expose globally. This hopefully covers all known loader cases
amdRequire = typeof amdRequire === 'function' ? amdRequire : global.require;
```

`require()` returns an `Object` rather than a `function`, and `global.require` is `undefined`, so `amdRequire` becomes `undefined` too.   Note that if the `require("bogusPath.js")` throws an error, rather than returning an `Object`, so it's apparently not a path issue.

Problem occurs on Intern 3.0.3.  To reproduce, just `npm install requirejs` (version 2.1.20) and then add this to your configuration:

```js
loaders: {
	"host-node": "requirejs/require.js",
	"host-browser": "../delite/node_modules/requirejs/require.js"
},
```

Actually, I don't know why that code is running at all.  I'm trying to make Intern run the tests in a browser, so it doesn't matter what loader is being used inside Node.  But still, looks like a bug.

PS: From reading http://requirejs.org/docs/node.html perhaps it should be loading r.js not require.js?  But anyway I based my test off of the example listed in https://theintern.github.io/intern/#common-config:

```js
loaders: {
  'host-node': 'requirejs',
  'host-browser': 'node_modules/requirejs/require.js'
}
```

**Comment by csnover** [comment]
You need to load requirejs as specified in the example configuration by installing the npm package and using `requirejs`, which points to `r.js`, and not `requirejs/require.js`. `require.js` is for Web browsers only and will not work in Node.js. Yes, this is confusing, so I’ve added a documentation note calling it out specifically.

**Comment by wkeese** [comment]
Ah OK thanks.
