### ISSUE TITLE
intern:runner gets stuck never execute test cases 

### ISSUE THREAD

**Issue by mamatak** [theintern/intern#497]
I am using intern version 3.0.2
I see error in web console :
 ReferenceError: require is not defined

GET 
http://localhost:9000/__intern/node_modules/dojo/dojo.js [HTTP/1.1 404 Not Found 1ms]

With Intern 2.2.2 there is no error.

Even intern:sauce doesnt work.

**Comment by csnover** [comment]
This ticket doesn’t contain the information we need to investigate. Please read the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) and make sure to provide all the necessary information. All I can tell you from what you have reported is:

1. Intern doesn’t come with any `intern:sauce` Grunt task
2. Intern 3 doesn’t load `dojo.js` so whatever is doing this is a custom configuration or unsupported modification you’ve made to your copy of Intern

Please provide more detailed information including your configuration file and we can investigate further.

**Comment by csnover** [comment]
I’m closing this ticket since we haven’t heard back in a week. If you have the necessary information please reply and I will reopen the ticket. Thanks!
