### ISSUE TITLE
Struggling with Firefox Browser.

### ISSUE THREAD

**Issue by brunano21** [theintern/intern#499]
First of all, I'm not sure if this is an intern issue or a selenium one.
I'm having problem running functional tests against Firefox. The same tests run well against Google Chrome.
This is my configuration:

    Firefox ESR v 38.2.1
    Windows 7 x64
    Selenium Standalone server 2.47.1
    Intern v3.0.3

Intern.conf.env: `environments: [{ browserName: 'firefox', version: '38', platform: 'WINDOWS'}]`

This is the output of selenium server: http://pastebin.com/duDcGYp1
Basically, the browser starts, does stuff, closes by itself, then my test fail, and finally a new browser windows has been opened.

Can anyone suggest any solution? Or am I missing something?
Thanks.

**Comment by dylans** [comment]
The errors from your pastebin are as follows:
* org.openqa.selenium.UnsupportedCommandException: driver (org.openqa.selenium.firefox.FirefoxDriver) does not support org.openqa.selenium.html5.WebStorage
* org.openqa.selenium.UnsupportedCommandException: driver (org.openqa.selenium.firefox.FirefoxDriver) does not support org.openqa.selenium.html5.LocationContext

It would help to know if you're testing something using WebStorage or Geolocation, or if this is failing on Leadfoot's initial feature capabilities test before running your tests?

fwiw, this is not an issue on OS X with FF 40.0.3.

If you are testing web storage or geolocation, it would be helpful to see your test cases.

To test if it is the Leadfoot capabilities test itself that is failing, you could start by changing https://github.com/theintern/leadfoot/blob/0da713f4dcbd086503feea92d45a376eb76e9dec/Server.js#L266 to false. If that fixes the issue for you, then you could set it back to true and try debugging further with the capabilities info in this file.

**Comment by brunano21** [comment]
My test is quite simple and I'm not trying to access to WebStorage and/or Geolocation. 
It consists in ask for a url - `get(url)` - type username and password e so far. It fails on creation, so basically the browser gets opened, but then for some reason it closes, and the a new instance is created - but with an empty page.

I tried switching that flag to false, but the behaviour is the same. However I do not get that exception about WebStorage and Geolocation. 
The new pastebin is: http://pastebin.com/yPbAjZ55
Is it maybe fauld of FF ESR?

**Comment by dylans** [comment]
It's of course possible that Selenium 2.47.1 and FF ESR 38 are not working together. I would start by trying FF 40.

**Comment by vladikoff** [comment]
> It's of course possible that Selenium 2.47.1 and FF ESR 38 are not working together.

We've got tests constantly running against latest ESR and it works fine with latest Selenium

**Comment by brunano21** [comment]
So, @vladikoff what are you thoughts about this? Why does FF get closed and opened again during the test? 
I also searched for FF crash log, but I have not been lucky. No crash log.

**Comment by vladikoff** [comment]
>  Why does FF get closed and opened again during the test?  

I've never seen that happen. (Though I only use it on OS X). Could you try running this with a really simple test (just `get` some url) and also include ` fixSessionCapabilities: false,` in your config. Let us know how it goes

**Comment by brunano21** [comment]
Ok, just tried as you suggested. and it works well, as expected. 

First of all, I switched that boolean to false. So I do not get the unsupported suff. I'm not sure if it's good or not, by the way.
Anyway, I rewrote the test in order to do a `get(url)`, type username and password and click submit. The original test, does more or less the same thing, except that being a bit cryptic. 
Using the Page Object Pattern, I wrote an `Login` object, with following functions:

NOTE: _super_ is a superclass, which Login inherits from.

    Login._doLogin = function (args) {
        var self = this;
        var usernameValue = args[0];
        var passwordValue = args[1];
        var usernameInputId = _props.get("login.username.id");
        var passwordInputId = _props.get("login.password.id");
        var cssSelector = _props.get("login.submit.css");

        return _super_
            .setInputById.call(self, [usernameInputId, usernameValue])
            .then(function() {
                return _super_.setInputById.call(self, [passwordInputId, passwordValue]);
            })
            .then(function() {
                return _super_.clickBtnByCss.call(self, [cssSelector]);
            })
            .then(pollUntil("return document.getElementsByTagName(\"cirrusapp-core-app\")", 10000))
            .then(function (){ // NOTE This is wrong!
                console.log("Then untilPoll");
            })
            .getPageTitle()
            .then(function (title) {
                console.log(title);
            })
            .sleep(5000) // FIXME
            .catch(function (err) {
                console.log(err);
            });
    };

    Login.prototype.loadLoginPage = function(args) {
        var self = this;
        var remote = self._remote;
        return remote
            .get(require.toUrl(args[0]))
            .setFindTimeout(5000)
            .sleep(2000);
    }; 

Then using a promise approach, I chain the above functions.

The test that I rewrote is instead:

    "Test 2": function() {
        return this.remote
            .get(require.toUrl("https://dubxpcvm2327.mul.ie.ibm.com:9044/CuramCirrusClient/"))
            .setFindTimeout(5000)
            .findById('j_username')
            .click()
            .type('susan@example.com')
            .end()
            .findById('j_password')
            .click()
            .type('password')
            .end()
            .findByCssSelector('input[type=submit]')
            .click()
            .end();
    }

Now I'll need to understand the difference between tests above. Maybe something that I'm using in a wrong way? Or,something that FF does not handle as Chrome does?
Any suggestion would be really appreciated! Thanks!

PS: even with the `working simple` test, FF gets closed and re-open (but after the test is completed!). This allows me to think that in the not working test, something goes wrong, closing then FF.

**Comment by csnover** [comment]
If Firefox window closes in the middle of your tests, then the browser is probably crashing. I don’t think the Selenium log in the OP is complete, it only shows the feature detection running. Your inheritance code is wrong in your crashing example, you should never call anything on any superclass directly without using `apply` and you should never call anything on superclass except from a subclass override (e.g. call `super.foo` from `this.foo`).

**Comment by csnover** [comment]
Also, on Windows you should be able to find application crash logs in Windows Event Viewer.

**Comment by brunano21** [comment]
@csnover From my investigation I understood that the part which is creating issues is the `.sleep()`. Removing all of them the test works as expected. 
As far as the super calls are concerned, I'm calling from the `Login` *object*, methods that its parent is exposing. Furthermore, `.apply` and `.call` should have been the same thing, except for how you can pass arguments.
