### ISSUE TITLE
WebDriver not handling `waitForRunner = 'fail'` properly

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#502]
I was doing maintenance on one of my outstanding PRs #451 and noticed that the CI was failing.  Upon inspection I realised that I had added unit tests cases for the WebDriver reporter and that there had been a [test case that was now failing](https://travis-ci.org/theintern/intern/builds/81725117#L144).  Apparently d39632bec252a01cce4ba3340e7ce3242d360c4b appears to have introduced a regression that is causing Promises to be returned when they shouldn't be, basically not providing the features of `waitForRunner = 'fail'`.

I can't yet work out why it is failing, but I am pretty sure my [unit tests](https://github.com/kitsonk/intern/blob/6a7ac2646fa1ba6dfde99932b9050bcddfc4f706/tests/unit/lib/reporters/WebDriver.js#L388) cases reflect the desired and original behaviour.

**Comment by csnover** [comment]
the util function is returning the wrong value :(

**Comment by kitsonk** [comment]
Oh yeah, I see it now... yeah, that would explain exactly the behaviour I am catching in the tests.
