### ISSUE TITLE
Error handling in Proxy.js

### ISSUE THREAD

**Issue by eddiechihyi** [theintern/intern#506]
We are using Intern to unit test our existing dojo based widgets. While most of the tests running fine, some tests gave us a lot of trouble especially when we run the unit test against remote Selenium node. 

We noticed that if any of the existing widgets having AJAX POST to root path and having request body not in Json format, the proxy.js will simply throw exception and then the browser running the test will disconnect from the Intern so it stops the whole testing job. I have to put below try/catch block to handle this more peacefully.

I am requesting Intern to have better error handling inside Proxy.js and maybe also potentially adding logic to filter out non-Selenium actions so it can be more fault tolerance.

```
request.on('end', function () {
try{
var message = JSON.parse(data);
var runnerReporterPromise = self._publishInSequence(message);
}catch(err){
console.log("--- error:"+err + "  --- data is:" + data);
response.end();
}
``` Regards,
Eddie

**Comment by csnover** [comment]
Why are your widgets sending requests to endpoints that they don’t know about during testing? I’m happy to keep the proxy from crashing but filtering data is the wrong thing to do; your code is doing something bad and you should fix your code!

**Comment by kitsonk** [comment]
I :+1: making the Proxy more robust and surfacing up anything unexpected as either a hard fail (which is cruel, but accurate) or a warning (which is kind but cruel in a different way).

**Comment by eddiechihyi** [comment]
Hi Colin,

Our widgets are running fine in normal environment. I am talking about unit test scenarios which the test is running against sandbox browser and now all the underlying AJAX POST will by default POST to root path if they have not been explicitly override. We already put in some prevention fixes in our test but it's every difficult to find which one actually cause the issue if you have a lot of modules with all the dependencies. 

A good testing framework should not stop the whole testing job just because one test failure not matter what. We have experience couple these kinds of issues and because of the AMD and async natural of Intern/Selenium. The debugging is not trivial especially for junior developers. We know Intern is new but we have high hope that it will keep improve to make the tool better. That's why I am reporting this issue. Hope that makes sense to Intern team.

Regards,
Eddie

**Comment by jason0x43** [comment]
As of Intern 3.1.0 (942baa04), the Proxy will now respond with an HTTP 500 if there are errors processing a message. Does that resolve this issue?

**Comment by jason0x43** [comment]
Since there hasn't been any input for a while, I'm assuming this is in good shape now.
