### ISSUE TITLE
dojo2 defined as dojo in package.json conflicts when using npm3

### ISSUE THREAD

**Issue by odoe** [theintern/intern#511]
I've run into issues (using npm3) when I include intern in a project that also does a Dojo build. In this case, I have a node_modules/dojo dep for my app using dojo 1.10. Intern has the same dep, but it's dojo2, and it looks like dojo 1.10 takes priority in that folder and breaks Intern.

I've since reverted back to npm 2.x to avoid this issue on my machine.

You can see this happen with this repo https://github.com/odoe/esrijs-generator-demo

**Comment by csnover** [comment]
Thanks for the report but I see no Intern/npm 3 bug in your repository. You are telling Intern to use your copy of the Dojo loader by the `loaders` configuration you’ve defined, but you haven’t properly [configured the loader to run in pure AMD mode by setting `async: true`](https://github.com/csnover/dojo-boilerplate/blob/master/tests/intern.js#L1-L9), so your tests crash on startup. The exact same thing happens regardless of whether installation is done with npm 2 or npm 3.

If you can provide a series of steps that demonstrate a working test system with npm 2 and a broken test system with npm 3 please let me know and I will reopen this ticket.
