### ISSUE TITLE
Test result reporters do not create needed directories

### ISSUE THREAD

**Issue by sholladay** [theintern/intern#512]
**Environment:**
Intern: `3.0.6`
Node: `4.1.1`
npm: `3.3.5`

**Steps:**
1. Setup a typical project that depends on Intern, as recommended in the [user guide](https://theintern.github.io/intern/#directory-structure "Recommended directory structure for projects that use Intern.").
2. Configure a [test result reporter](https://theintern.github.io/intern/#reporter-results) to output a file inside of a directory that does not exist.

For example:
```js
reporters: [
    { id: 'JUnit', filename: 'report/junit.xml' }
]
```

**Current behavior:**
An error is thrown, with a useless stack trace:
```bash
Error: ENOENT: no such file or directory, open 'report/junit.xml'
  at Error  <native>
```

Interestingly, all of the code coverage reporters seem to handle this scenario just fine.

**Expected behavior:**
 - Something akin to `mkdir -p` is used to create intermediate path components.
 - Useful stack traces.

**Comment by dylans** [comment]
Closed via b8b979a.
