### ISSUE TITLE
Intern's Proxy.js doesn't support HTML5 pushstate

### ISSUE THREAD

**Issue by DavidSimner** [theintern/intern#513]
I'm trying to use Intern to test a single-page app that uses HTML5 pushstate.

My production server has been configured to serve the same HTML file for all requests, as per: http://readystate4.com/2012/05/17/nginx-and-apache-rewrite-to-support-html5-pushstate/

But I need to make the same config setting in intern.

At the moment I'm using a workaround, but it'd be really nice if intern supported this out-of-the-box.  I'm imagining it would be a config setting that specifies a html file which Proxy.js would serve.

For reference, the workaround I'm using is:
- In Intern, setting proxyUrl: 'http://localhost:8000/'
- And in my gulpfile.js, using gulp-webserver, and calling webserver({
 fallback: '/404.html',
 proxies: [
 { source: '/**intern/', target: 'http://localhost:9000/**intern/' },
 { source: '/app/', target: 'http://localhost:9000/app/' }
 ]
 })

It'd be much easier if HTML5 pushstate was supported out-of-the-box in intern, especially given the popularity of single page apps, and that it would make them much easier to test :)

**Comment by csnover** [comment]
So I guess my gut reaction is thus:

While I’m happy to entertain adding features that would be useful, the way you are using pushState is… not correct, so I don’t know how useful this would be as a built-in option (as opposed to, say, exposing the built-in HTTP server in a way that makes it easier to extend by some custom middleware).

pushState is intended to allow Ajax-like partial loads of pages that actually *have* distinct URLs on a server, where if you load the URL from the server it will return a complete page, and by using pushState you’re just optimising to avoid retransmitting the entire page.

The whole “unfortunately” part from the article you linked is, well, *the entire point of pushState*. If the URL on the server is always some stub page, you should just be using `location.hash`. Redirecting every 404 to a stub page breaks the Web by never returning the correct 404 response for a page that does not actually exist. You should never do what that article says to do.

I’d like to hear some opinions by other people as well before making a final decision on this.

**Comment by sholladay** [comment]
I agree that this isn't the right design choice. If you absolutely must do weird things like this, I think it would be good for you to take a look at [hoxy](https://github.com/greim/hoxy) and use that in your setup. It has a beautiful API and is probably a better tool for the job than Intern's own proxy would be, even after being exposed for middleware.

**Comment by rodneyrehm** [comment]
For the opionen part: I'm not sure I'd go as far as saying the OP is using pushState wrong. At best they're not using it as originally intended.

Disregarding the reasons for doing this, implementing #547 should provide the API to configure the proxy to allow this use-case without having to spin up a secondary server.

**Comment by jason0x43** [comment]
Closing this as it's out-of-scope for Intern's test server.
