### ISSUE TITLE
Multiple sessions are run on testingbot for iphone

### ISSUE THREAD

**Issue by herby** [theintern/intern#515]
As intern has problems with testingbot (#488), it not only fails to run the tests, but runs the session four times. each time eating up minutes by doing nothing.

**Comment by csnover** [comment]
This is the same problem as #516. Intern retries up to [`environmentRetries`](https://theintern.github.io/intern/#option-environmentRetries) times if a session fails to be created. TestingBot is broken, creates the session, then redirects to the wrong URL so Leadfoot thinks the session creation failed. This is not an Intern bug, but a bug in TestingBot.
