### ISSUE TITLE
Intern throws load timeout error for "intern" with requirejs

### ISSUE THREAD

**Issue by apsdehal** [theintern/intern#517]
Possibly due to https://github.com/theintern/intern/blob/master/lib/executors/PreExecutor.js#L369 
Adding a path for `intern/main` in `loaderOptions`'s `paths` options fixes this.

**Comment by csnover** [comment]
I’m not able to reproduce any issue when using RequireJS with the intern-tutorial, everything works fine. Could you please provide a reduced test case that demonstrates this problem?

**Comment by csnover** [comment]
This appears to be a bug in RequireJS 2.1.9 and earlier. 2.1.10 (released 8 Jan 2014) and later work fine.
