### ISSUE TITLE
Node v4 and v5 support

### ISSUE THREAD

**Issue by rodneyrehm** [theintern/intern#527]
Running intern on node `v5.0.0` and `v4.2.2` currently presents the following error

```
I'm `fs` modules
TypeError: fs.createWriteStream is not a function
  at Object.<anonymous>  <node_modules/intern/lib/ReporterManager.js:143:18>
  at Object.defineProperty.get [as output]  <node_modules/intern/lib/ReporterManager.js:99:24>
  at new JUnit  <node_modules/intern/lib/reporters/JUnit.js:127:23>
  at ReporterManager.add  <node_modules/intern/lib/ReporterManager.js:194:16>
  at <node_modules/intern/lib/executors/Executor.js:212:24>
  at execModule  <node_modules/dojo/loader.js:332:62>
  at <node_modules/dojo/loader.js:374:21>
  at guardCheckComplete  <node_modules/dojo/loader.js:361:9>
  at checkComplete  <node_modules/dojo/loader.js:366:32>
  at onLoadCallback  <node_modules/dojo/loader.js:428:17>
```

**Comment by kitsonk** [comment]
Strange, as I am running Intern under v5.0.0 and not having that issue.  Are you sure you don't have something else going on?  I also just tried master self tests and didn't have a problem.

In particular, `fs` in 5.0.0 still has `createWriteStream` which seems like your specific environment must be injecting some other module than `fs`.

**Comment by rodneyrehm** [comment]
strange indeed. deleted intern and installed it again with node 4.2.2 being active - and it works. I'm pretty sure that's the same thing I did to verify that the above stack trace wasn't caused by something I screwed up…
