### ISSUE TITLE
Suite.numFailedTests problem

### ISSUE THREAD

**Issue by brunano21** [theintern/intern#528]
I'm trying to play a bit with some of the properties of Suite and Test objects.
I noted that the below snippet 

    registerSuite(function() {

        return {
            name: "MySuite",
            before: function() {
                console.log("starting - setup");
                console.log("name", this.name);
                console.log("numTests", this.numTests);
                console.log("numFailedTests", this.numFailedTests);
                console.log("numSkippedTests", this.numSkippedTests);
            },
            after: function () {
                console.log(this.numFailedTests);
                console.log(this.numSkippedTests);
            },
            beforeEach: function(test) {
                console.log("beforeEach: " + test.name + " - "numFailedTests: " + this.numFailedTests);
            },
            afterEach: function(test) {
            },

            "test1": function() {
                
            },

            "test2": function() {
               
            },
        };
    });

is printing:

    starting - setup
    name MySuite
    numTests 2
    numFailedTests 2
    numSkippedTests 0
    beforeEach: test1 - numFailedTests: 2
    ✓ chrome on Windows 7 - MySuite - test1 (0.001s)
    beforeEach: test2 - numFailedTests: 1
    ✓ chrome on Windows 7 - MySuite - test2 (0s)
    0
    0
    No unit test coverage for chrome on Windows 7
    >> chrome on Windows 7: 0/2 tests failed

Using: `intern: 3.0.3`

As you may see numFailedTests is equal to 2 at beginning. Why? 
Am I wrong in something?

EDIT: updating to 3.0.6 did not fix the issue.

**Comment by gitgrimbo** [comment]
Do the tests need successful assertions to be classified as passing?

**Comment by brunano21** [comment]
Tests fail when a certain function returns an exception.
In other words, a generic functional tests is written as follow:

    "test1": function() {
       return myPageObject.run()
     },

If `run()` method returns an exception, then the test has to fail. Actually it works fine, I'm not only explaining why the suite's `numFailedTests` properties is equal to the number of suite's tests at the beginning (into the `before` function in example). 

I'm asking this because I want skip all remaining tests if a previous one failed.

Hope I have been clear.
Thanks.

**Comment by csnover** [comment]
Tests that aren’t passed and aren’t skipped are considered failed (this is in order to fail-safe in case of a problem). If a test has never run before it will be considered failed because it hasn’t passed and isn’t skipped.

**Comment by sholladay** [comment]
> I'm asking this because I want skip all remaining tests if a previous one has failed.

This is now available with the [`bail`](https://theintern.github.io/intern/#common-config) option.

```sh
intern run --webdriver --bail
```
