### ISSUE TITLE
Using __intern/client.html does not work without initialBaseUrl=/

### ISSUE THREAD

**Issue by sholladay** [theintern/intern#531]
This seems like a bug to me, based on the documentation.

#### Environment

Intern: `3.0.6` Node: `4.1.1` npm: `3.3.5` OS: `OS X 10.11.1` #### Steps

1. Setup a typical project that depends on Intern, as recommended in the [user guide](https://theintern.github.io/intern/#directory-structure).
2. Configure a test suite to run in your `tests/intern.js` config file. For example:

``` js<br />   suites: [<br />       'tests/unit/foo'<br />   ]<br />   ``` 3. Launch the Intern proxy, so as to avoid implementing your own static server.

``` bash<br />   node node_modules/.bin/intern-runner config=tests/intern proxyOnly<br />   ``` 4. In a browser (such as Chrome), visit http://localhost:9000/__intern/client.html?config=tests/intern

#### Current behavior

A 404 error is received for a bad URL.

```HTTP
GET http://localhost:9000/__intern/client.html/tests/unit/foo.js    loader.ts:878
``` The client has tried to load the test suite module relative to the client.html page.

Adding `&initialBaseUrl=/` to the client URL causes the test suite module to load properly.

#### Expected behavior

The [Intern User Guide](https://theintern.github.io/intern/#common-config) states that:

> In a browser with no initialBaseUrl argument, basePath is resolved relative to two directories above the Intern directory (i.e. node_modules/intern/../../)

This seems to indicate that `suites` are relative to the Intern user's project directory by default.

No `initialBaseUrl` should be necessary in this case.

**Comment by jason0x43** [comment]
The issue here is that Intern expects something like `node_modules/intern/client.html` here instead of `__intern/client.html`. The code in PreExecutor that computes the default base path from the initial path in a browser assumes that the initial path will be at least 3 elements deep (`node_modules/intern/client.html`). If it is, the last 3 elements are replaced by '/'. When using `__intern`, the path is only 2 elements deep, so is left unchanged. If you provide an `initialBaseUrl` config parameter, it is used instead of the computed default base path, which is why adding `&initialBaseUrl=/`makes the example work.

This seems like a documentation issue.

**Comment by sholladay** [comment]
So, in other words, the defaults are setup to assume that the browser client is being hosted by a custom static web server. This may or may not be what people typically do, I'm not sure. For me, I certainly find it easier to avoid that altogether. Are there any reasons to _not_ use the proxy in this fashion? Might it make more sense to treat using what ships with Intern as the normal thing and using your own web server as the outlier?

**Comment by jason0x43** [comment]
Hmmm...I'd say the defaults just assume you're accessing `client.html` on a real path. I was going to say that the '__intern' virtual path isn't meant to be used directly, but I see it mentioned in the guide, so...that should probably be fixed. I've always just run node-static when I want a static server, but I can see the utility in being able to use Intern's proxy for that purpose.

**Comment by sholladay** [comment]
Ah, yes. You are right of course. `http://localhost:9000/node_modules/intern/client.html?config=tests/intern` works without any `initialBaseUrl`. And if using the path over `__intern/` is considered more canonical, it makes perfect sense to have the defaults set up that way. I actually don't remember why

**Comment by jason0x43** [comment]
Intern's a bit smarter now about how it handles pathing. You can use either `node_modules/intern/` or `__intern/` (when using Intern's own server) to load the client runner, and you should not (in general) need to worry about the base path.

**Comment by sholladay** [comment]
I noticed that multiple issues of mine on this tracker have been edited by @morrinene and the code formatting is now broken.

I assume it was just a mistake, but it would be nice to know how / why that happened.

I will fix it later, so here is a screenshot for posterity.

<img width="772" alt="screen shot 2017-11-09 at 11 21 06 am 1" src="https://user-images.githubusercontent.com/3674950/32616372-310b42ce-c540-11e7-97b0-9cae8ab6ba38.png">
