### ISSUE TITLE
Support Babel async/await

### ISSUE THREAD

**Issue by rightaway** [theintern/intern#535]
In Intern 3.0.6 I can't seem to use it with Babel ES7 async/await, would make code look much cleaner.

```js
define((require) => {
  const tdd = require('intern!tdd');
  tdd.suite('suite', () => {
    tdd.test('test', async () => {
      const value = await something();
      // Continue test
    });
  });
});
```

Using this code under Babel works fine until async/await are added. Meaning the other ES6 features are no problem, like `const`, arrow functions, etc.

**Comment by csnover** [comment]
What do you mean by “can’t seem to use it”? What do you expect to happen, and what actually happens? How are you running Babel to convert your test code into code that your test environment can execute (as no runtime exists that supports this draft feature)?

**Comment by csnover** [comment]
Closing due to no response from OP. Please feel free to respond with the requested information and I’ll be happy to reopen this issue if it makes sense.
