### ISSUE TITLE
TeamCity: suiteEnd doesn't send the message when we have error in suite.after

### ISSUE THREAD

**Issue by LingSpb** [theintern/intern#537]
I have a test suite like below

```javascript
bdd.describe("Parent", function(){
bdd.describe("Child 1", function(){
bdd.after(function(){
expect("Child 1 after").to.equal("1");
});

bdd.it("Child 1 Test 1", function(){

});
bdd.it("Child 1 Test 2", function(){

});
});
bdd.describe("Child 2", function(){

bdd.it("Child 2 Test 1", function(){
});
bdd.it("Child 2 Test 2", function(){
});
});
});
```

The output with TeamCity reporter is

> ## teamcity[**testSuiteStarted** name='chrome on any platform - Parent' startDate='Fri Nov 20 2015 12:01:43 GMT+0100 (W. Europe Standard Time)' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.054']
> ## teamcity[**testSuiteStarted** name='chrome on any platform - Parent - Child 1' startDate='Fri Nov 20 2015 12:01:43 GMT+0100 (W. Europe Standard Time)' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.061']
> ## teamcity[testStarted name='chrome on any platform - Parent - Child 1 - Child 1 Test 1' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.066']
> ## teamcity[testFinished name='chrome on any platform - Parent - Child 1 - Child 1 Test 1' duration='0' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.072']
> ## teamcity[testStarted name='chrome on any platform - Parent - Child 1 - Child 1 Test 2' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.074']
> ## teamcity[testFinished name='chrome on any platform - Parent - Child 1 - Child 1 Test 2' duration='0' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.077']
> ## teamcity[**testSuiteStarted** name='chrome on any platform - Parent - Child 2' startDate='Fri Nov 20 2015 12:01:43 GMT+0100 (W. Europe Standard Time)' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.085']
> ## teamcity[testStarted name='chrome on any platform - Parent - Child 2 - Child 2 Test 1' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.086']
> ## teamcity[testFinished name='chrome on any platform - Parent - Child 2 - Child 2 Test 1' duration='0' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.088']
> ## teamcity[testStarted name='chrome on any platform - Parent - Child 2 - Child 2 Test 2' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.089']
> ## teamcity[testFinished name='chrome on any platform - Parent - Child 2 - Child 2 Test 2' duration='0' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.091']
> ## teamcity[**testSuiteFinished** name='chrome on any platform - Parent - Child 2' duration='9' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.094']
> ## teamcity[**testSuiteFinished** name='chrome on any platform - Parent' duration='36' flowId='9e28fa74-d82b-41b7-8c6c-85db75dfb0f6' timestamp='2015-11-20T11:01:43.097']
> 
> Error: One or more suite errors occurred during testing
>   at <..\node_modules\intern\lib\executors\Executor.js:304:13>
>   at <..\node_modules\intern\node_modules\dojo\Promise.ts:393:15>
>   at runCallbacks  <..\node_modules\intern\node_modules\dojo\Promise.ts:11:11>
>   at <..\node_modules\intern\node_modules\dojo\Promise.ts:317:4>
>   at run  <..\node_modules\intern\node_modules\dojo\Promise.ts:237:7>
>   at <..\node_modules\intern\node_modules\dojo\nextTick.ts:44:3>
>   at process._tickCallback  node.js:355:11
> Stopping IISExpress
> npm ERR! Test failed.  See above for more details.

As you can notice, there is no **testSuiteFinished** for the suite **Child 1** which will cause the wrong wrapping when that suite has a sibling as you can see in the picture below
![image](https://cloud.githubusercontent.com/assets/4546284/11298445/41a6e65e-8f7f-11e5-980f-c4e7ad544e32.png)

**Comment by croes** [comment]
Errors thrown in Suite.after was also the cause of issues in #525

**Comment by jason0x43** [comment]
The suiteEnd event is now always fired when a suite is finished. The `error` property on a suite indicates whether there were suite errors.
