### ISSUE TITLE
Relative basePath is relative to cwd rather than config file path, unlike RequireJS AMD

### ISSUE THREAD

**Issue by pizza2code** [theintern/intern#550]
I've been working with AMD through RequireJS for some months now.  So it was a surprise when running intern-client that a relative basePath (or baseUrl) in the config file is treated as relative to the cwd rather than relative to the config file.  Why should it matter where I'm running the command from, as long as I specify the right config file?

RequireJS treats baseUrl as relative to the script file which defines it.  Is there a good reason to deviate from this practice?

**Comment by kitsonk** [comment]
A browser doesn't have a cwd... so the analogy is a bit apples and oranges.  It is the more common practice to have things be relative to the cwd on a command line.

This was discussed largely in #249 though and why in Intern 3 the basePath and baseUrl were separated, because of the expected behaviours of a "browser" and a "command line".

**Comment by pizza2code** [comment]
I agree, it makes sense to have paths be relative to the cwd on the command line... when specifying paths on the command line.  If there's a path in a config file, unless it was an alias in .bashrc, I wouldn't expect the path meaning to change based on where I was when I referenced the file.

**Comment by jason0x43** [comment]
The overall goal is consistency. Different AMD loaders may have different defaults for `baseUrl`, and those may be environment-dependent (amdjs-api suggests that `baseUrl` should default to the [current working directory](https://github.com/amdjs/amdjs-api/wiki/Common-Config#baseurl-)). Intern is typically used in both Node and browser environments, and we want relative module locations to be the same in both environments to make reasoning about where things are easier (and to avoid the need for environment-specific paths).
