### ISSUE TITLE
Problems with testing in the browser and oddities with console.log messages

### ISSUE THREAD

**Issue by metasean** [theintern/intern#560]
These problems are complicated enough that I can't just put code snippets in this issue, so I set up a public C9 repo that demonstrates the problems.

The repo is available at: https://ide.c9.io/metasean/intern-tutorial#openfile-README.md

PROBLEMS:
  1. The functional test's console.log shows up in the terminal, but ***NOT*** in the browser.  
  2. The unit test's console.log shows up in the browser, but ***NOT*** in the termina  l.
  3. **>->->->->-> MASSIVE PROBLEM <-<-<-<-<-<**  
  Rerunning the tests in the browser *OCCASIONALLY*, but **RARELY**, and certainly ***NOT ALWAYS*** reruns the tests. (e.g. change the `hello.js` console.log message and refresh the browser; it will take a minute or so for the test/s to run.)
  4. Running the tests in the browser, does ***NOT*** report anything about the unit test (even though it shows the console.log from the unit test)

**Comment by kitsonk** [comment]
With 1 and 2, it sounds like you don't understand the difference between functional and unit tests.  Any `console.log` statements will be logged where the code is executing.  Functional tests are a harness which remote commands are run via the Selenium/WebDriver interface, where the code is running on the host machine and the commands are being run remotely.  For unit tests, the code is loaded in the browser, therefore the `console.log` statements are running on the browsers.

I think 3 and 4 are related to your confusion about 1 and 2.

**Comment by metasean** [comment]
In regards to the tests not being re-run:
I'm definitely learning how to do TDD and use intern, but *If I make a change to the code, save the revised code, and explicitly re-run the test,* then my expectation (and the expectations of those I've shown this to) is that it will actually run again! 

Results for each of three possible testing methods (minus the code coverage table):
 -  **`./node_modules/.bin/intern-client config=tests/intern`** (run from C9 terminal):  

   ```
   :-) from with the "greet" unit test
   PASS: hello - greet (3ms)
   0/1 tests failed
   0/1 tests failed
   ```  

   Note: `:-) from with the "greet" unit test` is my console.log message for the unit test.  

   Comments: Only the unit tests are run, but I get the console.log messages from the unit tests *and* the results of the unit tests.   This is as expected.


 -  **`./node_modules/.bin/intern-runner config=tests/intern`**  (run from C9 terminal through BrowserStack):  

   ```
   Listening on 0.0.0.0:9000
   Tunnel started
   ‣ Created session firefox 37 on MAC (9d8a91d16b2d3b032d139e9b08c02ad9f145edba)
   ✓ firefox 37 on MAC - unit tests - hello - greet (0.002s)
   from within the "greeting form" functional test
   ✓ firefox 37 on MAC - index - greeting form (2.641s)
   ```

   Notes: `:-) from with the "greet" unit test` is my console.log message for the unit test. `from within the "greeting form" functional test` is my console.log message for the functional test.  

   Comments: Both the unit and functional tests are run, but I *ONLY* get the console.log messages from the functional tests.   Since this is running via the tunnel, I would expect to get all console.log messages reported. 

   How do I get console.log messages from both unit and functional tests to be displayed?


 -  **`client.html`**  (run through BrowserStack):  

   ```
   hello Console.js:76
   :-) from with the "greet" unit test hello.js:9:13
   PASS: greet (1ms) Console.js:85:4
   0/1 tests failed Console.js:62:4
   0/1 tests failed
   ```

   Notes: `:-) from with the "greet" unit test` is my console.log message for the unit test. 

   Comments:  Only the functional tests results are run, but I *ONLY* get the console.log messages from the unit tests.   Since this is running via the tunnel in the browser, I would hope all tests would be run and to get all console.log messages reported, but if it is analogous to the terminal's `./node_modules/.bin/intern-client config=tests/intern` then I would expect only the functional test to be run, *BUT* I'd also expect the functional test's console.log messages to be displayed.

   How do I run both unit and functional tests from the get console.log messages from both unit and functional tests to be displayed?

**Comment by kitsonk** [comment]
Again, you are missing some fundamentals.  You are not understanding the difference between function and unit tests and where the code actually executes, which would explain why your expectations of  `console.log` messages is not met.

This isn't really the support forum for Intern, as [stated in the contributing guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) which were available when originally opening this issue.

> but If I make a change to the code, save the revised code, and explicitly re-run the test, then my expectation (and the expectations of those I've shown this to) is that it will actually run again!

It is hard to diagnose why this isn't meeting your expectations.  Either your expectations are wrong or you are doing something that is hard to diagnose.  I am afraid without seeing exactly what you are doing to cause this mis-alignment of expectations, it is impossible to inform you of why they are mis-aligned.

If the freely available sources of support don't meet your needs, there are commercial options available as well, but as the contributing guidelines state, this is not the support forum.
