### ISSUE TITLE
Not able to run the functional test cases parallel on sauce labs.

### ISSUE THREAD

**Issue by MohanKalidindi** [theintern/intern#566]
Not able to run the functional test cases parallel on sauce labs. It is executing sequentially all the functional tests on different environments paralelly

**Comment by csnover** [comment]
Thank you for interest in Intern!

The bug tracker is not a support forum. Please read the [contribution guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md) to learn how to receive support. Thanks!
