### ISSUE TITLE
Maximum call stack size exceeded with runner tests

### ISSUE THREAD

**Issue by jonnycornwell** [theintern/intern#568]
Description: If an error occurs in a suite before/after intern exits with a maximum call stack exceeded error, leaving the browser open and the test process is terminated.

Steps to reproduce:
Using the runner, execute this test suite in the browser (I tested with chrome 47 on windows, using selenium 2.46):

```
define(function (require) {
var bdd = require('intern!bdd');

bdd.describe('the thing being tested', function () {
bdd.before(function () {
// In webpage this is reported correctly with
// a message "Fatal error during pre-execution stage"
// throw new Error("BOOM");
});

bdd.after(function () {
throw new Error("BOOM");
});

bdd.it('a passing test', function () {
});
});
});
``` Expected result: Tests to run with a suite error and end gracefully without leaving browser open or reporter error.

Actual result:

```
C:\D\Intern test>node_modules\.bin\intern-runner config=tests/intern
Listening on 0.0.0.0:8555
Tunnel started
? Created session chrome on any platform (bdd83a93-3509-46a8-a8b1-1523ead26b53)
√ chrome on any platform - unit tests - the thing being tested - a passing test (0.001s)
Suite chrome on any platform - unit tests - the thing being tested FAILED
Error: BOOM
at Suite.<anonymous>  <tests\unit\tests.js:12:10>
at Suite.target.(anonymous function).dispatcher [as teardown]  <__intern\node_modules\dojo\aspect.js:75:55>
at <__intern\lib\Suite.js:363:36>
at new Promise  <__intern\node_modules\dojo\Promise.js:172:17>
at teardown  <__intern\lib\Suite.js:362:12>
at <__intern\lib\Suite.js:386:13>
at getFinalValue  <__intern\node_modules\dojo\Promise.js:258:35>
at <__intern\node_modules\dojo\Promise.js:272:24>
at <__intern\node_modules\dojo\Promise.js:156:41>
at runCallbacks  <__intern\node_modules\dojo\Promise.js:19:22>
Reporter error!
RangeError: Maximum call stack size exceeded
at Suite.toJSON  <__intern\lib\Suite.js:394:20>
at Object.stringify  <native>
at sendRequest  <__intern\lib\reporters\WebDriver.js:146:17>
at Object.WebDriver._send  <__intern\lib\reporters\WebDriver.js:176:5>
at Object.WebDriver._sendEvent  <__intern\lib\reporters\WebDriver.js:130:16>
at Object.WebDriver.suiteEnd  <__intern\lib\reporters\WebDriver.js:54:16>
at <__intern\lib\ReporterManager.js:250:29>
at Array.map  <native>
at ReporterManager.emit  <__intern\lib\ReporterManager.js:232:39>
at report  <__intern\lib\Suite.js:199:34>
Error: Repeated sequence for session bdd83a93-3509-46a8-a8b1-1523ead26b53: 11 last 0 cur
at Proxy._publishInSequence  <node_modules\intern\lib\Proxy.js:181:11>
at IncomingMessage.<anonymous>  <node_modules\intern\lib\Proxy.js:63:39>
at IncomingMessage.emit  <events.js:92:17>
at <_stream_readable.js:943:16>
at process._tickCallback  <node.js:419:13>
``` Intern version: 3.0.6

If you need any more info let me know and can retest if needed,
J

**Comment by csnover** [comment]
This is related to the need to severely reduce the amount of data transmitted in response to tests being completed. If the WebDriver reporter did not try to serialise whole tests/suites this problem would not occur, and the system would be much faster and less breaky in general.

**Comment by sholladay** [comment]
Presumably it at least wouldn't crash if it used iteration instead of recursion.

I wonder how much easier that would be to implement vs simplifying what gets transmitted.

**Comment by jason0x43** [comment]
This doesn't seem to be related to the amount of data being transmitted -- the stack error is being generated in the browser while trying to serialize the suite, which in the given test case only contains a single test. From running the test myself, it looks like `Suite.toJSON` is entering into a recursive loop.

**Comment by jason0x43** [comment]
A call to `JSON.stringify` on the sample `Suite` object in `reporters/WebDriver#_send` is causing the stack size exceeded error.

**Comment by jonnycornwell** [comment]
Never got round to providing the workaround I found for this

In Suite:
<pre>relatedTest: this.error.relatedTest</pre>
needs to be
<pre>relatedTest: this.error.relatedTest === this ? undefined : this.error.relatedTest</pre>
