### ISSUE TITLE
Maintainers needed

### ISSUE THREAD

**Issue by csnover** [theintern/intern#579]
Friends,

I am not currently able to fulfil my obligations as project lead, as I am not working on any Web/JS projects, and I have no spare time to spend working on it for free any more. I am not sure if/when this will no longer be the case.

So, if anyone is interested in stepping up to help maintain this project (at least review/land pull requests, and publish releases using the automated release script, so people can actually use the new stuff), please let me know here—or if you prefer, you may contact me privately through [my Web site](https://zetafleet.com/contact.php).

If you rely on any of the Intern tools or libraries and wish to sponsor development, I may be able to perform some short-term paid contracts. To discuss such an arrangement, please contact me through [my Web site](https://zetafleet.com/contact.php).

Thanks,

**Comment by jason0x43** [comment]
> publish releases using the automated release script

Silly write-only NPM repo... /grumble. Anyway, I can review and merge, and maybe even publish.

**Comment by olemis** [comment]
I use the library in my personal projects and I'm in train of integrating it with code written by the [brython-dev](http://github.com/brython-dev) organization . As such , I'd be interesting in helping maintain this project .

**Comment by dylans** [comment]
At the moment, a mix of @jason0x43 , @devpaul , @kitsonk , and me are doing what we can to help maintain and add new features, so I think we should mark this as closed. Obviously the more high quality help we get, the better we'll do in moving forward with Intern's mission to provide a highly useful test stack.
