### ISSUE TITLE
Intern breaks shrinkwrap in npm 3.x

### ISSUE THREAD

**Issue by alekstorm** [theintern/intern#586]
To reproduce:

```
$ npm -v
3.6.0
$ npm install intern
...
$ npm shrinkwrap
npm ERR! Darwin 14.0.0
npm ERR! argv "/Users/alek/.nvm/versions/node/v5.6.0/bin/node" "/Users/alek/.nvm/versions/node/v5.6.0/bin/npm" "shrinkwrap"
npm ERR! node v5.6.0
npm ERR! npm  v3.6.0

npm ERR! Problems were encountered
npm ERR! Please correct and try again.
npm ERR! extraneous: chai@3.0.0 /Users/alek/foo/node_modules/chai
npm ERR! extraneous: diff@1.1.0 /Users/alek/foo/node_modules/diff
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
```

Simply running `npm ls` instead of `npm shrinkwrap` also triggers the bug. This appears to be due to the symlinking of the `chai` and `diff` modules in https://github.com/theintern/intern/blob/3.0.6/support/fixdeps.js, and prevents us from upgrading to Node 5/npm 3, since we shrinkwrap. For more info, see https://github.com/npm/npm/issues/9703#issuecomment-154521493.

**Comment by sholladay** [comment]
I hit this today, too. As someone who has [worked on](https://github.com/theintern/intern/commit/aff8eb9b01bf35335a2c2a6c4f1df7b6af527375) the symlinks that cause this, I am not sure offhand how to solve it. Intern uses this structure because AMD stuff in the browser has no way of walking the filesystem and thus needs to be able to make simple assumptions about where things live.

The original `fixdeps.js` commit that started doing symlinking: https://github.com/theintern/intern/commit/e9360701376f7e7915d1459d218cfd59fce8c040

It has caused [plenty of problems](https://github.com/theintern/intern/issues?utf8=%E2%9C%93&q=symlink), so it's not like Intern _wants_ to do this, but there hasn't yet been a solution deemed truly superior.

**Comment by jason0x43** [comment]
@alekstorm has an interesting solution -- symlink the AMD dependencies into somewhere other than `node_modules`, and have browser-based code look there.

**Comment by vladikoff** [comment]
> @alekstorm has an interesting solution -- symlink the AMD dependencies into somewhere other than node_modules, and have browser-based code look there.

That is a weird pattern for npm / node based projects

**Comment by sholladay** [comment]
Yeah, agreed. It does seem to do the trick, while being backwards compatible, though.

**Comment by alekstorm** [comment]
Hey, I'm not too enthusiastic either. But it solves the problem, and IMO is no worse than before.

**Comment by vladikoff** [comment]
What if we `npm shrinkwrap` the dependencies? Last time I tried this it force tree of dependencies in npm 3

**Comment by jason0x43** [comment]
The whole fixdeps system is a weird pattern for node projects, but Intern has some browser-based requirements that are outside node's scope. This solution is at least weird in a way that doesn't directly conflict with npm's expectations. It leaves the existing node module structure intact, and confines the symlinking to a location not managed by npm. The key question is whether it breaks anything else. (Nothing immediately comes to mind.)

**Comment by sholladay** [comment]
> What if we npm shrinkwrap the dependencies?

As far as I know this doesn't guarantee that npm will put chai (etc) underneath Intern's directory. Wouldn't it still be allowed to "hoist" them? I'm not 100% sure, but this would be interesting. Using shrinkwrap to make shrinkwrap possible would be tasty.

**Comment by arty-name** [comment]
@jason0x43, would it be possible to publish this fix to npm? The bug blocks us from updating any of our dependencies for quite some time now.

**Comment by kitsonk** [comment]
We will do an npm release soon, but there is no actual distribution build step with Intern, so a dependency of `"intern": "theintern/intern#7b524a057a4a7140d0a4422b18f2084975746dfe"` works until it is released.

**Comment by arty-name** [comment]
Thank you, @kitsonk!
