### ISSUE TITLE
Is intern support function testing on maps.

### ISSUE THREAD

**Issue by SwethaVitta** [theintern/intern#587]
We have a app having leaflet maps. is intern supports this.

**Comment by sholladay** [comment]
Hi @SwethaVitta. The answer is most likely yes. A lot more information is needed to be 100% certain.

FYI, this is a bug tracker. The [Contributing Guidelines](https://github.com/theintern/intern/blob/master/CONTRIBUTING.md#how-to-get-help) state that you should ask questions like this on [StackOverflow](http://stackoverflow.com/) instead. You will get way more answers and help over there.

**Comment by SwethaVitta** [comment]
Actually we have a application that uses leaflet js for displaying maps on browser. and we are doing lot of map operations using this leaflet library. we want to test this map functionalities by writing some automated tests.
Is it possible through intern?

**Comment by sholladay** [comment]
Do you have a link to your [StackOverflow](http://stackoverflow.com/) question?
