### ISSUE TITLE
TeamCity reporter is missing error stack

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#591]
Using Intern 3.0.6

### Actual 
The TeamCity reporter shows the Selenium error, but not the JS stack where the runner timed out

![](http://v14d.com/i/56df1cab25c96.jpg)

### Expected

The selenium and the JS stack in the error field

**Comment by jrgm** [comment]
This seems to give the right output, but need to run with this for a while and figure out what intern regression tests I need to run.

https://github.com/theintern/intern/compare/3.0...jrgm:fix-record-stack-in-teamcity-reporter?expand=1

<img width="432" alt="intern-stack" src="https://cloud.githubusercontent.com/assets/758162/13626309/9667aa6a-e575-11e5-8df2-733aea6b4cab.png">

**Comment by jrgm** [comment]
Okay, I know what to run now (I think). Now to figure out how to get the expected output to line up. Later.

**Comment by jrgm** [comment]
Updated with tests. Not thrilled with the change in tests, but it does what it does ;-)
https://github.com/jrgm/intern/commit/e29282f68e3c1670755f241f463e67d3623f184e
@vladikoff - any comments? I'll put in a PR if it looks good (and I fill out the contributor thing).

**Comment by vladikoff** [comment]
@jrgm the output looks excellent!

**Comment by jason0x43** [comment]
Fixed in https://github.com/theintern/intern/commit/2d9c64c1b6947224d45253f86c118ad6c5df55ac
