### ISSUE TITLE
Improve the stack trace for a SyntaxError in a test

### ISSUE THREAD

**Issue by sholladay** [theintern/intern#592]
The stack trace currently provided when there is a simple SyntaxError in a test is ... less than ideal.

The situation with [displayErrors being undocumented](http://stackoverflow.com/questions/20658921/test-parse-errors-in-intern-do-not-include-the-line-that-describes-the-error) has changed. It is now a fully supported part of [the API](https://nodejs.org/api/vm.html#vm_vm_runinthiscontext_code_options). Intern should use it to provide the place in the code where the SyntaxError lives.

**Edit:** `displayErrors` is true by default, actually. So the output must be truncated somewhere.

**Comment by jason0x43** [comment]
This should probably be an upstream enhancement request, either for https://github.com/dojo/dojo2 (which is what Intern uses now) or https://github.com/dojo/loader (which is what Intern will likely switch to at some point), or both, since that's where `runInThisContext` is actually called.

**Comment by Tomdye** [comment]
Have updated in the dojo/loader issue, looks like `intern` is truncating the output somewhere

**Comment by jason0x43** [comment]
Closing this since it's for Intern 3 and an older dojo
