### ISSUE TITLE
xit and xdescribe methods in bdd interface

### ISSUE THREAD

**Issue by d48** [theintern/intern#595]
I find myself incrementally testing methods and commenting out some without having them run or report. I was using `this.skip` but have been wanting to block out bigger chunks as well. At this point i've just been commenting out blocks of code in my test files which at some points becomes a big cumbersome.

Are there any issues with providing an interface for `bdd` for `xit` and `xdescribe` methods with a possible noop method or at the least report based on description of block that is being bypassed?

I think this would be more convenient then the `this.skip()` method since I can deactivate entire describe block. If it's approved, I can just update the interface it looks like here with a noop method for both `xit` and `xdescribe`:

https://github.com/theintern/intern/blob/2c209d96820020080f26efd84fab510510afeaab/lib/interfaces/bdd.js

```
return Object.create(tdd, {
describe: createValue(tdd.suite),
it: createValue(tdd.test),
suite: { value: undefined },
test: { value: undefined },
xdescribe: function() {},
xit: function() {}
});
```

**Comment by jason0x43** [comment]
This sounds reasonable. For the time being, you use `this.skip` in a suite `before/setup` method to skip an entire suite.

**Comment by d48** [comment]
Okay great. I'll see when I can get some time to update and properly set up unit tests for it. Thanks

**Comment by joshrhoades** [comment]
@d48 and are you going to give credit to who actually did this with our intern instance, which was actually me? :P

**Comment by d48** [comment]
ha, of course!

**Comment by kailo777** [comment]
Is there any progress about the implentation from xit and fit?

**Comment by kailo777** [comment]
@jason0x43 its there any progress about the implentation from xit and fit & xdescribe and fdescribe?

**Comment by jason0x43** [comment]
@kailo777 Not that I'm aware of, no. It sounded like a PR was incoming.

**Comment by jason0x43** [comment]
This shouldn't be too hard to do, though. The `xdescribe` and `xit` functions could just be wrappers that ignored the test function they were given and created a test containing `skip(description)`. Something like that.
