### ISSUE TITLE
Global require in typings/node/node.d.ts

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#598]
If you use another TypeScript based loader with Intern (e.g. the Dojo 2 Loader) and include the typings of both Intern and the loader, the NodeJS typings will conflict with that loader and you will get typescript errors such as:

```
error: error TS2451: Cannot redeclare block-scoped variable 'require'
``` Since Intern will always utilise some other loader than the native NodeJS loader, it is safe to remove [this declaration](https://github.com/theintern/intern/blob/942baa040a824477f1cda55abd9d029553873db5/typings/node/node.d.ts#L30) from the the typings.

**Comment by jason0x43** [comment]
Closing this since Intern no longer includes custom node typings
