### ISSUE TITLE
SauceLabs version should be configurable instead of hardcoded

### ISSUE THREAD

**Issue by Delvach** [theintern/intern#599]
My organization is currently using intern for testing, and have run into periodic timeouts with SauceConnect that sound like they may be alleviated by upgrading to the latest version.  It looks like SauceConnect is currently hardcoded to '4.3' within the digdug project.

As I'm just getting into this project I'm hesitant to create any pull requests on either repo myself, but it would be helpful to have a configurable SAUCE_VERSION.

**Comment by jason0x43** [comment]
Fixed in https://github.com/theintern/digdug/commit/bcb3c40bf44e5f116fa7b72331f8f7f69788a947

**Comment by jason0x43** [comment]
@colmsnowplow That property is documented in the current docs at https://theintern.io/docs.html#Dig%20Dug/2/api/SauceLabsTunnel/scversion. The documentation at https://theintern.io/digdug/module-digdug_SauceLabsTunnel.html is for an earlier version of Dig Dug.

**Comment by colmsnowplow** [comment]
My mistake, thanks for pointing that out!
