### ISSUE TITLE
Getting Cannot read property 'reduce' of undefined when running 3.1.0

### ISSUE THREAD

**Issue by ericuldall** [theintern/intern#600]
My tests work fine in v3.0.6, when I run v3.1.0 they fail with the following error:

```
TypeError: Cannot read property 'reduce' of undefined
  at Object.resolveModuleIds  <node_modules/intern/lib/util.js:807:20>
  at <node_modules/intern/lib/executors/PreExecutor.js:397:38>
  at new Promise  <node_modules/intern/browser_modules/dojo/Promise.ts:411:3>
  at resolveSuites  <node_modules/intern/lib/executors/PreExecutor.js:395:16>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:393:15>
  at runCallbacks  <node_modules/intern/browser_modules/dojo/Promise.ts:11:11>
  at <node_modules/intern/browser_modules/dojo/Promise.ts:317:4>
  at run  <node_modules/intern/browser_modules/dojo/Promise.ts:237:7>
  at <node_modules/intern/browser_modules/dojo/nextTick.ts:44:3>
  at doNTCallback0  <node.js:407:9>
```

Are there changes that aren't backwards compatible in 3.1.0?

**Comment by owiber** [comment]
I had this problem due to suites being null. Making it [] fixed it, but it's prob a bug since docs say "suites can be set to null to skip loading the unit testing system when in runner mode"

**Comment by jason0x43** [comment]
Aaaaand that's a case that apparently doesn't have a unit test. Yes, that's a bug. You should still be able to set `suites` to null.

**Comment by ericuldall** [comment]
I don't believe I have any suites set to null:

https://github.com/the-letter-e-production/termoil/tree/master/tests

**Comment by owiber** [comment]
Prob same issue with `functionalSuites` (which you have commented out, so is prob `undefined`)

**Comment by ericuldall** [comment]
Yes, uncommenting functionalSuites did the trick.

Now set to: `functionalSuites: [],`

**Comment by jason0x43** [comment]
Fixed in https://github.com/theintern/intern/commit/d3304b68b75ac786ea5939d790f8c8736840a862

**Comment by erikdstock** [comment]
This broke tests in a test suite I'm running developing and running remotely from. I don't want to run unit tests (or more specifically visit client.html which does not exist on the system under test) but now that doesn't seem an option. My sauce tests tries to visit /__intern/client.html and gets lost.

Am I missing something? Keeping `suites` out of my config did this before. now intern is trying to `reduce` on undefined.

**Comment by jason0x43** [comment]
As mentioned above, a bug was introduced that broke Intern's handling of a null or undefined `suites` value. A fix will be included in the next point release.

**Comment by erikdstock** [comment]
Ah, sorry! Missed the full resolution and thought everyone had just settled on [].

**Comment by jason0x43** [comment]
Yeah, just using [] won't totally fix the issue you're seeing because a `ClientSuite` will still be created when `suites` is `[]`, which means Intern will still try to load `client.html`. The committed fix restores the previous behavior.

**Comment by sholladay** [comment]
Personally, I can't see any good reason why the behavior ought to differ between `undefined`, `null`, and `[]`. These all seem to convey, "I have nothing for you."

**Comment by jason0x43** [comment]
In the Runner executor, there is a semantic difference between a falsey value for `suites` and an empty array. A falsey value means there are definitely no suites, so the runner doesn't even try to run unit tests. An empty array may only be empty on the Node side, but could be populated in the browser, so the runner creates a ClientSuite for unit tests.
