### ISSUE TITLE
Tests should handle Suite#skip

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#605]
When `this.parent.skip()` is called from within a test, the test should be marked as skipped.

**Comment by aciccarello** [comment]
It looks this still is a problem. Interestingly it seems like it is skipped but not noted correctly.

<img width="1278" alt="Screen Shot 2019-12-06 at 5 40 16 PM" src="https://user-images.githubusercontent.com/11273838/70366851-7ef9bb00-184f-11ea-8579-7dd75a3d3808.png">

**Comment by jason0x43** [comment]
Resolved by #1009
