### ISSUE TITLE
unresolved packageLocation failing suite globbing

### ISSUE THREAD

**Issue by rodneyrehm** [theintern/intern#610]
[require.toUrl()](https://github.com/theintern/intern/blob/master/lib/util.js#L814) may return unresolved paths, e.g. 'some/../where/else'. This can lead to the situation that `packageLocation` is _not_ a substring of `path` in [pathToModuleId](https://github.com/theintern/intern/blob/master/lib/util.js#L802-L804), yielding invalid paths. I'm not sure if this is limited to using RequireJS as the loader, but it's where I observed this.

I made the suite globbing work by replacing [`var packageLocation = require.toUrl(package);`](https://github.com/theintern/intern/blob/master/lib/util.js#L814) with `var packageLocation = pathUtil.resolve(require.toUrl(package));`. But I'm not sure if this possibly breaks something else.

I also had to change my config from

```js
{
loaders: {
'host-node': 'requirejs',
'host-browser': 'node_modules/requirejs/require.js',
},
loaderOptions: {
baseUrl: 'src/js/',
packages: [
{ name: 'tests', location: '../../tests/' },
// …
],
paths: {
// …
},
},
},
``` to

```js
{
loaders: {
'host-node': 'requirejs',
'host-browser': 'node_modules/requirejs/require.js',
},
loaderOptions: {
baseUrl: 'src/js/',
packages: [
// …
],
paths: {
'tests': '../../tests',
// …
},
},
},
``` i.e. compensate the `baseUrl` using `paths` instead of `packages`. But this may have to do with my lack of understanding what their difference is…

Did I hit an issue with Intern, or am I just doing it wrong?

**Comment by dylans** [comment]
@rodneyrehm did you ever receive feedback on this elsewhere (e.g. IRC or StackOverflow)?

**Comment by rodneyrehm** [comment]
@dylans if I did, I don't remember. I'm not patching utils.js locally, so I assume I don't have this problem anymore

**Comment by jason0x43** [comment]
Closing this because it's specific to Intern 3
