### ISSUE TITLE
command line args not forwared by grunt task 

### ISSUE THREAD

**Issue by gbaumgart** [theintern/intern#621]
Hi,
I can't retrieve the original command line arguments in my test units. Is there any chance this is ever happening? Can I send you the just the code or do i need to go through the CLA procedure fist? 

Close this, I can live with my fork too.

**Comment by jason0x43** [comment]
For general questions, StackOverflow or the IRC channel are the best ways to go. If you have a bug to report or a feature enhancement to suggest, this is the place to do it.

Do you have a pull request to make, or do you just want to post code to illustrate a potential bug? If it's just example code, feel free to post it, no CLA required. If you want to make a PR, you need to go through the CLA process.

Regarding your question, you can import the 'intern' dependency in your suites, and command line arguments will be available on `intern.args`.

**Comment by gbaumgart** [comment]
great, thanks a lot
