### ISSUE TITLE
error with digdug path when running tests with Intern-TravisCI-Browserstack

### ISSUE THREAD

**Issue by cch5ng** [theintern/intern#622]
OS: Mac OSX 10.10.5
Browser: Chrome 50.0.2661.75
Node: 5.7.1
Intern: v2.2.0
Test case: I'm trying to run predefined tests on BrowserStack via Intern and TravisCI. I'm trying to test them on my forked repo (https://github.com/cch5ng/webcompat.com-1) which is sync'd to Travis.

**TravisCI error:**
FATAL ERROR
`Error: ENOENT, no such file or directory '/home/travis/build/cch5ng/webcompat.com-1/node_modules/intern/node_modules/digdug/browserstack/BrowserStackLocal'
  at Error  <native>
  at Object.fs.chmodSync  <fs.js:948:18>
  at <node_modules/intern/node_modules/digdug/BrowserStackTunnel.js:128:7>
  at <node_modules/intern/node_modules/digdug/node_modules/dojo/Promise.js:235:37>
  at runCallbacks  <node_modules/intern/node_modules/digdug/node_modules/dojo/Promise.js:11:18>
  at <node_modules/intern/node_modules/digdug/node_modules/dojo/Promise.js:188:17>
  at run  <node_modules/intern/node_modules/digdug/node_modules/dojo/Promise.js:131:29>
  at <node_modules/intern/node_modules/digdug/node_modules/dojo/nextTick.js:30:13>
  at process._tickCallback  <node.js:355:11>`

**.travis.yml contains:**
env:
  global:
  - ISSUES_REPO_URI=webcompat/webcompat-tests/issues
  - TRAVIS_NODE_VERSION="0.12.7"
  - SELENIUM_HOST=hub.browserstack.com
  - SELENIUM_PORT=80
  - BS_AUTOMATE_PROJECT="$TRAVIS_REPO_SLUG"
  - BS_AUTOMATE_BUILD="Travis build No. $TRAVIS_BUILD_NUMBER for $TRAVIS_REPO_SLUG"
  - secure: GHdEMwyqEtazcI9tcFKCS7uagsJPPN8tbp52aZztfTQTDV2NZ89FJKqphJIdgTgs...
  - secure: 0enD6VWqOLBqtO8+P8JvTGyLTQwljxtjTGV9yR+J8uFcCDDgQFBWQ2eRbX7xRl6XvcLu...
  matrix:
  - BS_AUTOMATE_OS="OS X" BS_AUTOMATE_OS_VERSION=Lion SELENIUM_BROWSER=firefox SELENIUM_VERSION=24

**intern.js contains:**
    tunnel: 'BrowserStackTunnel',

**Comment by vladikoff** [comment]
Hello @cch5ng, 

```
Error: ENOENT, no such file or directory '/home/travis/build/cch5ng/webcompat.com-1/node_modules/intern/node_modules/digdug/browserstack/BrowserStackLocal'
```

The error means the file is not found, please check make sure you are calling it with the right path. 

If you look here https://github.com/theintern/digdug/blob/1.2.0/BrowserStackTunnel.js the path to the tunnel should be `digdug/BrowserStackTunnel.js` and not `digdug/browserstack/BrowserStackLocal`

**Comment by cch5ng** [comment]
thanks. I'm going to close this. I think possibly I had something missing in my configuration from Intern.js or Travis. I also upgraded my Intern version and right now I am not seeing this error.
