### ISSUE TITLE
Proxy should invalidate code cache if instrumented file changes

### ISSUE THREAD

**Issue by novemberborn** [theintern/intern#624]
I'm using Intern to test some browser code in a [Dojo 2 package](https://github.com/dojo/routing/pull/8). I use `grunt intern:proxy` to start the proxy server, then open <http://0.0.0.0:9000/node_modules/intern/client.html?config=_build/tests/intern> in my browser. My source files are configured to be instrumented.

Due to [this line](https://github.com/theintern/intern/blob/2c0e0a499c548808b9bd177b5dc590bc22f8725b/lib/Proxy.js#L136) once my source file has been instrumented, the proxy will keep serving that version, even if I make changes.

Non-instrumented files are always [read from disk](https://github.com/theintern/intern/blob/2c0e0a499c548808b9bd177b5dc590bc22f8725b/lib/Proxy.js#L179).

I'd expect changes to be reflected when I reload the test runner. One approach would be to always load the file, but hash the filename and the content and use that to see whether the cache is stale. That way the code isn't instrumented unnecessarily, and changes are reflected. This doesn't seem worse in performance than how non-instrumented files are handled.

Caching in [nyc](https://github.com/bcoe/nyc) is implemented in a similar fashion.

Happy to do a PR.

**Comment by jason0x43** [comment]
A simple timestamp check is probably sufficient for Intern's proxy. `_codeCache` could be updated to store objects with timestamps and file data (instead of just the file data), and `_handleFile` could then do a stat check when loading the file.

**Comment by novemberborn** [comment]
@jason0x43 happy to do that as well. Just let me know.

**Comment by jason0x43** [comment]
Go ahead with a PR
