### ISSUE TITLE
TeamCity/Pretty: Wrong numFailedTests when a suite has error at `before`

### ISSUE THREAD

**Issue by LingSpb** [theintern/intern#629]
When a suiteError appears in `before`, currently that suite is considered as 1 FAIL, no matter how many tests are in it. So the output looks strange, like

> Total: [×-   ] 1/4
> Passed: 0  Failed: 1  Skipped: 0

Example:

```
bdd.describe("Suite1", function () {
bdd.before(function () {
throw Error("Suite Error before");
});

bdd.it("Test 1", function () {

});
bdd.it("Test 2", function () {

});

bdd.describe("Suite 1 child", function () {
bdd.it("Test 1 1", function () {

});
bdd.it("Test 1 2", function () {

});
});
});
```

**Comment by LingSpb** [comment]
This issue is quite obvious, I wonder why no one does anything, like, at least marking it as a bug or saying that we will not support?

**Comment by dylans** [comment]
@LingSpb we just have a backlog we're working through, and we hope to get to it soon. We appreciate your patience.

**Comment by LingSpb** [comment]
Thanks for the response. I just wanted to know if we consider it as a bug, so that I will know whether I should spend sometime to investigate this issue on TeamCity :)

**Comment by jason0x43** [comment]
This isn't really a bug. When a suite fails, Intern can't tell how many tests would end up failing because, for example, some might still have passed. Rather than guessing, it just indicates the suite failure and says nothing about the tests, because they never ran.

At the time this behavior was developed we didn't have the concept of explicitly skipped tests, so probably the most correct option would be to mark all the tests in the suite as skipped with a reason of 'suite failure' or something. We also probably shouldn't record the suite failure as a failed test, although some way of indicating a suite failure in the summary would be beneficial.

**Comment by LingSpb** [comment]
I'm fine with any of: 
* (a) skip all the tests in the suite and mark them as skipped
* (b) indicate the suite as failure
* or (c) keep as it is now - consider all the tests as `failed` when the suite fails

In my view,
* with (a): Not hard to implement (I hope), but how about the case the suite fails in `beforeEach`? Currently we mark the test as `failed` when there are errors in `beforeEach`, but I think to make it consistent with `before`, we should mark it as `skipped` too?
* with (b): It sounds a nice idea but not sure it will be good in practice, like how TeamCity (or other CI) will interpret and display the test results?
* with (c): The implementation should be quite similar to (a), except, we don't need to change the code for `beforeEach` since it is marked as `failed` now --> less things to do if we choose (c)

**Comment by sholladay** [comment]
Errors in lifecycle functions should definitely skip the tests but mark the suite as failed.

Marking tests as failed when they didn't run is misleading, especially bad for tooling that tracks test stability / regressions over time. In this case, people get blamed for code they never touched.

By the same token, errors in `afterEach` and `after` should not retroactively mark tests as failed or skipped (for example).

I expect the output here to be:

> Passed: 0 Failed: 0 Skipped: 4

... but with a non-zero exit code and bright red stack trace.
