### ISSUE TITLE
Feature Request: start services while the test runner is working.

### ISSUE THREAD

**Issue by tobiastom** [theintern/intern#633]
It would be nice to be able to start scripts automatically while the test running is doing it's magic. This would for example allow for daemons to be started, and automatically finished once the runner is done. 

Right now I'm doing this with this scripts in Npm, but especially the cleanup is not very nice:

```
"pretest": "npm-run-all pretest:*",
"pretest:server": "php -S 127.0.0.1:9090 Public/index.php & echo $! > server.pid",
"pretest:phantomjs": "node node_modules/.bin/phantomjs --webdriver 127.0.0.1:4444 & echo $! > phantomjs.pid",
"posttest": "npm-run-all posttest:*",
"posttest:server": "kill `cat server.pid` && rm server.pid",
"posttest:phantomjs": "kill `cat phantomjs.pid` && rm phantomjs.pid",
```

**Comment by sholladay** [comment]
I believe you are looking for `config.setup` and `config.teardown`, which are general purpose lifecycle hooks for the testing system.

```javascript
// test/intern.js
define(
    [],
    function () {

        'use strict';

        var proxyPort = 9000;

        return {
            setup : function (executor) {console.log('setup:', executor);},
            teardown : function (executor) {console.log('teardown:', executor);},

            proxyPort : proxyPort,
            proxyUrl  : 'http://localhost:' + proxyPort + '/',

            // Places where unit and/or functional tests will be run.
            environments : [
                { browserName : 'chrome' }
            ],

            // Which unit test files to load. These check our APIs.
            suites : [
                'test/unit/**/*.js'
            ],
            // Which functional test files to load. These check our
            // user-facing behavior.
            functionalSuites : [
                'test/functional/**/*.js'
            ],

            // Ignore some code from test coverage reports, even if it loads
            // during testing. The paths that match this pattern will NOT
            // count against coverage.
            excludeInstrumentation : /^(?:test|node_modules)\//,
        };
    }
);
```

These functions get passed the [Executor](https://github.com/theintern/intern/blob/2c0e0a499c548808b9bd177b5dc590bc22f8725b/lib/executors/Executor.js#L279) instance.

The tricky bit is that if you are using `intern-runner`, the Intern configuration is run in both Node.js and the browser. So you are going to have to run your daemon-killing code conditionally.

You could do the environment detection yourself or rely upon something like `dojo/has` to do it for you. Using that, the daemon killer wouldn't even be loaded except in Node.

```javascript
// test/intern.js
define(
    [
        // Daemon killer as an AMD module.
        'intern/dojo/has!host-node?daemon-killer'
        // Daemon killer as a Node / CommonJS module.
        'intern/dojo/has!host-node?intern/dojo/node!daemon-killer'
        ...
```

**Comment by dylans** [comment]
@tobiastom did @sholladay's suggestion help? If so, I'll assume this is a documentation issue.

**Comment by tobiastom** [comment]
Sorry for the long delay. That is actually what I was looking for. 

Looks like @dylans is correct and it's only missing from the documentation. 

Thanks for your help!

**Comment by jason0x43** [comment]
Descriptions for `setup` and `teardown` have been added to the docs.

**Comment by tobiastom** [comment]
Thank you!
