### ISSUE TITLE
Feature Request: Retry test in browser client

### ISSUE THREAD

**Issue by odoe** [theintern/intern#636]
It would be great if each test in the browser client had a button/link to rerun only that test. Similar to the QUnit client.

This is incredibly useful when working on 1-2 test items at a time.

**Comment by sholladay** [comment]
Out of curiosity, how long do your unit tests take to run? Is it really more convenient to go hunt down a link with your mouse and click it vs Command + Shift + R on your keyboard?

**Comment by odoe** [comment]
All our suites take about 10 minutes. It's not a huge deal while working on a particular feature. I can typically isolate the tests to a single suite. But I still have to test everything to make sure I don't introduce bugs or break anything. That's when it comes in handy to try and nail down those failing tests.

**Comment by RoystonS** [comment]
The other use case for this feature is unrelated to execution speed: if you want to put a breakpoint in your code to see what happens during a failing unit test: re-running all the tests makes that problematic as the breakpoint will be hit for multiple running tests, not just the one you're interested in.  It's very useful to be able to focus in on one or a few unit tests.  Right now we end up going back to the code, commenting out (or skipping) uninteresting tests and running it again to ensure that if the breakpoint is hit, it's only during the interesting test.

**Comment by sholladay** [comment]
> our suites take about 10 minutes

But presumably that is mainly due to functional suites. Yes? The browser client doesn't deal with those. So this would only affect unit tests, which are usually very fast.

> It's very useful to be able to focus in on one or a few unit tests

Amen. I think https://github.com/theintern/intern/issues/514 is a better solution, though. E.g. it is generic (isn't specific to unit tests) and is probably still faster to work with, since you don't have to scroll a huge test result table and hunt for a button.

**Comment by jason0x43** [comment]
This should be pretty easy to do by just giving the report items targeted links. Like, each suite item would have a link like `<existing URL>&suites=<mid>`. Test items would have links pointing to `<existing URL>&suites=<mid>&grep="test id"`. Clicking the link would run only that suite or test. The user could use the browser's back button to run all tests again.

**Comment by jason0x43** [comment]
This was handled by #802, which makes test ID's clickable links in the HTML reporter.
