### ISSUE TITLE
Update CONTRIBUTING.md to link to jQuery CLA

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#639]
We should update that CONTRIBUTING.md to link to the jQuery CLA.  When the re-brand for the foundation arrives, we will likely need to update it again, but since the bot is checking contributions against the jQuery database anyways, we should ensure we point at the right CLA.

Refs #638.

**Comment by jason0x43** [comment]
The link was updated to point to the JS Foundation in 769ba42.
