### ISSUE TITLE
Support for asynchronous before/after and friends

### ISSUE THREAD

**Issue by lawnsea** [theintern/intern#64]
I have some async setup code I need to run before each test. Is this supported in Intern? If so, how do I go about it?

I tried calling `this.async` in `beforeEach`, but it is not available. I also tried returning a `Deferred`, but this had no effect.

**Comment by kospiotr** [comment]
Wouldn't it be more convenient and more consistent to support this.async also in both functions as well. The documentation doesn't say anything about support only promises. Mind that this.async works in all environments, while promises must be additionally configured.
