### ISSUE TITLE
File upload doesn't work in Firefox

### ISSUE THREAD

**Issue by rundmd** [theintern/intern#642]
The following code works fine in Chrome for uploading either photo or video files:
.findByXpath(elements.UPLOAD_PHOTO_BTN_LOCATOR)
    .type(require.toUrl(properties.VIDEO_PHOTO_LOCATION))

However, it results in an error when running in Firefox
firefox 44 on any platform - Video Upload - should upload a video (16.435s)
ElementNotVisible: [POST http://localhost:4444/wd/hub/session/8ee660b7-49e8-4985-9768-f9058ec153d5/element/15/value / {"value":["/var/folders/nz/kpcby4vj3zx7_zk9ptm0qzrcqy_sjg/T/8ee660b7-49e8-4985-9768-f9058ec153d5/upload8328908279087663520file/testvid.mp4"]}] Element is not currently visible and so may not be interacted with

I'm trying to run the test in Firefox 44 using node 4.2.4, Mac OS Yosemite

**Comment by dylans** [comment]
I'm going to move this issue to theintern/leadfoot as this is related to leadfoot.

**Comment by dylans** [comment]
Issue moved to [theintern/leadfoot #82](https://github.com/theintern/leadfoot/issues/82) via [**ZenHub.io**](https://www.zenhub.io/)
