### ISSUE TITLE
Pretty reporter shows incorrect total number of tests

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/intern#647]
When I run tests I see the following from the Pretty reporter:

```<br />Tunnel: Starting<br /><br />Total: [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 75/51<br />Passed: 75  Failed: 0   Skipped: 0<br /><br />Phan 2 XP:  [✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓✓] 75/51<br />``` I have 51 functional tests and 24 unit tests so the total is 75, but the reporter thinks the total is 51.

**Comment by jason0x43** [comment]
Fixed in https://github.com/theintern/intern/commit/7679fed6e015072f5383f1ee2e29c272bc01db93
