### ISSUE TITLE
ie 10, 11 use promise for async test  throw errors

### ISSUE THREAD

**Issue by xiaohulu** [theintern/intern#649]
at intern doc
> Intern always uses Promise objects whenever an asynchronous operation needs to occur

but when i use promise for async test.

```js
define(function (require) {
	var registerSuite = require('intern!object');
	var assert = require('intern/chai!assert');
	registerSuite({
		name: 'hello',
		greet: function () {	
			return new Promise(function (resolve) {
					resolve(); 
		    }).then(function(){
		    	assert.strictEqual("1", "1");
		    });
		}
	});
});
```

test success when use chrome, microsoft edge, or firefox. but when use ie 10 and ie 11 throw error 
```
ReferenceError: 'Promise' is undefined
  at getFocusDomNode: focus in the middle ……
  at Anonymous function  <__intern/lib/Test.js:181:6>
  at Anonymous function  <__intern/browser_modules/dojo/Promise.js:156:33>
  at runCallbacks  <__intern/browser_modules/dojo/Promise.js:19:13>
  at Anonymous function  <__intern/browser_modules/dojo/Promise.js:103:21>
  at run  <__intern/browser_modules/dojo/Promise.js:51:33>
```
the intern version is 3.2.3.
did I miss something? thanks very much.

**Comment by jason0x43** [comment]
IE10 and 11 don't have native Promises, so can't directly call `new Promise`. You can use a Promise library, or you can call [`this.async()`](https://theintern.github.io/intern/#async-tests) in an Intern test to get a Deferred object (it serves a similar purpose to a Promise, but works a bit differently). This also explicitly puts the test in async mode; if the user doesn't return a Promise from the test, Intern will wait for the Deferred created by the `this.async` call to resolve.

```js
define(function (require) {
    // ...
    greet: function () {
        var dfd = this.async();
        someAsyncFunction(function () {
            try {
                assert.strictEqual('1', '1');
                dfd.resolve();
            }
            catch (error) {
                dfd.reject(error);
            }
        )};
    }
});
```

The Deferred object also has some convenience methods that can simplify this a bit.
