### ISSUE TITLE
clickMouseButton(2) doesn't do right click in safari on OS X

### ISSUE THREAD

**Issue by sophiecdd** [theintern/intern#651]
When clickMouseButton(2) on a element it doesn't right click on the element and no context menu pops. 
Selenium version: 2.53.0 
Safari extension is the latest version 2.48
Safari: 9.0.1
OS X: 10.11.1

**Comment by sophiecdd** [comment]
intern version: 3.2.3

**Comment by jason0x43** [comment]
This issue has been moved to the [Leadfoot issue tracker](https://github.com/theintern/leadfoot/issues/88)
