### ISSUE TITLE
[Preliminary] Memory usage spike between 3.1 and 3.2 with npm3

### ISSUE THREAD

**Issue by SlexAxton** [theintern/intern#653]
I'm low on information right now, but wanted to just create an issue in case something was obvious to you kind folks before I tried to repeat outside of our codebase.

We've (Stripe) been running `3.1.1` on npm `2.latest` for a bit, and recently I bumped to latest (a `3.2.x`) *and* npm `3.latest`, and we started crashing jenkins workers reliably (repeatable on our macs as well). This is true for node v4 and v6, as far as I can tell.

If I:

- downgrade npm to `2.latest`
- downgrade intern to `3.1.x`

I don't get crashes anymore (which implies that I probably don't get memory spikes, but it's possible they're just lower).

When I run it locally, my *node* process(es) (whereas normally I assume it's chrome) spike to the max memory limit we set (regardless of what that is, we tried up to 4gb), and then the runtime crashes with a useless error message (just whatever line it happened to crash on).

```
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory
```

 I understand this isn't a lot of information, but perhaps someone else is having the issue, or there's an obvious change that you can think of, I figured I'd report early, and then work on a reduced case (I assume reducing too far solves the issue, though).

**Comment by owiber** [comment]
Some more context, it does successfully run a few tests before pausing and then causing memory to spike (and eventually crash). It also seems to consistently be the same tests that cause this, though I haven't narrowed down what exactly causes it. Something seems to cause a following interaction with leadfoot to break.

Also to clarify, the upgrade to npm3 also equates to blowing away our existing node2 installed modules and reinstalling (so some deps probably got version bumped in that process). My suspicion is potentially some bad interaction between Intern (or its deps) and some other deps causes this since using our npm2 installed modules and _just_ upgrading Intern didn't result in the problem.

**Comment by vladikoff** [comment]
@SlexAxton are you able to debug this using https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27 to pinpoint the problem?

**Comment by vladikoff** [comment]
The debugger needs to be attached to either https://github.com/theintern/intern/blob/master/bin/intern-client.js or https://github.com/theintern/intern/blob/master/bin/intern-runner.js

**Comment by kitsonk** [comment]
The "big" difference I can think of off hand is that npm3 flattens the dependencies and was causing issues with the symbolic linking Intern did to make sure the browser modules were in a consistent "knowable" place.  `browser_modules` were introduced and the sym links moved there.  It could be some interaction there.

If you are upgrading an install, are you `rm -rf node_modules`, or just migrating to npm3?  It might be something with that.

**Comment by owiber** [comment]
The upgrade process is roughly:

```bash
nvm use v6
rm -rf node_modules npm-shrinkwrap.json
npm install # our package.json has ^3.1.1 for intern, so this brings in 3.2.3
```

We experience the issue at that point. If I then `npm install intern@3.1.1`, issue goes away.

Going back to npm2 land, if I just `npm uninstall intern && npm install intern@3.2.3`, the issue is not present.

I'll give attaching a debugger a try.

**Comment by owiber** [comment]
Upon further investigation, while something in Intern 3.2.3 may have exacerbated it, I believe the root cause lies in other dependencies of ours.
