### ISSUE TITLE
TeamCity report looks bad when having nested suites

### ISSUE THREAD

**Issue by LingSpb** [theintern/intern#659]
TeamCity report wraps tests by suite. Currently in Intern we use test/suite id (which are made by adding the parent suite name to the current test/suite name) to display tests in the report. You can see that the reports look quite a mess with repeated information.

![image](https://cloud.githubusercontent.com/assets/4546284/17883867/5e7269b4-6915-11e6-99cc-25d8f213846b.png)

**Comment by jason0x43** [comment]
Fixed by #652
