### ISSUE TITLE
"Gets your coffee"?

### ISSUE THREAD

**Issue by ddavison** [theintern/intern#660]
According to https://theintern.github.io/, theintern is able to fetch your coffee.
![coffee](https://i.imgur.com/rW7JeXk.png)

I've tried calling several different methods with theintern, and nothing is working.

Below is what i've tried:

```javascript
...
this.remote
    .get(require.toUrl("keurig.html"))
    .getCoffee()
    // also tried \/
    .get(coffee)
    .fetchCoffee()
    .bringCoffee()
...
```

but nothing is working!

Do i need to download an external library, or does this come default?

*please hurry, i'm running low on caffeine*

**Comment by dylans** [comment]
👍 You need the live human Intern module, e.g. require(['intern/human'], ...) to enable this feature.

**Comment by jason0x43** [comment]
Cleaning out the queue (but this is quite good :) )...
