### ISSUE TITLE
BDD: mark tests without implementation as pending/skipped

### ISSUE THREAD

**Issue by lenntt** [theintern/intern#661]
(enhancement)

When testing with other BDD frameworks, like cucumber or rspec, I can define a test without implementing it yet. When I run it, the tests are being marked as pending.
It helps describe the tests first, and then implement them one by one.

If I do in Intern, using the BDD test interface, I get an error.

```javascript
bdd.it( "does x");
bdd.it( "does y");
// => Error: self.test is not a function
``` And I think this is simply too much of a hassle when quickly sketching some behavior:

```javascript
bdd.it( "does x", function()
{
this.skip( "TODO" );
} );
bdd.it( "does y", function()
{
this.skip( "TODO" );
} );
```

**Comment by SirLenz0rlot** [comment]
A dirty workaround is to put this on top of my file.

```javascript
var orginalit = bdd.it;
bdd.it = function( description, test )
{
    if ( typeof test === "undefined" )
    {
        test = function() { this.skip( "Pending" ); };
    }
    return orginalit( description, test );
};
```

**Comment by sholladay** [comment]
[`Suite#skip()`](https://theintern.github.io/intern/#skipping-tests) is now available, which should make this way easier.

```js
define(function (require) {
  var bdd = require('intern!bdd');

  bdd.describe('the thing being tested', function () {
    bdd.before(function () {
      this.skip('unwritten test suite');
    });

    bdd.it('an unwritten test');
  });
});
```

I don't use BDD and I haven't actually tried omitting a test function. You may have to supply an empty function for the test.

**Comment by SirLenz0rlot** [comment]
Not being able to ommit the test function is my whole point :)

**Comment by sholladay** [comment]
I just tried the code I sketched out above. It works for me.

```sh
intern run --suites='test/foo'
SKIP: the thing being tested - an unwritten test (unwritten test suite)
0/1 tests failed (1 skipped)
0/1 tests failed (1 skipped)
```

As I said, the trick is the `Suite#skip()`.

**Comment by SirLenz0rlot** [comment]
I was not saying your code doesnt work, I'm saying adding more code, instead of less, when doing BDD, isn't efficient.

**Comment by jason0x43** [comment]
I'm closing this as `xtest/xit` and `xsuite/xdescribe` methods have been added to the tdd and bdd interfaces, which let you mark a suite (empty or otherwise) as intentionally skipped with a minimum of fuss. (#595) This seems preferable to just dealing with undefined suites and tests since they may still be under active development (and broken) even when some content is present.
