### ISSUE TITLE
Running Intern through GruntJS breaking without error showing error, but found it be on process.cwd

### ISSUE THREAD

**Issue by JeffHerb** [theintern/intern#662]
So I'm not 100% sure if this belongs here, but it feels like a good place to start. I'm currently using gruntJS to execute my intern functional tests. After restoring a new desktop to a fresh copy of Window 10 64 bit, I attempted to clone and test my project. The grunt script runs great till I get to the intern tasks. The fail immediately with the error:

```
Warning: Test failure; check output above for details. Used --force, continuing.
```
But there is no errors above

I attempted to do the same to a laptop that runs Linux and the grunt scripts and intern tests run perfectly fine. So I started digging into the node_modules intern folder to see if I could manually output the errors with console. In the process of doing so, I found the error to be:

```
[TypeError: process.cwd is not a function]
```

To be sure it wasn't just the version of node (initialy installed 6.4.0) I downgraded to 4.5.0. Same result.

**Comment by sholladay** [comment]
I have never seen this before. Did you see a browser open up? My first guess is that `process.cwd()` is being run in the browser by accident.

To help debug this, it might be nice to try all three testing modes by themselves and see which ones fail.

1. Unit tests in Node (`intern-client`)
2. Unit tests in browser (`intern-runner`)
3. Functional tests in browser (`intern-runner`)

You can fully disable the unit or functional testing systems to isolate them by setting the respective `suites` or `functionalSuites` array to `null` in the configuration. And in the Grunt task, you can switch between `client` and `runner` using the `runType` [option](https://theintern.github.io/intern/#grunt).

**Comment by JeffHerb** [comment]
@sholladay sorry but no, the browser never opens up. This particular setup does not have an intern-client test, just functional test we send the a local selenium server. Our config file is using `functionalSuites` and the `runner` `runType` in the Gruntfile.

**Comment by sholladay** [comment]
Without going through the motions I described above, it is going to be a bit more difficult to find the culprit.

But either way, your next step should be to use [longjohn](https://www.npmjs.com/package/longjohn) and try to squeeze a stack trace out of it.

I would also run a sanity check on your tests by running:

```
grep -R 'process.cwd' /path/to/test/dir
```

If that comes back with any results, you should consider those files suspect. Post any relevant code if you can.

**Comment by JeffHerb** [comment]
Some progress, not sure what changes, but these errors are showing on a Windows 7 test machine:

![image](https://cloud.githubusercontent.com/assets/1133732/18310873/0ef45f80-74cf-11e6-91f8-83d0b5a95775.png)

**Comment by sholladay** [comment]
Those module load failures would seem to implicate that the problem is with your configuration.

**Comment by JeffHerb** [comment]
So i added basePath to my grunt config and my tests now load! But I now get new additional errors I have never seen before.

Before each set of functional test runs:
![image](https://cloud.githubusercontent.com/assets/1133732/18324969/1e915374-750d-11e6-9eba-27c176fda872.png)

And this new set after:
![image](https://cloud.githubusercontent.com/assets/1133732/18324947/05171a28-750d-11e6-8b91-14d30f4c5f74.png)

**Comment by JeffHerb** [comment]
@sholladay Thanks for your help. I figured out my custom grunt task was causing the newer Suite Error as it generating a empty `suites` array in the `intern.js` config. Currently we are not doing unit testing, just functional. Though this is not really an issue, is it possible to disable that chart at the very end of the functional tests? 

Closing out this issue as it has been fixed. Thanks again!

**Comment by sholladay** [comment]
The table at the end is code coverage. Intern is actually able to determine code coverage for functional tests, so it is still applicable to you. I would recommend leaving it on. But if you really want to, you can set excludeInstrumentation to true.
