### ISSUE TITLE
Add CircleCI reporter or support

### ISSUE THREAD

**Issue by dylans** [theintern/intern#665]
[CircleCi](https://circleci.com/) is a CI service that is [configured via yml](https://circleci.com/docs/configuration/) in a manner that looks very similar to TravisCI.

Let's investigate adding support for CircleCI (would this require a separate reporter, given that we don't really have one for Travis?). Note that CircleCI also has [free plans for open source projects](https://circleci.com/pricing/) so it should be easy to setup/test.

**Comment by sholladay** [comment]
Yes, please!

Sadly, Atlassian has announced that they are [discontinuing Bamboo](https://confluence.atlassian.com/bamboocloud/bamboo-cloud-eol-827125716.html). I am beginning to migrate to Circle CI. I put all of my personal projects on it has been fantastic so far.

**Comment by dylans** [comment]
Perhaps useful information as well at https://discuss.circleci.com/t/the-intern-javascript-tests/4543/2

**Comment by jason0x43** [comment]
Closing this as it's covered by the more general #711.
