### ISSUE TITLE
Remove dependency on `dojo/dojo2`, and move to individual dojo2 packages.

### ISSUE THREAD

**Issue by rishson** [theintern/intern#666]
Enhancement:
Currently we rely upon `dojo/dojo2`. 
Can we move to relying on `dojo/core`, `dojo/shim`, `dojo/has` and `dojo/loader` so that we can remove the `dojo/dojo2` repo?
I know `dojo/dojo2` is marked as deprecated, but its the first package returned when you search of dojo + typescript on [librariesio](https://libraries.io/search?languages&#61;TypeScript&amp;q&#61;dojo) or do a google search for [dojo2](https://www.google.co.uk/search?q&#61;dojo2).

Rationale:
There is so much great work being done on dojo2, that I would not want to think that someone searches for `dojo2` and the first impression that they get, it that the package might be deprecated.

Approach:
If this is alot of work, then as an interim step, can we rename `dojo/dojo2` so it starts to drop out of the search rankings?

**Comment by jason0x43** [comment]
We plan to move to `dojo/core` etc. eventually, but there's not a firm time frame for that. Renaming the experimental dojo2 package should be fine, assuming nothing other than Intern projects are using it.

**Comment by morrinene** [comment]
Per Jason, this is done!
