### ISSUE TITLE
Intern with Webpack

### ISSUE THREAD

**Issue by ala85** [theintern/intern#667]
Hi all, Is it possible to use Webpack (rather than, for instance, requirejs) as provided loader? I'd expect I can pass webpack as loader to the intern.js file:

```
loaders: {
"host-node": "some_webpack_reference",
"host-browser": "some_webpack_path"
}
``` Has anyone achieved that? Thanks in advance.

**Comment by jason0x43** [comment]
Webpack isn't, to my knowledge, a general purpose loader, so it's not something we can use here. However, it's possible that a loader plugin (something like the sample [JSX transpiler](https://github.com/theintern/intern-examples/blob/master/react-example/tests/support/jsx.js)) might work for this use case.

**Comment by ala85** [comment]
Hi, thanks. The problem is that I'd like intern to compile and run the test code using Webpack loaders. For example, in my Webpack configuration, I handle tpl files with an ejs-loader (https://github.com/okonet/ejs-loader) which I would like intern to use it when running the test against those tpl loaders.

From your previous comment, I was expecting a reference of the jsx.js file in the intern loader section, but I havent found it. 

I am new to intern, but my understanding was that I should then create my own loader plugin which then calls Webpack loaders somehow to process the tested code?

**Comment by jason0x43** [comment]
When Intern refers to a `loader`, it means a general purpose AMD-compatible loader. To load other types of things, you can use (or create) [AMD loader plugins](https://dojotoolkit.org/reference-guide/1.10/loader/amd.html#plugins), like the JSX one I liked to earlier. The loader plugin will manage having Webpack do whatever pre-processing is required, and can return a bundled resource.

Note that Intern doesn't have any built in support for resource bundlers like Webpack, so using it will be a bit of a manual process.

How you use your plugin, and how you write your tests, depends on whether they need to run in a browser or can run entirely in Node. Assuming you need to inject code into a browser, you'll need to write [Intern functional tests](https://theintern.github.io/intern/#writing-functional-test). Such a test can load a test page and then interact with it. It would probably be simplest to create a test page that already includes a `<script>` tag referencing a built resource. The test will direct a browser to load the test page _after_ Webpack has built the resource. The test itself might look like:

```js
define(function () {
    // this should use Webpack to build the resource, asynchronously resolving when
    // Webpack is finished
    require('myPlugin!resourceToBuild');

    var registerSuite = require('intern!object');

    registerSuite({
        name: 'my suite',

        'a test': function () {
            return this.remote
                // my_test_page.html has a script tag to load the resource that is built
                // by myPlugin above
                .get('my_test_page.html')
                // do 
        }
    });

**Comment by ala85** [comment]
Thanks. I am trying to create a custom loader, how would I use it in an intern.js configuration?

> loaders: {
>             'host-node': ?,
>             'host-browser': ?
>         }

I am trying to follow the same structure of jsx example.

**Comment by jason0x43** [comment]
Closing this as it's specific to to Intern 3. For Intern 4, the standard solution is to webpack the tests, and then have intern load them as suites (or a single suite if they're in a single bundle).
