### ISSUE TITLE
Feature: search path for --config

### ISSUE THREAD

**Issue by devpaul** [theintern/intern#670]
I'd like to get some feedback on codifying our recommended pattern for creating Intern configurations. In general we recommend that configuration lives at `tests/intern` and `tests/intern-local`. When the `--config` parameter is not set on the command-line (or url) I'd like to see intern look for `tests/intern-local` and then `tests/intern` to attempt to resolve the Intern config.

Essentially I feel if engineers follow our best practices they should be rewarded by needing to type less and the less an engineer has to type the happier they are :).

**Comment by jason0x43** [comment]
`intern-cli` looks for `tests/intern` by default.

**Comment by sholladay** [comment]
I personally use `test/` instead of `tests/`, that was one less thing to type, until `config` became an optional argument. :)

**Comment by devpaul** [comment]
That's great! Can we merge this functionality into Intern?

**Comment by jason0x43** [comment]
This project is where this type of functionality (the user interface) is intended to go. There are no plans to remove `intern-runner` and `intern-client` any time soon, but this project is intended to take their place for day-to-day use.

**Comment by devpaul** [comment]
Closing this. Talked w/ Jason and it sounds like moving forward we'll be following more a Grunt approach w/ a separate cli and application and we'll update documentation to better reflect this.

While we are not going to remove `intern-runner` and `intern-client` anytime soon, we may want to consider adding a deprecation notice to them when users run them directly and point them to `intern-cli` and of course update our documentation to use `intern-cli`.
