### ISSUE TITLE
Firefox with marionette

### ISSUE THREAD

**Issue by rayros** [theintern/intern#675]
`<br />Suite firefox on any platform - unit tests FAILED<br />JavaScriptError: [POST http://localhost:4444/wd/hub/session/b09bd250-7550-4ee8-92bd-93162e49a139/execute / {"script":"return (function getCoverageData(coverageVariable) {\n\t\tvar coverageData = (function () { return this; })()[coverageVariable];\n\t\treturn coverageData && JSON.stringify(coverageData);\n\t}).apply(this, arguments);","args":["<strong>internCoverage"]}] Error: Permission denied to access property "</strong>internCoverage" (WARNING: The server did not provide any stacktrace information)<br />Command duration or timeout: 10 milliseconds<br />Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'<br />System info: host: 'master-Lenovo-B50-80', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.2.0-42-generic', java.version: '1.8.0_101'<br />Driver info: org.openqa.selenium.firefox.MarionetteDriver<br />Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, appBuildId=20160606114238, version=47.0, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, selenium-version=2.53.0, acceptSslCerts=false, browserVersion=47.0, platformVersion=4.2.0-42-generic, name=tests/intern, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=Firefox, takesScreenshot=true, idle-timeout=30, takesElementScreenshot=true, platformName=Linux, device=desktop}]<br />Session ID: ff398f8c-c3f1-4186-a5e2-f9e659ad087d<br />  at runRequest  <../../src/lib-intern/node_modules/leadfoot/Session.js:88:40><br />  at getFinalValue  <../../src/lib-intern/node_modules/dojo/Promise.ts:462:21><br />  at <../../src/lib-intern/node_modules/dojo/Promise.ts:478:10><br />  at <../../src/lib-intern/node_modules/dojo/Promise.ts:393:15><br />  at runCallbacks  <../../src/lib-intern/node_modules/dojo/Promise.ts:11:11><br />  at <../../src/lib-intern/node_modules/dojo/Promise.ts:317:4><br />  at run  <../../src/lib-intern/node_modules/dojo/Promise.ts:237:7><<br /><br />br />  at <../../src/lib-intern/node_modules/dojo/nextTick.ts:44:3><br />  at <em>combinedTickCallback  <internal/process/next</em>tick.js:67:7><br />  at process.<em>tickCallback  <internal/process/next</em>tick.js:98:9><br />  at Command.target.(anonymous function) [as get]  <../../src/lib-intern/node_modules/leadfoot/Command.js:610:11><br />  at ClientSuite.lang.mixin.run  <../../src/lib-intern/node_modules/intern/lib/ClientSuite.js:151:6><br />  at runWithCatch  <../../src/lib-intern/node_modules/intern/lib/Suite.js:389:21><br />  at next  <../../src/lib-intern/node_modules/intern/lib/Suite.js:404:18><br />  at <../../src/lib-intern/node_modules/intern/lib/Suite.js:447:6><br />  at new Promise  <../../src/lib-intern/node<em>modules/intern/browser</em>modules/dojo/Promise.ts:411:3><br />  at runTests  <../../src/lib-intern/node_modules/intern/lib/Suite.js:353:12><br />  at <../../src/lib-intern/node<em>modules/intern/browser</em>modules/dojo/Promise.ts:393:15><br />  at runCallbacks  <../../src/lib-intern/node<em>modules/intern/browser</em>modules/dojo/Promise.ts:11:11><br />  at <../../src/lib-intern/node<em>modules/intern/browser</em>modules/dojo/Promise.ts:317:4><br />No unit test coverage for firefox on any platform<br />firefox on any platform: 0/0 tests failed; fatal error occurred<br />`

**Comment by LingSpb** [comment]
> Marionette and geckodriver are not yet feature complete. This means it does not yet offer full conformance with the WebDriver standard or complete compatibility with Selenium.
> 
> You can track the implementation status of the latest Firefox Nightly on MDN. We also keep track of known Marionette, Selenium, and specification problems in our issue tracker.
> 
> Marionette support is best in Firefox 48 and onwards, although the more recent the Firefox version, the more bug fixes and features. Firefox 47 is explicitly not supported.

**Comment by jonnycornwell** [comment]
I am seeing these errors too with Firefox on Windows 7 (works fine on Mac FF 52.0.2). Not 100% convinced it is an intern problem.

Firefox version: 47.0.2

**Broken versions:**
Selenium server: 3.3.1
GeckoDriver: 0.15.0-x64

**Working versions:**
Selenium server: 2.53.1
GeckoDriver: 0.13.0-x64

Stack trace
`SUITE ERROR
JavaScriptError: [POST http://localhost:4444/wd/hub/session/e626d6d6-30fe-49ad-9c3c-6b96e36f5bce/execute / {"script":"return (function getCoverageData(coverage
Variable) {\n\t\tvar coverageData = (function () { return this; })()[coverageVariable];\n\t\treturn coverageData && JSON.stringify(coverageData);\n\t}).apply(t
his, arguments);","args":["__internCoverage"]}] Error: Permission denied to access property "__internCoverage"
Build info: version: '3.3.1', revision: '5234b32', time: '2017-03-10 09:04:52 -0800'
System info: host: 'WIN-0V8BQ1LLB19', ip: '172.16.231.132', os.name: 'Windows 7', os.arch: 'x86', os.version: '6.1', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.firefox.FirefoxDriver
Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, appBuildId=20161031133903, version=47.0.2, platform=XP, proxy={}, command_id=1, specificat
ionLevel=0, selenium-version=2.53.0, acceptSslCerts=false, browserVersion=47.0.2, platformVersion=6.1, name=testconfig, XULappId={ec8030f7-c20a-464f-9b0e-13a3a
9e97384}, browserName=Firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=Windows_NT, device=desktop}]
Session ID: c5935425-9c5b-4998-a229-765e7bbd9d0e
  at runRequest  <..\..\node_modules\leadfoot\Session.js:92:40>
  at <..\..\node_modules\leadfoot\Session.js:113:39>
  at new Promise  <..\..\node_modules\dojo\Promise.ts:411:3>
  at ProxiedSession._post  <..\..\node_modules\leadfoot\Session.js:67:10>
  at ProxiedSession.execute  <..\..\node_modules\leadfoot\Session.js:686:21>
  at <..\..\node_modules\intern\lib\ProxiedSession.js:95:19>
  at <..\..\node_modules\intern\browser_modules\dojo\Promise.ts:393:15>
  at run  <..\..\node_modules\intern\browser_modules\dojo\Promise.ts:237:7>
  at <..\..\node_modules\intern\browser_modules\dojo\nextTick.ts:44:3>
  at _combinedTickCallback  <internal\process\next_tick.js:73:7>
  at process._tickCallback  <internal\process\next_tick.js:104:9>
  at Command.target.(anonymous function) [as get]  <..\..\node_modules\leadfoot\Command.js:610:11>
  at Suite.<anonymous>  <testsbuild\functional\reporters\ScreenshotReporterTests.js:26:32>
  at Suite.dispatcher  <..\..\node_modules\intern\browser_modules\dojo\aspect.ts:102:35>
  at Promise.catch.suite.async  <..\..\node_modules\intern\lib\Suite.js:237:51>
  at new Promise  <..\..\node_modules\intern\browser_modules\dojo\Promise.ts:411:3>
  at runLifecycleMethod  <..\..\node_modules\intern\lib\Suite.js:219:12>
  at runWithCatch  <..\..\node_modules\intern\lib\Suite.js:349:15>
  at next  <..\..\node_modules\intern\lib\Suite.js:352:17>
  at <..\..\node_modules\intern\browser_modules\dojo\Promise.ts:393:15>
  at runCallbacks  <..\..\node_modules\intern\browser_modules\dojo\Promise.ts:11:11>`

**Comment by jason0x43** [comment]
This looks like https://github.com/mozilla/geckodriver/issues/79, where pre-48 Firefox can't access global variables in `execute` scripts. (Coverage data is retrieved using an `execute` script.)

**Comment by jason0x43** [comment]
I'm going to close this since the problem should be fixed by using FF 48+. Reopen if that doesn't fix the issue.

**Comment by jonnycornwell** [comment]
Moved to 52.1.1, seems to work fine now. Sorry I missed that geckodriver issue :(

**Comment by jason0x43** [comment]
No problem! Glad it's working :)
