### ISSUE TITLE
Windows self tests: FAIL: intern/lib/ReporterManager - add Reporter with output file (2ms)

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/intern#682]
Windows path separator issue.

```
Error: ENOENT: no such file or directory, mkdir 'd:\dev\git_repos\intern\intern\report\dir'
  at Error  <native>
  at Object.fs.mkdirSync  <fs.js:922:18>
  at <lib\ReporterManager.js:144:28>
  at Array.reduce  <native>
  at mkdir  <lib\ReporterManager.js:136:45>
  at ReporterManager.add  <lib\ReporterManager.js:183:29>
  at Test.add Reporter with output file [as test]  <tests\unit\lib\ReporterManager.js:111:20>
  at <node_modules\intern\lib\Test.js:211:24>
  at <node_modules\intern\node_modules\dojo\Promise.ts:393:15>
  at runCallbacks  <node_modules\intern\node_modules\dojo\Promise.ts:11:11>
```

Within this code [lib/ReporterManager.js#L124-L141](https://github.com/theintern/intern/blob/8bdff9104fe17881150f941ec8b12e0830ac0bbf/lib/ReporterManager.js#L124-L141) we see the following values:

```
mkdir report/dir
pathUtil.sep \
currentPath
currentPath report\dir
currentPath dir false
```

So `dirname` comes in using `/`, but `pathUtil.sep` is `\`, thus `dirname` isn't `split()` correctly.

**Comment by jason0x43** [comment]
There were actually a couple of issues here. One was the path issue (the test had hardcoded in a path with '/'), and the other was a race condition that comes up at least on Windows 7. ReporterManager creates its file indirectly using `createWriteStream`, and the test was checking for the presence of the file using `statSync`. I ended up modifying the test to do an initial async `stat` call, and then do the actual checks in the `stat` callback.
