### ISSUE TITLE
Intern silently hangs if a fatal error request generates a repeated sequence id

### ISSUE THREAD

**Issue by andyearnshaw** [theintern/intern#684]
An easy way to demonstrate this issue is to checkout [intern-systemjs-loader](https://github.com/andyearnshaw/intern-systemjs-loader/), edit the file `tests/sample.spec.js` to add an import for a module that doesn't exist, e.g.

``` javascript
import foo from 'bar';
```

Then execute `npm run test` (you need ChromeDriver) and wait for the hang.  https://github.com/andyearnshaw/intern-systemjs-loader/issues/2 explains the reason for the hang.

It looks like 2 files have a `sequence` variable they send to the server: 

```
lib/executors/PreExecutor.js
22:     var sequence = 0;
```

```
lib/reporters/WebDriver.js
16:     this.sequence = 0;
```

Because these each define their own sequence, in this case, `lib/reporters/WebDriver.js` sends one request with sequence 0, followed by `lib/executors/PreExecutor.js` sending another request with sequence 0.

It looks like this sequence var needs to be shared, per session, between both files.

**Comment by andyearnshaw** [comment]
I had a go at fixing this by adding a `sessionData` prop to the object returned by `util`.  However, it seems that, when using a custom loader, the `require` used by `PreExecutor` is different to the `require` used by `WebDriver`.  I guess this is because `PreExecutor` swaps out the loaders but doesn't start everything all over again, keeping its original modules.

This isn't a problem I can solve in intern-systemjs-loader as I don't have access to the original require cache (it's set to undefined before my script runs).  

One possible alternative is to allow fatal errors to be reported without a sequence id.  Since they're fatal, it doesn't seem like the sequence is important here.

**Comment by andyearnshaw** [comment]
Hmm... it looks like https://github.com/theintern/intern/pull/561 already tries to deal with this by ignoring sequence for fatal errors (as per my last comment), but that PR has been awaiting review for a disturbingly long time.  If that's not an acceptable solution, perhaps having a different sequence set each for PreExecutor errors and WebDriver messages would be better?

Is it worth me submitting a separate PR without all the other changes in #561 to get this through?

**Comment by jason0x43** [comment]
Oooooo, that one fell off the table. I'll see about getting that one (or something like it) landed relatively soon.

**Comment by jason0x43** [comment]
Commit 68b20ca introduces some new communication code that ensures PreExecutor and the WebDriver reporter stay in sync, resolving this issue. Feel free to re-open it if the problem comes up again.

**Comment by andyearnshaw** [comment]
Awesome, thanks!
