### ISSUE TITLE
Evaluate what is needed to make ESM and TS support more seamless

### ISSUE THREAD

**Issue by morrinene** [theintern/intern#685]
- Moving Intern's AMD plugins into another format so that they work with ES6
- Support other loaders, such as SystemJS

Related issues

_feel free to remove anything not relevant_

- Feature Request: use SystemJS as the default loader (or at least support it) #615
 - Feature Request: Write tests in ES6 #626
 - Allow loader config in file(s) #493

**Comment by morrinene** [comment]
Some questions:

ESM support/workflow (how it works now)
Work through how ESM is used to author and structure tests
How does Intern 4 load dependencies? How does someone include a loader for testing and/or running their app (is that a relevant question)
Do we need any dynamic behavior to replace loader plugins?
How do we replace usage of dojo/has?
Anything special with how we distribute our packages
Anything special with test authoring structure or workflow to document?

**Comment by devpaul** [comment]
@jason0x43 suggested we could remove much of the need for `has` by creating suite configurations based on the engine in #669.

Intern could use some improvement in selectively running tests. For instance, if you want to conditionally register functional tests based on browser support, e.g. the test machine supports 4k resolution, there is no way to do this and `skip()` only works at the test level. Maybe we could support `skip()` in `before()` so the rest of the suite is skipped and the tests are still reported as part of the run?

Also, I'm all for splitting out Intern into separate packages as long as we still bring it all together under a single `intern` package. What are your thoughts on this?

If the loader is externalized then how will Intern load suites provided to it in it's configuration? To keep it like it is, I assume we'll need a way to dynamically load modules, either by creating a wrapper around popular loaders (dojo-loader, SystemJS, WebPack, etc...) or we'd need to only use Intern programmatically and do away with the configuration-driven approach.

**Comment by bryanforbes** [comment]
> Also, I'm all for splitting out Intern into separate packages as long as we still bring it all together under a single intern package. What are your thoughts on this?

That seems like a good idea: if someone wants a basic/standard install, they can use the `intern` package.

> If the loader is externalized then how will Intern load suites provided to it in it's configuration?

The loader mechanism (which would be inlined into the environment) would read the inlined intern configuration and do its thing. The inlined configuration could (should?) have paths to the files resolved (especially for globs) so the loader doesn't have to do any crazy path manipulation.

> creating a wrapper around popular loaders (dojo-loader, SystemJS, WebPack, etc...)

That's my thought. A small wrapper around the loader API or a hook to tell intern how to inline the loader (or loader script tag) into the environment.

**Comment by morrinene** [comment]
This is done
