### ISSUE TITLE
Use @types for typing management

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#688]
**Issue:**

Intern, in 3.4, is including types in a way that is largely incompatible with other users of TypeScript 2.0.  Because it includes third party types, in its `typings` directory, these get loaded by `tsc` and design time and then conflict with other types that are included.  For example `chai` which is available as `@types/chai` should be used instead of copying the types into the package manually.

**Comment by jason0x43** [comment]
Fixed in 3.4.1

**Comment by michaeljota** [comment]
I use VSCode and I'm not able to use the Typescript definitions with Javascript. This normally work out-of-the-box when types are well placed.

**Comment by dylans** [comment]
@michaeljota I believe they are well placed, and some of us are VSCode users as well. I would check out a config, say from https://github.com/dojo/widget-core/blob/master/package.json , for an example of how we typically use Intern with TypeScript.
