### ISSUE TITLE
Problem loading built versions of some dojo modules such as dojo/cldr/nls/gregorian

### ISSUE THREAD

**Issue by Giwayume** [theintern/intern#694]
Hi! I'm loading Dojo into my `intern.js` config with links pointing to Google's hosted version of Dojo.
```
// ...
loader: {
	packages: [
		{ name: 'dojo', location: 'https://ajax.googleapis.com/ajax/libs/dojo/1.11.2/dojo' },
		{ name: 'dojox', location: 'https://ajax.googleapis.com/ajax/libs/dojo/1.11.2/dojox' },
		{ name: 'dijit', location: 'https://ajax.googleapis.com/ajax/libs/dojo/1.11.2/dijit' }
	]
},
// ...
```
Using a local uncompressed copy of Dojo works. However, when I point to google's version, the **Browser test runner** (intern/client.html) throws the following error when loading the `dojo/cldr/nls/gregorian` (https://ajax.googleapis.com/ajax/libs/dojo/1.11.2/dojo/cldr/nls/gregorian.js) module:

```
TypeError: deps.map is not a function
  at resolveDeps  <PATH_TO/intern/browser_modules/dojo/loader.js:448:16>
  at defineModule  <PATH_TO/intern/browser_modules/dojo/loader.js:462:19>
  at injectModule/onLoadCallback  <PATH_TO/intern/browser_modules/dojo/loader.js:425:17>
  at injectUrl/handler  <PATH_TO/intern/browser_modules/dojo/loader.js:516:65>
```
It looks to me like your loader.js is custom? At least, not the one used in the dojo library.

Edit: I see this is the dojo/dojo2 loader. I also see that this issue is fixed in dojo/loader.

**Comment by Giwayume** [comment]
It looks like your loader is incorrectly mapping the define format:
`define('module/id', { factory: 'object' });`

Also on a side-note, you're missing the `isXdUrl` utility on the local require that `dojo/i18n` uses.
```
mix(mix(result, req), {
	toUrl: function (name) {
		return toUrl(name, module);
	},
	toAbsMid: function (mid) {
		return toAbsMid(mid, module);
	},
        // Add me Add me Add me
	isXdUrl: function(url){
		if(/^\./.test(url)){
			return false;
		}
		if(/^\/\//.test(url)){
			return true;
		}
		var match = url.match(/^([^\/\:]+\:)\/+([^\/]+)/);
		return match && (match[1] != location.protocol || (location.host && match[2] != location.host));
	}
});
```

**Comment by Giwayume** [comment]
The following changes fixed this problem for me:

https://gist.github.com/Giwayume/15227d0ee5cf34a108cf799ed5a62d8f#file-intern-browser_modules-dojo-loader-js-L165-L174

https://gist.github.com/Giwayume/15227d0ee5cf34a108cf799ed5a62d8f#file-intern-browser_modules-dojo-loader-js-L583-L597

**Comment by jason0x43** [comment]
Thanks for the info. Someone else also had a similar issue recently. I've created an issue in the repo for Intern's dojo at https://github.com/dojo/dojo2/issues/24.
