### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by rozaev** [theintern/intern#705]
Hello! You have a typo in documentation.

Here https://theintern.github.io/intern/#interface-benchmark

You can see an example of benchmark tests:

``` JavaScript
define([ 'intern!benchmark' ], function (registerSuite) {
  var async = registerSuite.async; 
  var skip = registerSuite.skip; 

  registerSuite({
    name: 'a suite',

    'basic test': function () {
      // benchmark
    },

    'skipped test': skip(function () {
      // benchmark
    }),

    'async test': async(function (dfd) {
      // benchmark that returns a Promise or resolves the passed in deferred object
    })
  });
}
```

You forgot `);` in the end.

It should be:

``` JavaScript
define([ 'intern!benchmark' ], function (registerSuite) {
  var async = registerSuite.async; 
  var skip = registerSuite.skip; 

  registerSuite({
    name: 'a suite',

    'basic test': function () {
      // benchmark
    },

    'skipped test': skip(function () {
      // benchmark
    }),

    'async test': async(function (dfd) {
      // benchmark that returns a Promise or resolves the passed in deferred object
    })
  });
});
```

By the way: I tried to find documentation source and fix it but i did't succeed. Maybe you should add some link to documentation source for such case?

**Comment by dylans** [comment]
Thanks @rozaev, we'll get this fixed asap (once everyone is back from the holidays). FWIW, the docs live in the [gh-pages branch](https://github.com/theintern/intern/tree/gh-pages).

**Comment by rozaev** [comment]
Okay, here it is:
https://github.com/theintern/intern/pull/707
