### ISSUE TITLE
TypeError: deps.map is not a function

### ISSUE THREAD

**Issue by cowwoc** [theintern/intern#708]
Repro steps:
1. Check out https://github.com/cowwoc/intern-import-urijs
2. Run testcase mentioned in README.md

If this is a bug in the loader, I am looking for a bugfix.
If this is caused by a configuration error on my part, I am looking for the loader to output a clearer error message.

**Comment by jason0x43** [comment]
One of the dependencies in the attached project, punycode, uses an AMD `define` call of the form `define(id, factory)`. This is a case that isn't currently handled by Intern's internal loader.

The easiest fix would be to use an [alternative AMD loader](https://theintern.github.io/intern/#option-useLoader) for tests, such as the normal Dojo loader or RequireJS. For example, to use requirejs, install requirejs as a project dependency and add the following property to the test config:

```js
loaders: {
    'host-node': '../../node_modules/requirejs'
},
```

**Comment by cowwoc** [comment]
@jason0x43 I'll try that, thank you.

Are you able to improve the error message so other users don't trip over this in the future?

**Comment by jason0x43** [comment]
Glad to hear it worked!

Regarding the error message, I'll take a look. It may be as easy to fix the problem as it is to improve the error message.
