### ISSUE TITLE
Recommend use of inspect-process instead of node-inspector

### ISSUE THREAD

**Issue by cowwoc** [theintern/intern#709]
The documentation recommends the use of node-inspector to debug tests. The node-inspector project was recently abandoned in favor of "node --inspect". If you read [this horrible discussion](https://github.com/node-inspector/node-inspector/issues/905) you will see countless bug reports complaining that newer versions contain a major regression that completely prevent its use under Windows. Because the project has been abandoned, no one is answering.

I tried using `node --inspect`. It is (still) a very ugly process from a usability perspective.

I tried https://github.com/jaridmargolin/inspect-process and it was dead simple. As such, please consider updating the documentation to point to this project instead of node-inspector.

**Comment by jason0x43** [comment]
Closing since we now recommend Node's built-in `--inspect` or `--inspect-brk` flags.
