### ISSUE TITLE
Add documentation for intern-cli, intern-a11y, and intern-visual

### ISSUE THREAD

**Issue by dylans** [theintern/intern#715]
The guide has no information about our newest packages ( intern-cli, intern-a11y, and intern-visual )... let's fix that.

**Comment by rozaev** [comment]
Please, do that. I want try to use intern-visual, but there are not much documentation.

**Comment by jason0x43** [comment]
We should add a list of sub-projects/plugins/etc. to the main Intern README, and add full installation and usage docs to the READMEs/repos for each project.
