### ISSUE TITLE
Add Hierarchical Auto Numbering System

### ISSUE THREAD

**Issue by ArtBlue** [theintern/intern#718]
# Feature Request

## The Issue
One of the challenges to referring to specific tests of particular suites, especially from other systems and tools, is that there are no points of reference. _Say I have a suite for **My Feature** and my third test in my second suite_ within it is wrong, is failing or has a false positive of some sort, and I want to refer to it from JIRA or some other application. At present, there is no short way to refer to it. One solution is to manually create a hierarchal pattern in the "defines" and "its" using numbers, letters, roman numerals, etc. for suites and tests within suites respectively (imagine a numbered list with indents).

This is adequate unless one considers that certain suites might be added, others removed or revised, etc. And when that happens, the entire numbering system is thrown off, and needs to be manually revised again. 

## The Suggestion

The feature I have in mind is a numbering system automatically prepended to "describe" and "it" blocks. This would be extremely valuable, especially for in-browser tests. One could easily cite the bad test referred to above like so: 

> "There's something wrong with **My Feature**. Check out test **2c**."

The hierarchy pattern for numbering is secondary. First level could be numbers, second level could be letters, then roman numerals, etc. The short of it is to have automatic points of reference. I hope this is clear enough, but let me know any further clarification is necessary.

**Comment by sholladay** [comment]
> This is adequate unless one considers that certain suites might be added, others removed or revised ...

Right, all it would take is for someone to add a test at the top of the suite and all of your previous test pointers are worse than invalid, they are _valid but incorrect_.

How could this possibly be _not_ brittle without strictly enforced code reviews **and** a convention to always add tests at the bottom?

Another huge issue is that since these are automatically generated at runtime, humans don't have an easy way to lookup a test by its number. Sounds self-defeating for what you are trying to achieve.

FYI, tests do have a [unique ID] at runtime already. You can access it in a test as `this.id`, for example.

**Comment by ArtBlue** [comment]
@sholladay , under the specific use cases you've described the change _would_ be meaningless and counterproductive. I completely agree there. However, I do think there is value in this for short-term references, whether for troubleshooting various tests in large suites when writing tests, or immediate references for tests that need to be looked at in the very near future. Depending on the frequency of changes one makes to a piece of code that requires new/updated tests, this could range from a day to months. My suggestion was not meant to solve the issues you've outlined in your specific scenarios.

**Comment by jonnycornwell** [comment]
I don't see why this needs to be a feature in intern itself, you could easily put a facade in front of the intern API to achieve the same result.

You then have the issue of finding the test in the source code which you will have to find by name anyway as the uid is transient :) (EDIT: as @sholladay mentioned)

e.g. (excuse the typescript example)
<pre>
// my-bdd.ts
import * as bdd from 'intern!bdd';
import Test = require("intern/lib/Test");

let instance = 0;
export function describe(name: string, callback: () => void) {
    // you could of course be smarter and figure out the depth too
    return bdd.describe(++instance + ": " + name, callback);
}

export function it(name: string, callback: (this: Test) => any) {
    return bdd.it(++instance + ": " + name, callback);
}
// etc

// test.ts
import * as bdd from "my-bdd";

bdd.describe("a suite", () => {
    bdd.it("use as normal", () => {

    });
});
</pre>

**Comment by ArtBlue** [comment]
@jonnycornwell , fair enough. Thanks for the consideration and the suggestion.
