### ISSUE TITLE
Add LICENSE, update copyright on website

### ISSUE THREAD

**Issue by dylans** [theintern/intern#720]
Need to make a few updates to https://github.com/theintern/theintern.github.io

* Update copyright year to 2017
* Update Dojo Foundation to JS Foundation
* Add a license file, similar to https://github.com/dojo/dojo-website/blob/master/LICENSE.txt

**Comment by jason0x43** [comment]
Should the license file point to the Intern license rather than duplicating its content? The content is mostly the same (New BSD verbiage), except that the copyright in the Intern LICENSE has more history.

**Comment by jason0x43** [comment]
Also, the dojo license still mentions the "Dojo Foundation"; is that intentional?

**Comment by dylans** [comment]
> Also, the dojo license still mentions the "Dojo Foundation"; is that intentional?

Not intentional

> Should the license file point to the Intern license rather than duplicating its content?

I believe we need to include the license itself.

**Comment by jason0x43** [comment]
> I believe we need to include the license itself.

Should we modify or exclude the copyright line since the various Intern projects have different copyrights (e.g. Intern is (c) 2012-2013 Colin, 2013-2017 SitePen, while Leadfoot is (c) 2014-2017 SitePen)?

**Comment by dylans** [comment]
One strategy is to just get rid of the year in the copyright statement. The main reason the years are different is based on the start year of the project, so if we keep the years, the end year should all be 2017. I believe for Intern both Colin and I have completed a copyright assignment, so it's probably best to rewrite it as something like this:

```(c) [JS Foundation](http://js.foundation/), [SitePen](https://sitepen.com/), Colin Snover, and contributors.```

**Comment by jason0x43** [comment]
Updated in https://github.com/theintern/theintern.github.io/commit/d95c67b5ef3216781c913f8eba1f627f4821f729
