### ISSUE TITLE
Leadfoot's execute typings should have an optional argument

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#722]
The typings for [`Command.execute()`](https://github.com/theintern/intern/blob/5aadf3463bc0d338e6922b16e449a3e01291abf0/typings/leadfoot/leadfoot.d.ts#L751) should have `args` be an optional second argument.

**Comment by jonnycornwell** [comment]
Do have a monkey patch for this at the moment, same applies for [Command.executeAsync](https://github.com/theintern/intern/blob/5aadf3463bc0d338e6922b16e449a3e01291abf0/typings/leadfoot/leadfoot.d.ts#L775) :)

**Comment by jason0x43** [comment]
They are optional in master, and I can push out a 3.4 update with that, too.

**Comment by jason0x43** [comment]
This is fixed in 3.4.4.
