### ISSUE TITLE
Is source maps supports?

### ISSUE THREAD

**Issue by rozaev** [theintern/intern#723]
Hello!
Here in documentation: https://theintern.github.io/intern/#what-is-intern, I read:

>  Its built-in support for source maps makes it uniquely well-suited for developers that compile their code to JavaScript from another language, such as TypeScript, or that run tests against production-ready built/minified code.

I tried to check: is sourceMaps actually works? I create a small example with babel and source maps:
https://github.com/rozaev/intern-examples/tree/source-map-question/source-map-support-example

But In coverage report I see transpiling code, not the origin one. What I do wrong? I expect that I see a new ES2015 code in code coverage report.

Hot-to reproduce:
``` bash
git clone https://github.com/rozaev/intern-examples.git

cd intern-examples/source-map-support-example

npm install && npm run build && npm test
```

Then, open code coverage report.

**Comment by dylans** [comment]
It should work when using [remap-istanbul](https://github.com/SitePen/remap-istanbul) . This extension is needed until we switch to a newer version of Istanbul that will support source maps.

**Comment by rozaev** [comment]
Thank you, I try do something with that.

**Comment by rozaev** [comment]
@jason0x43 Hello Jason! The intern 4 was released several days ago. This feature works in intern 4 or not? I want this feature because in our company we use babel and it's will be good if we generate coverage report by non-transpiled code. If it's not work I can try to help with that.

**Comment by jason0x43** [comment]
Source map support should work out-of-the-box with babel and TypeScript transpilation. It should also work with webpack using [istanbul-loader](https://github.com/theintern/istanbul-loader)). If you find cases where it doesn't, let us know!

**Comment by rozaev** [comment]
Okay, I will re-check it.
