### ISSUE TITLE
Source Maps/Istanbul

### ISSUE THREAD

**Issue by morrinene** [theintern/intern#726]
Evaluate current state of istanbul release, adjust on our end if needed.  Review & Implement with Source Maps

**Comment by jason0x43** [comment]
The standard usage model for istanbul is now to use the [nyc](https://github.com/istanbuljs/nyc) command line tool. That appears to work with SystemJS and pure Node-based projects out-of-the-box. For remote suites we may be able to use `nyc` to instrument the code and collect the coverage afterwards, use `istanbul-api`.

**Comment by jason0x43** [comment]
No, of course it's not that easy. `nyc` doesn't appear to work with SystemJS, which the self-tests are currently using.

**Comment by jason0x43** [comment]
We need to support instrumentation in several situations:

* Node loader
* An AMD loader in Node (which should default to the Node loader in a Node environment)
* SystemJS in Node
* Anything in the browser

`nyc` can handle the Node loader case, or we can use the underlying `istanbul-lib-hook` and `istanbul-lib-instrument` libraries similarly to how Intern 3 does. SystemJS will probably need a transformer. The browser situation could be handled via the Intern proxy as it is now, or we could use `nyc` to pre-transform the files to be tested and then serve those.

**Comment by jason0x43** [comment]
Using `nyc` to pre-process the code has definite possibilities. It's usage is a bit weird, and it is essentially a build step (which I was trying to stay clear of as a base requirement for testing), but it has the advantage of working no matter how a module is loaded.

**Comment by jason0x43** [comment]
Ok, this seems to be in a good state, at least for the time being. Coverage basically works like it did in Intern 3: Intern adds hooks to the Node loader in Node, and instruments files in Server when they're requested by a browser client. Source-map support is now built in, and I've tested it with TypeScript and ES6 + babel projects.

One new feature is a `functionalCoverage` option. Coverage for functional tests can be disabled by setting `functionalCoverage: false` in a test config.
