### ISSUE TITLE
 Error: Permission denied to access property "_wrapped"

### ISSUE THREAD

**Issue by kimek** [theintern/intern#738]
I've spend some time on this issue as I am new to theintern.js
I just want to point out that Firefox Selenium driver have issue on submit Windows/Firefox from version 48 above, selenium 2.4-3.4 , gecko 1.4-1.6.1.
Tested on local selenium, browserstack, saucelabs. 
Ticket was rised here https://github.com/mozilla/geckodriver/issues/438.

It's hard for me to say is this issue is caused by lack of 'bulletproofing' from theintern or it's just another driver/version issue.

Writing this post to inform that it's better to use Firefox 47 for testing.

I will try to update this when I will know more.

**Comment by jason0x43** [comment]
Could you post a test project somewhere that reproduces the issue?

**Comment by jason0x43** [comment]
Could you post a test project somewhere that reproduces the issue?

**Comment by kimek** [comment]
from:  https://github.com/mozilla/geckodriver/issues/438

andreastt commented an hour ago

@kimek I’m afraid Firefox 48 isn’t supported. Please consider using Firefox Nightly with geckodriver whilst it is in a pre-release stage.


One of examples is random site on backbone : 
define([
	'intern!object',
	'intern/chai!assert',
	'require',
	'intern/dojo/node!leadfoot/Command',
    'intern/dojo/node!leadfoot/helpers/pollUntil',
    'intern/dojo/node!leadfoot/Session',
    'intern/dojo/node!leadfoot/keys'
], function (registerSuite, assert, require, Command, pollUntil, session, keys) {
	
	registerSuite({
		name: 'Pet Quote (functional)',

		// element_visible_by_query_selector: function(query) {
		//         return function(query) {
		//             elem = document.querySelector(query);
		//             if (!elem) { return null; }
		//             return (elem.offsetWidth > 0 && elem.offsetHeight > 0) ? elem : null;
		//         }  
		//     },

		// .then(pollUntil(util.element_visible_by_query_selector(), ['<element>'], 22000))

		setup: function () {
	      app = {
	        price: 0,
	        benefit: 0,
	        fullPrice: 0
	      };
	    },

		'submit form': function () {

			return this.remote
				.get('https://words-keeper.com/signup')
				// .setWindowSize(1200,1000)
				// .getWindowSize().then(function (val) {
				//     assert.equal(val.width, 1200, val);
				//  })
				.findByCssSelector('.email-signup-link > a:nth-child(1)')
					.click()
					.end()
				.sleep(2000)
			    .findByCssSelector('#signup-button')
					.submit()
					.end()
				.sleep(3000)
				
				
				;
		}
	});
});

define([ 'intern' ], function (intern) {
	var config = {
		proxyPort: 9000,

		proxyUrl: 'http://localhost:9000/',

		capabilities: {
		    fixSessionCapabilities: false,
		  },

		environments: [ 

			{ 
				browserName: 'firefox',
				version: ['47'],
				platform: 'Windows 7'
			},
		],

		maxConcurrency: 3,

		tunnel:'SauceLabsTunnel',

		tunnelOptions: {
		    verbose: true,
		  },

		loaderOptions: {

			packages: [
			

			]
		},

		functionalSuites: [ 
			// 'tests/functional/Todo', 
			'tests/functional/Recorder' 
		],

		defaultTimeout: 5000000,

		excludeInstrumentation: true 
	};

	if (intern.mode === 'runner') {
		config.reporters = [ 'Runner', 'Console', 'LcovHtml' ];
	}

	return config;
});


This works on 47 not on version above. Just informing about that as I spend days to crack on what's going on..

**Comment by jason0x43** [comment]
Closing this as geckodriver has been out and usable for a while at this point
