### ISSUE TITLE
Unhandled Promise Rejection

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#742]
Would it make sense for the intern client to register for unhandled promise rejections and treat them as test errors?  I have seen several instances where developers forget to return their promises from a function, get a passed test, but actually are missing the fact that there is an unhandled promise rejection.

**Comment by jason0x43** [comment]
Intern 4 registers handlers for unhandled promise rejections and uncaught errors and emits an error event. This doesn't cause individual tests to fail, but it does at least let the user know something weird happened.

**Comment by kitsonk** [comment]
Ok, I will close this then.  Thank you.
