### ISSUE TITLE
Running intern fails with npm 5.0.0 in istanbul dependency

### ISSUE THREAD

**Issue by Kiechlus** [theintern/intern#746]
`"intern": "^3.0.6",` In my package.json
`"istanbul": "0.4.1"` From intern package.json

Install latest npm (version 5.0.0 atm.)
> `sudo npm i -g npm` 

Install dependencies of my intern project

> `rm -r /node_modules`
> `npm i` 

Running tests fails somewhere in isanbul
> ./chromedriver --log-path=chromedriver.log --port=4444 --url-base=wd/hub & NODE_ENV=test node_modules/.bin/intern-runner config=config/intern

`Error: Cannot find module 'has-flag'
  at Function.Module._resolveFilename  <module.js:470:15>
  at Function.Module._load  <module.js:418:25>
  at Module.require  <module.js:498:17>
  at require  <internal/module.js:20:19>
  at Object.<anonymous>  <node_modules/istanbul/node_modules/supports-color/index.js:2:15>
  at Module._compile  <module.js:571:32>
  at Object.Module._extensions..js  <module.js:580:10>
  at Module.load  <module.js:488:32>
  at tryModuleLoad  <module.js:447:12>
  at Function.Module._load  <module.js:439:3>
  at Module.require  <module.js:498:17>
  at require  <internal/module.js:20:19>
  at Object.<anonymous>  <node_modules/istanbul/lib/report/common/defaults.js:7:21>
  at Module._compile  <module.js:571:32>
  at Object.Module._extensions..js  <module.js:580:10>
  at Module.load  <module.js:488:32>
`

**After downgrading back to npm@4.6.1 it works again as it did always before.**

**Comment by jason0x43** [comment]
Try removing your `~/.npm` directory and reinstalling. I experienced a similar issue with a different package just after upgrading to npm 5, and clearing the cache and re-running `npm install` fixed it. The new cache structure is incompatible with the old, and npm 5 doesn't seem to behave well with bits of the old cache hanging around.

**Comment by Kiechlus** [comment]
I wait till I update to 5.0.0 again (way back was not too comfortable).
