### ISSUE TITLE
Intern in-browser

### ISSUE THREAD

**Issue by devpaul** [theintern/intern#747]
I am trying to load intern programmatically into the browser and want to be able to programmatically configure it and start tests. My use case is loading intern w/o a package.json; e.g. to use in on jsfiddle.

Sample Code:

tests.html
```
<!DOCTYPE html>
<html lang="en">
<head>
	<title>Unit Tests</title>
	<script src="https://unpkg.com/intern@4.0.0-alpha.4/browser/intern.js"></script>
</head>
</html>
```

Results in an error because it tries to load and parse a (non-existent) config

> GET http://localhost:63342/intern.json 404 (Not Found)

**Comment by jason0x43** [comment]
There's this now: https://github.com/theintern/intern/blob/master/docs/how_to.md#run-intern-in-my-own-test-page-in-a-browser.

**Comment by jason0x43** [comment]
There's https://github.com/theintern/intern/blob/master/tests/example.browser.html now, which can be modified to use the unpkg artifact.

**Comment by jason0x43** [comment]
I believe this has been addressed, but feel free to reopen if not.
