### ISSUE TITLE
Update the Qunit interface for Intern 4

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#748]
The QUnit interface needs to be ported to intern 4 and the self tests need to be updated. I started doing that in the qunit-update branch, but didn't get terribly far.

**Comment by bryanforbes** [comment]
I've moved the work for this over to [a plugin](https://github.com/bryanforbes/qunit-plugin) and started updating it to the QUnit 2.0 API.

**Comment by jason0x43** [comment]
I'm closing this since no one has seemed to miss this interface. (At least, I don't recall anyone asking for it since Intern 4 has been out.)
