### ISSUE TITLE
Safari and iOS unit tests hang on SauceLabs

### ISSUE THREAD

**Issue by wkeese** [theintern/intern#752]
For some reason, my unit tests hang when running against Safari or iOS on SauceLabs.   Other combinations work fine, such as SauceLabs + Firefox + macOS,  or running against Safari locally.

Actually, "hang" isn't quite the right word.  The tests run on SauceLabs but the results don't get sent back to the client (ie the intern process).  I noticed Safari is getting a 500 error apparently trying to send back the results:

<img width="1123" alt="screen shot 2017-06-09 at 5 01 24" src="https://user-images.githubusercontent.com/69599/27000997-f6a320b0-4df9-11e7-893f-201e652f6bf0.png">

It doesn't seem like a problem with a particular unit test; I can all of my unit tests individualy, but it's just when they are put all together that they overload something.

## Expected behavior

Results should be printed to console.

## Current behavior
Tests are running but results aren't printed to console.  Eventually test fails with timeout.

## Steps to reproduce (for bugs)

1. Get the code:

```
$ git clone https://github.com/ibm-js/deliteful.git
$ cd deliteful
$ npm install
$ bower install
```

2. Edit tests/intern.js to specify platform as `{ browserName: "safari", version: "9", name : "deliteful"}` (or safari 10), and set ` functionalSuites: [  ]`. 

3. Run test:

```
$ grunt test:remote
```

## Environment
Intern version: 3.4.5
Node version: 4.2.6
NPM version: 3.7.1
Browser version: Safari 10

**Comment by dylans** [comment]
fwiw, we've had similar issues the past couple of months with Sauce Labs when testing Dojo 2, and Sauce Labs is aware of the issue and working on it by trying to improve performance and stability of Appium. For now, we have switched our tests over to use BrowserStack which resolved the issue for Dojo 2 at least.

**Comment by jason0x43** [comment]
Closing this because it's Intern 3 specific and there have been quite a few changes to the webdriver code
