### ISSUE TITLE
v4.0a this.remote not exposed in functional tests

### ISSUE THREAD

**Issue by geuis** [theintern/intern#757]
## Expected behavior
According to the docs for v4.0a, `this.remote` should be exposed in a functional test.

## Current behavior
`this.remote` is undefined. `this` is also an empty object.

## Steps to reproduce (for bugs)
A reproducible demo is available at https://github.com/geuis/intern-remote
Run `npm run intern` or `yarn intern`.

## Environment

Intern version: 4.0.0-alpha.5
Node version: 8.1.2
NPM version: 5.0.3
Browser version: Chrome latest

**Comment by jason0x43** [comment]
The problem is that the test is defined using an arrow function, so it can't access `this.remote`. Use a regular function statement or method definition:

```js
'basic test'() {
  console.log('##', this.remote); // undefined
  return this.remote.get('http://localhost:3000');
}
```

**Comment by jason0x43** [comment]
Improved support for arrow functions was added in 4.0.0-alpha.6. Tests are now passed the test object as the first parameter.

```js
'basic test': (test) => {
    // use test.remote
}
```
