### ISSUE TITLE
Headless Chrome Support?

### ISSUE THREAD

**Issue by jonny-improbable** [theintern/intern#758]
## Expected behavior
Be able to execute tests under a headless Chrome instance captured by Selenium (see [yukinying/chrome-headless-browser-docker](https://github.com/yukinying/chrome-headless-browser-docker))

## Current behavior
Tests fail to startup with default configuration; upon removing the `environment=` flag, they connect to selenium but fail with a (`cannot get automation extension` error)

## Steps to reproduce (for bugs)
```
# Start chromeheadless & selenium on port 4444
docker run -it --rm --name chrome --shm-size=1024m --cap-add=SYS_ADMIN \
  -p=127.0.0.1:4444:4444 \
  yukinying/chrome-headless-browser-selenium

# Run intern tests:
intern-runner config=intern-config environments=[{browserName:'chrome'}] tunnel=NullTunnel tunnelOptions=''
```

## Environment

Intern version: intern 3.4.4
Node version: 4.7.2
NPM version: 2.5.11
Browser version: N/A (see Docker image)

**Comment by jason0x43** [comment]
Try setting `fixSessionCapabilities` to false.

```js
environments: [
  {
    browserName: 'chrome',
    chromeOptions: { args: [ 'headless', 'disable-gpu' ] },
    fixSessionCapabilities: false
  }
]
```

It looks like some of Leadfoot's feature tests aren't playing well with headless Chrome.

**Comment by dylans** [comment]
We should verify this works as expected and add to the Intern documentation.

**Comment by jason0x43** [comment]
It does work (even feature tests work now). I [added a section](https://github.com/theintern/intern/blob/master/docs/how_to.md#run-tests-with-headless-chrome) to the [How To](https://github.com/theintern/intern/blob/master/docs/how_to.md) doc.
