### ISSUE TITLE
The link to the sample configuration file on this page is dead

### ISSUE THREAD

**Issue by DanAtShenTech** [theintern/intern#759]
https://theintern.github.io/intern/#common-config

**Comment by kitsonk** [comment]
Works for me... just checked.

**Comment by kitsonk** [comment]
Sorry, it is a 404.

**Comment by jason0x43** [comment]
Hmmm...it seems to be up now. Possibly just a github.io fluke.

**Comment by jason0x43** [comment]
Ah, it's not. I see.

**Comment by jason0x43** [comment]
Fixed in https://github.com/theintern/intern/commit/8c026b9e2c775e77fd16d2b968dbb7225ad22a44. Thanks!
