### ISSUE TITLE
Add support for .env to load environment variables

### ISSUE THREAD

**Issue by geuis** [theintern/intern#762]
In setting up a configuration json document for intern@v4, there [is documentation](https://github.com/theintern/intern/blob/4.0.0-alpha.5/docs/configuration.md#environment-variable) about using INTERN_ARGS to load environment variables.

This is especially useful for storing credentials and other sensitive information needed for authentication to remote services without committing them to git.

However, since intern.json is just a document there isn't a direct way to store those credentials in a .env file such as used with [dotenv](https://www.npmjs.com/package/dotenv), and then have intern use those.

An example of where this would be useful is how we are setup.

In our package.json scripts section, we have defined the various commands we use in both local development and production deployment. We use `yarn run <cmd>` to execute them. For example:

```
{
  "scripts": {
    "build": "webpack --env=prod",
    "test:unit": "jest",
    "test:integration": "wdio test/wdio.config.js"
  }
}
```

We use dotenv extensively in our projects so that we can store various credentials in a local .env file and not have them committed, nor have to worry about setting environment variables in our shells manually.

I think it would be very useful if intern looked for a local .env (possibly just use the dotenv package). This would avoid the need to write additional wrapper code to make INTERN_ARGS available.

**Comment by jason0x43** [comment]
`INTERN_ARGS` is actually just a way to provide normal Intern arguments through an environment variable rather than a way for Intern to deal with environment variables in general.

That said, you should be able to load `node_modules/dotenv/config` as a plugin (in `plugins`, or `node.plugins` if your config is also used by browser tests):

```js
{
  "plugins": "node_modules/dotenv/config"
}
```

**Comment by geuis** [comment]
The problem I'm seeing is that there's not an easy (apparent) way to include environment variables into the config file, namely because its a static json document. Its probable I'm still missing something from the project documentation though. 

I tried your suggestion, loading dotenv as a plugin, in combination with adding the following as an environment variable in the .env file (real credentials omitted to protect the innocent). No bueno though.

```
INTERN_ARGS="tunnelOptions='{\"username\":\"geuis-sauce\", \"accessKey\":\"abcdefg-0000-1111-2222-abcdefghijk\"}'"
```

That's a kind of an awkward way of loading environment variables in any case, not a pattern I've really seen in any other projects.

What would actually be really cool in the config json doc would be some kind of marker for a property that gets parsed as "replace with matching environment variable". Might look something like this:

```
{
  "description": "Intern testing config",
  "bail": false,
  "connectTimeout": 30000,
  "debug": false,
  "maxConcurrency": 4,
  "functionalSuites": "intern-tests/functional/**/*.js",
  "tunnelOptions": {
    "username": "@TUNNEL_USERNAME",
    "accessKey": "@TUNNEL_ACCESSKEY"
  }
}
```

So when `intern.json` gets loaded, `@TUNNEL_USERNAME` and `@TUNNEL_ACCESSKEY` get replaced by the matching values environment variables. Config might then fail with an error if any are missing, for example.

**Comment by jason0x43** [comment]
The tunnel classes actually have [their own support for environment variables](https://theintern.github.io/digdug/) (they're the only things where that generally comes up).

**Comment by jason0x43** [comment]
Is there another use case for this besides the tunnel variables? Otherwise I think we can close it for now.
