### ISSUE TITLE
Make PRs for custom types with DefinitelyTyped

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#765]
Intern 4 currently includes custom types for the istanbul-* projects and shell-quote. Make PRs for these with DefinitelyTyped.

- [x] istanbul-lib-coverage
- [x] istanbul-lib-hook
- [x] istanbul-lib-instrument
- [x] istanbul-lib-report
- [x] istanbul-lib-source-maps
- [x] istanbul-reports
- [x] shell-quote

**Comment by bcoe** [comment]
👋 hey, I'm one of the core contributors to Istanbul. Thanks for pulling these type definitions together. I'd love for these to be included in DefinitelyTyped (there aren't any competing definitions that I know of, certainly not any that are part of the project itself).

**Comment by nicojs** [comment]
Types can be found here: https://github.com/theintern/intern/tree/master/types

**Comment by jason0x43** [comment]
@nicojs Yes, they just need some cleanup and tests to go from [the single files in Intern](https://github.com/theintern/intern/tree/4.0.0-alpha.13/types/shell-quote) to more complete [type sets for DT](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/040774f26c8392a610a7302ff02840b39959dcf8/types/shell-quote).

**Comment by nicojs** [comment]
🍾 Thanks for providing the types to DT! 💐
