### ISSUE TITLE
Improve usage with bundlers

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#769]
Requirements:

* Support building intern + app code into one or more bundles. This essentially works now by having a test harness require `intern/browser/remote.js`, but there should be an easier way to create a more targeted bundle.
* Provide a mechanism to load the bundle for webdriver-driven unit tests. Currently RemoteSuite always loads `__intern/browser/remote.html`, which loads intern's `remote.js`.
* Provide a plugin or other mechanism to allow bundler to process Intern suite lists.
* Provide a good flow for instrumenting test code. Currently if intern loads an alternative js file in its WebDriver-driven unit tests (such as a bundle), the file will be instrumented. This isn't what we want if intern is bundled in there, too.
* Ensure that intern properly utilizes source maps to resolve error stack and coverage data from bundles.

**Comment by jason0x43** [comment]
An example is in https://github.com/theintern/intern-tutorial/tree/completed

**Comment by rorticus** [comment]
We ended up using an istanbul loader for cli-build-webpack. It'd be great if this could be eventually moved to intern.

https://github.com/dojo/cli-build-webpack/pull/209/files#diff-5b1a9474f4a8448cf3b8714376f9c9fa

**Comment by jason0x43** [comment]
I extracted the loader into a standalone project at https://github.com/jason0x43/istanbul-loader. We can flesh that out and then move it under `@theintern`.

**Comment by jason0x43** [comment]
The loader is now in https://github.com/theintern/istanbul-loader. A beta is available on npm at `@theintern/istanbul-loader@next`

**Comment by jason0x43** [comment]
Usage with bundlers (at least webpack) is now something like this (assuming the user is running tests in a browser using webdriver):

1. Build a bundle of tests + app code. If code coverage is desired, use https://github.com/theintern/istanbul-loader.
2. Add the bundle in to `browser.suites` lists in `intern.json`
3. Ensure a tunnel and environment are set in `intern.json`
4. Run intern

Nothing special is needed to load the tests since they'll just register on the global executor. Istanbul-loader manages bundle instrumentation and source mapping.

**Comment by jason0x43** [comment]
With istanbul-loader and an example workflow, this is good enough for now.
