### ISSUE TITLE
TypeError: Feature "es6-symbol" exists and overwrite not true

### ISSUE THREAD

**Issue by mo** [theintern/intern#773]
$ node --version
v8.1.4
$ npm init -f
$ npm install --save intern@next
$ echo '{
  "suites": "tests/unit/**/*.js"
}' > intern.json
$ ./node_modules/.bin/intern
/home/molsson/src/trying-out-web-e2e-frameworks/example-tests/intern/node_modules/@dojo/has/has.js:155
            throw new TypeError("Feature \"" + feature + "\" exists and overwrite not true.");
            ^

TypeError: Feature "es6-symbol" exists and overwrite not true.
    at Object.add (/home/molsson/src/trying-out-web-e2e-frameworks/example-tests/intern/node_modules/@dojo/has/has.js:155:19)
    at /home/molsson/src/trying-out-web-e2e-frameworks/example-tests/intern/node_modules/@theintern/leadfoot/node_modules/@dojo/shim/support/has.js:28:11
    at Object.defineProperty.value (/home/molsson/src/trying-out-web-e2e-frameworks/example-tests/intern/node_modules/@theintern/leadfoot/node_modules/@dojo/shim/support/has.js:3:17)
    at Object.<anonymous> (/home/molsson/src/trying-out-web-e2e-frameworks/example-tests/intern/node_modules/@theintern/leadfoot/node_modules/@dojo/shim/support/has.js:9:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)

**Comment by mo** [comment]
Also:

$ npm ls
intern-testing@1.0.0 /home/molsson/src/trying-out-web-e2e-frameworks/example-tests/intern
└─┬ intern@4.0.0-alpha.10
  ├── @dojo/core@2.0.0-beta2.2
  ├── UNMET PEER DEPENDENCY @dojo/has@2.0.0-beta2.2
  ├── @dojo/interfaces@2.0.0-beta2.2
  ├── UNMET PEER DEPENDENCY @dojo/shim@2.0.0-beta2.2
  ├─┬ @theintern/dev@0.4.3
  │ ├─┬ chalk@2.0.1
  │ │ ├─┬ ansi-styles@3.1.0
  │ │ │ └─┬ color-convert@1.9.0
  │ │ │   └── color-name@1.1.3
  │ │ ├── escape-string-regexp@1.0.5
  │ │ └─┬ supports-color@4.2.0
  │ │   └── has-flag@2.0.0
  │ ├─┬ chokidar@1.7.0
  │ │ ├─┬ anymatch@1.3.0
  │ │ │ ├── arrify@1.0.1
  │ │ │ └─┬ micromatch@2.3.11
  │ │ │   ├─┬ arr-diff@2.0.0
  │ │ │   │ └── arr-flatten@1.1.0
  │ │ │   ├── array-unique@0.2.1
  │ │ │   ├─┬ braces@1.8.5
  │ │ │   │ ├─┬ expand-range@1.8.2
  │ │ │   │ │ └─┬ fill-range@2.2.3
  │ │ │   │ │   ├─┬ is-number@2.1.0
  │ │ │   │ │   │ └── kind-of@3.2.2 deduped
  │ │ │   │ │   ├─┬ isobject@2.1.0
  │ │ │   │ │   │ └── isarray@1.0.0 deduped
  │ │ │   │ │   ├─┬ randomatic@1.1.7
  │ │ │   │ │   │ ├─┬ is-number@3.0.0
  │ │ │   │ │   │ │ └─┬ kind-of@3.2.2
  │ │ │   │ │   │ │   └── is-buffer@1.1.5 deduped
  │ │ │   │ │   │ └─┬ kind-of@4.0.0
  │ │ │   │ │   │   └── is-buffer@1.1.5 deduped
  │ │ │   │ │   ├── repeat-element@1.1.2 deduped
  │ │ │   │ │   └── repeat-string@1.6.1
  │ │ │   │ ├── preserve@0.2.0
  │ │ │   │ └── repeat-element@1.1.2
  │ │ │   ├─┬ expand-brackets@0.1.5
  │ │ │   │ └── is-posix-bracket@0.1.1
  │ │ │   ├─┬ extglob@0.3.2
  │ │ │   │ └── is-extglob@1.0.0 deduped
  │ │ │   ├── filename-regex@2.0.1
  │ │ │   ├── is-extglob@1.0.0 deduped
  │ │ │   ├── is-glob@2.0.1 deduped
  │ │ │   ├─┬ kind-of@3.2.2
  │ │ │   │ └── is-buffer@1.1.5
  │ │ │   ├─┬ normalize-path@2.1.1
  │ │ │   │ └── remove-trailing-separator@1.0.2
  │ │ │   ├─┬ object.omit@2.0.1
  │ │ │   │ ├─┬ for-own@0.1.5
  │ │ │   │ │ └── for-in@1.0.2
  │ │ │   │ └── is-extendable@0.1.1
  │ │ │   ├─┬ parse-glob@3.0.4
  │ │ │   │ ├─┬ glob-base@0.3.0
  │ │ │   │ │ ├── glob-parent@2.0.0 deduped
  │ │ │   │ │ └── is-glob@2.0.1 deduped
  │ │ │   │ ├── is-dotfile@1.0.3
  │ │ │   │ ├── is-extglob@1.0.0 deduped
  │ │ │   │ └── is-glob@2.0.1 deduped
  │ │ │   └─┬ regex-cache@0.4.3
  │ │ │     ├─┬ is-equal-shallow@0.1.3
  │ │ │     │ └── is-primitive@2.0.0 deduped
  │ │ │     └── is-primitive@2.0.0
  │ │ ├── async-each@1.0.1
  │ │ ├── UNMET OPTIONAL DEPENDENCY fsevents@^1.0.0
  │ │ ├─┬ glob-parent@2.0.0
  │ │ │ └── is-glob@2.0.1 deduped
  │ │ ├── inherits@2.0.3 deduped
  │ │ ├─┬ is-binary-path@1.0.1
  │ │ │ └── binary-extensions@1.8.0
  │ │ ├─┬ is-glob@2.0.1
  │ │ │ └── is-extglob@1.0.0
  │ │ ├── path-is-absolute@1.0.1 deduped
  │ │ └─┬ readdirp@2.1.0
  │ │   ├── graceful-fs@4.1.11 deduped
  │ │   ├── minimatch@3.0.4 deduped
  │ │   ├─┬ readable-stream@2.3.3
  │ │   │ ├── core-util-is@1.0.2 deduped
  │ │   │ ├── inherits@2.0.3 deduped
  │ │   │ ├── isarray@1.0.0 deduped
  │ │   │ ├── process-nextick-args@1.0.7 deduped
  │ │   │ ├── safe-buffer@5.1.1
  │ │   │ ├─┬ string_decoder@1.0.3
  │ │   │ │ └── safe-buffer@5.1.1 deduped
  │ │   │ └── util-deprecate@1.0.2 deduped
  │ │   └── set-immediate-shim@1.0.1
  │ ├── glob@7.1.2 deduped
  │ ├── semver@5.3.0
  │ ├─┬ shelljs@0.7.8
  │ │ ├── glob@7.1.2 deduped
  │ │ ├── interpret@1.0.3
  │ │ └─┬ rechoir@0.6.2
  │ │   └── resolve@1.3.3 deduped
  │ ├─┬ tslint@5.5.0
  │ │ ├─┬ babel-code-frame@6.22.0
  │ │ │ ├─┬ chalk@1.1.3
  │ │ │ │ ├── ansi-styles@2.2.1
  │ │ │ │ ├── escape-string-regexp@1.0.5 deduped
  │ │ │ │ ├─┬ has-ansi@2.0.0
  │ │ │ │ │ └── ansi-regex@2.1.1
  │ │ │ │ ├─┬ strip-ansi@3.0.1
  │ │ │ │ │ └── ansi-regex@2.1.1 deduped
  │ │ │ │ └── supports-color@2.0.0
  │ │ │ ├── esutils@2.0.2 deduped
  │ │ │ └── js-tokens@3.0.2
  │ │ ├── colors@1.1.2
  │ │ ├── commander@2.11.0
  │ │ ├── diff@3.2.0 deduped
  │ │ ├── glob@7.1.2 deduped
  │ │ ├── minimatch@3.0.4 deduped
  │ │ ├─┬ resolve@1.3.3
  │ │ │ └── path-parse@1.0.5 deduped
  │ │ ├── semver@5.3.0 deduped
  │ │ ├── tslib@1.7.1
  │ │ └─┬ tsutils@2.7.1
  │ │   └── tslib@1.7.1 deduped
  │ └── typescript@2.4.1
  ├─┬ @theintern/digdug@2.0.0-beta.7
  │ ├── @dojo/core@2.0.0-beta2.2
  │ ├── UNMET PEER DEPENDENCY @dojo/has@2.0.0-beta2.2 deduped
  │ ├── @dojo/interfaces@2.0.0-beta2.2 deduped
  │ ├── UNMET PEER DEPENDENCY @dojo/shim@2.0.0-beta2.2
  │ └─┬ decompress@4.2.0
  │   ├─┬ decompress-tar@4.1.0
  │   │ ├── file-type@3.9.0
  │   │ ├── is-stream@1.1.0
  │   │ └─┬ tar-stream@1.5.4
  │   │   ├─┬ bl@1.2.1
  │   │   │ └── readable-stream@2.3.3 deduped
  │   │   ├─┬ end-of-stream@1.4.0
  │   │   │ └── once@1.4.0 deduped
  │   │   ├── readable-stream@2.3.3 deduped
  │   │   └── xtend@4.0.1
  │   ├─┬ decompress-tarbz2@4.1.0
  │   │ ├── decompress-tar@4.1.0 deduped
  │   │ ├── file-type@3.9.0 deduped
  │   │ ├── is-stream@1.1.0 deduped
  │   │ ├── pify@2.3.0 deduped
  │   │ ├─┬ seek-bzip@1.0.5
  │   │ │ └─┬ commander@2.8.1
  │   │ │   └── graceful-readlink@1.0.1
  │   │ └─┬ unbzip2-stream@1.2.4
  │   │   ├─┬ buffer@3.6.0
  │   │   │ ├── base64-js@0.0.8
  │   │   │ ├── ieee754@1.1.8
  │   │   │ └── isarray@1.0.0 deduped
  │   │   └── through@2.3.8
  │   ├─┬ decompress-targz@4.1.0
  │   │ ├── decompress-tar@4.1.0 deduped
  │   │ ├── file-type@4.4.0
  │   │ └── is-stream@1.1.0 deduped
  │   ├─┬ decompress-unzip@4.0.1
  │   │ ├── file-type@3.9.0 deduped
  │   │ ├─┬ get-stream@2.3.1
  │   │ │ ├── object-assign@4.1.1
  │   │ │ └─┬ pinkie-promise@2.0.1
  │   │ │   └── pinkie@2.0.4
  │   │ ├── pify@2.3.0 deduped
  │   │ └─┬ yauzl@2.8.0
  │   │   ├── buffer-crc32@0.2.13
  │   │   └─┬ fd-slicer@1.0.1
  │   │     └── pend@1.2.0
  │   ├── graceful-fs@4.1.11
  │   ├─┬ make-dir@1.0.0
  │   │ └── pify@2.3.0 deduped
  │   ├── pify@2.3.0
  │   └─┬ strip-dirs@2.0.0
  │     └── is-natural-number@4.0.1
  ├─┬ @theintern/leadfoot@2.0.0-beta.10
  │ ├── @dojo/core@2.0.0-beta2.2
  │ ├── UNMET PEER DEPENDENCY @dojo/has@2.0.0-beta2.2 deduped
  │ ├── @dojo/interfaces@2.0.0-beta2.2 deduped
  │ ├── UNMET PEER DEPENDENCY @dojo/shim@2.0.0-beta2.2
  │ ├── @theintern/dev@0.4.3 deduped
  │ └─┬ jszip@3.1.3
  │   ├── core-js@2.3.0
  │   ├── es6-promise@3.0.2
  │   ├─┬ lie@3.1.1
  │   │ └── immediate@3.0.6
  │   ├── pako@1.0.5
  │   └─┬ readable-stream@2.0.6
  │     ├── core-util-is@1.0.2
  │     ├── inherits@2.0.3 deduped
  │     ├── isarray@1.0.0
  │     ├── process-nextick-args@1.0.7
  │     ├── string_decoder@0.10.31
  │     └── util-deprecate@1.0.2
  ├── @types/benchmark@1.0.30
  ├── @types/chai@4.0.1
  ├─┬ @types/charm@1.0.0
  │ └── @types/node@8.0.13
  ├── @types/diff@3.2.0
  ├── @types/lodash@4.14.69
  ├── @types/mime-types@2.1.0
  ├── @types/platform@1.3.0
  ├── @types/source-map@0.1.29
  ├─┬ @types/ws@0.0.42
  │ └── @types/node@8.0.13 deduped
  ├─┬ benchmark@2.1.4
  │ ├── lodash@4.17.4 deduped
  │ └── platform@1.3.4 deduped
  ├─┬ chai@4.0.2
  │ ├── assertion-error@1.0.2
  │ ├── check-error@1.0.2
  │ ├─┬ deep-eql@2.0.2
  │ │ └── type-detect@3.0.0
  │ ├── get-func-name@2.0.0
  │ ├── pathval@1.1.0
  │ └── type-detect@4.0.3
  ├─┬ charm@1.0.2
  │ └── inherits@2.0.3
  ├── diff@3.2.0
  ├─┬ glob@7.1.2
  │ ├── fs.realpath@1.0.0
  │ ├─┬ inflight@1.0.6
  │ │ ├── once@1.4.0 deduped
  │ │ └── wrappy@1.0.2
  │ ├── inherits@2.0.3 deduped
  │ ├─┬ minimatch@3.0.4
  │ │ └─┬ brace-expansion@1.1.8
  │ │   ├── balanced-match@1.0.0
  │ │   └── concat-map@0.0.1
  │ ├─┬ once@1.4.0
  │ │ └── wrappy@1.0.2 deduped
  │ └── path-is-absolute@1.0.1
  ├── istanbul-lib-coverage@1.1.1
  ├─┬ istanbul-lib-hook@1.0.7
  │ └─┬ append-transform@0.4.0
  │   └─┬ default-require-extensions@1.0.0
  │     └─┬ strip-bom@2.0.0
  │       └── is-utf8@0.2.1
  ├─┬ istanbul-lib-instrument@1.7.4
  │ ├─┬ babel-generator@6.25.0
  │ │ ├─┬ babel-messages@6.23.0
  │ │ │ └── babel-runtime@6.23.0 deduped
  │ │ ├─┬ babel-runtime@6.23.0
  │ │ │ ├── core-js@2.4.1
  │ │ │ └── regenerator-runtime@0.10.5
  │ │ ├── babel-types@6.25.0 deduped
  │ │ ├─┬ detect-indent@4.0.0
  │ │ │ └─┬ repeating@2.0.1
  │ │ │   └─┬ is-finite@1.0.2
  │ │ │     └── number-is-nan@1.0.1
  │ │ ├── jsesc@1.3.0
  │ │ ├── lodash@4.17.4 deduped
  │ │ ├── source-map@0.5.6 deduped
  │ │ └── trim-right@1.0.1
  │ ├─┬ babel-template@6.25.0
  │ │ ├── babel-runtime@6.23.0 deduped
  │ │ ├── babel-traverse@6.25.0 deduped
  │ │ ├── babel-types@6.25.0 deduped
  │ │ ├── babylon@6.17.4 deduped
  │ │ └── lodash@4.17.4 deduped
  │ ├─┬ babel-traverse@6.25.0
  │ │ ├── babel-code-frame@6.22.0 deduped
  │ │ ├── babel-messages@6.23.0 deduped
  │ │ ├── babel-runtime@6.23.0 deduped
  │ │ ├── babel-types@6.25.0 deduped
  │ │ ├── babylon@6.17.4 deduped
  │ │ ├── debug@2.6.8 deduped
  │ │ ├── globals@9.18.0
  │ │ ├─┬ invariant@2.2.2
  │ │ │ └─┬ loose-envify@1.3.1
  │ │ │   └── js-tokens@3.0.2 deduped
  │ │ └── lodash@4.17.4 deduped
  │ ├─┬ babel-types@6.25.0
  │ │ ├── babel-runtime@6.23.0 deduped
  │ │ ├── esutils@2.0.2
  │ │ ├── lodash@4.17.4 deduped
  │ │ └── to-fast-properties@1.0.3
  │ ├── babylon@6.17.4
  │ ├── istanbul-lib-coverage@1.1.1 deduped
  │ └── semver@5.3.0 deduped
  ├─┬ istanbul-lib-report@1.1.1
  │ ├── istanbul-lib-coverage@1.1.1 deduped
  │ ├─┬ mkdirp@0.5.1
  │ │ └── minimist@0.0.8
  │ ├── path-parse@1.0.5
  │ └─┬ supports-color@3.2.3
  │   └── has-flag@1.0.0
  ├─┬ istanbul-lib-source-maps@1.2.1
  │ ├─┬ debug@2.6.8
  │ │ └── ms@2.0.0
  │ ├── istanbul-lib-coverage@1.1.1 deduped
  │ ├── mkdirp@0.5.1 deduped
  │ ├─┬ rimraf@2.6.1
  │ │ └── glob@7.1.2 deduped
  │ └── source-map@0.5.6 deduped
  ├─┬ istanbul-reports@1.1.1
  │ └─┬ handlebars@4.0.10
  │   ├── async@1.5.2
  │   ├─┬ optimist@0.6.1
  │   │ ├── minimist@0.0.8 deduped
  │   │ └── wordwrap@0.0.3
  │   ├─┬ source-map@0.4.4
  │   │ └── amdefine@1.0.1
  │   └─┬ uglify-js@2.8.29
  │     ├── source-map@0.5.6 deduped
  │     ├── uglify-to-browserify@1.0.2
  │     └─┬ yargs@3.10.0
  │       ├── camelcase@1.2.1
  │       ├─┬ cliui@2.1.0
  │       │ ├─┬ center-align@0.1.3
  │       │ │ ├─┬ align-text@0.1.4
  │       │ │ │ ├── kind-of@3.2.2 deduped
  │       │ │ │ ├── longest@1.0.1
  │       │ │ │ └── repeat-string@1.6.1 deduped
  │       │ │ └── lazy-cache@1.0.4
  │       │ ├─┬ right-align@0.1.3
  │       │ │ └── align-text@0.1.4 deduped
  │       │ └── wordwrap@0.0.2
  │       ├── decamelize@1.2.0
  │       └── window-size@0.1.0
  ├── lodash@4.17.4
  ├─┬ mime-types@2.1.15
  │ └── mime-db@1.27.0
  ├── platform@1.3.4
  ├─┬ shell-quote@1.6.1
  │ ├── array-filter@0.0.1
  │ ├── array-map@0.0.0
  │ ├── array-reduce@0.0.0
  │ └── jsonify@0.0.0
  ├── source-map@0.5.6
  └─┬ ws@2.3.1
    ├── safe-buffer@5.0.1
    └── ultron@1.1.0

npm ERR! peer dep missing: @dojo/has@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/shim@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/shim@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/shim@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/shim@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/shim@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/shim@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/shim@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/shim@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/shim@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/shim@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/core@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/has@next, required by @dojo/shim@2.0.0-beta2.2
npm ERR! peer dep missing: @dojo/shim@next, required by @dojo/core@2.0.0-beta2.2

**Comment by mo** [comment]
I workaround this using:
npm install @dojo/has@next
npm install @dojo/shim@next

...if that's the right thing to do, it would be nice if the readme mentioned this. My project does not use dojo outside of intern.

**Comment by jason0x43** [comment]
Try installing with npm 5.3.0. At least npm 5.2.0 had a package dedupe issue that would cause it to leave multiple copies of @dojo/shim in node_modules, which would cause the 'es6-symbol' issue you're seeing.

**Comment by mo** [comment]
Installing using npm 5.3.0 worked indeed!
