### ISSUE TITLE
Leadfoot setPageLoadTimeout typing definition is expecting a String instead of number in intern4

### ISSUE THREAD

**Issue by firdausng** [theintern/intern#786]
## Expected behavior
Leadfoot setPageLoadTimeout should expect a number in its argument

## Current behavior
Leadfoot setPageLoadTimeout should expect a string in its argument

## Possible solution
fixed the leadfoot type definition in Command.d.ts

**Comment by jason0x43** [comment]
Good catch! I moved this over to the Leadfoot issue tracker: https://github.com/theintern/leadfoot/issues/122
