### ISSUE TITLE
Handling of configs inside of npm namespaces

### ISSUE THREAD

**Issue by rorticus** [theintern/intern#787]
I'm trying to hide away the intern config behind a package that is in a namespace, so the resulting command looks like, 

```shell
node_modules/.bin/intern config=node_modules/@dojo/cli-test-intern/intern/intern.json
```

The error I get with this is, 

```
{ Error: EISDIR: illegal operation on a directory, read errno: -21, code: 'EISDIR', syscall: 'read' }
```

Which I assume is because it is treating the `@` as the child config separator.

## Expected behavior
Should support loading config files from paths with `@` in them.

## Current behavior
Error when loading a config file from a path with a `@` in it.

## Possible solution
Possibly use a regex to find only `@`'s at the end of the given path. Maybe something like `@([^\/]+)$`

## Steps to reproduce (for bugs)

1. Create a configuration file in a path that includes a `@` in it. Something like `/tmp/@temp/config.json` should do the trick.
2. Launch intern with this configuration file, `intern config=/tmp/@temp/config.json`

## Environment

Intern version: 4.0.0-alpha.13
Node version: 7.10.1
NPM version: 4.6.1

**Comment by rorticus** [comment]
For what it's worth, I just patched `splitConfigPath` locally to use the regex `/^(.+?)(?:@([^\/]+))?$/g` and it seemed to work for my one case.

**Comment by jason0x43** [comment]
Lucky me for choosing the same character that's used to denote npm org packages. In the long run we should probably choose a different character or support escaping.

**Comment by rorticus** [comment]
You could go with an emoji. That'd be fun to type in the terminal. `node_modules/@dojo/cli-test-intern/intern/intern.json🌭browserstack`
