### ISSUE TITLE
Allow a string for `loader.options` in intern.json

### ISSUE THREAD

**Issue by bryanforbes** [theintern/intern#795]
For applications using a loader, it's burdensome to keep `loader.options` in `intern.json` in sync with an application's loader configuration. It would be helpful to allow a string for `loader.options` that points to a loader configuration file which intern would load.

**Comment by jason0x43** [comment]
Would this point to a JSON file or to a JS module? Assuming it's a JSON file, is the idea that Intern would load and parse the JSON file and pass it in as the 'options' value?

**Comment by jason0x43** [comment]
After some offline discussion, it sounds like this would be satisfied by a script loaded via `plugins`.
