### ISSUE TITLE
Documentation update - new suite glob resolver will not work with just any static web server

### ISSUE THREAD

**Issue by edhager** [theintern/intern#816]
The documentation for running Intern in a browser need to be updated for version 4.0.1 of Intern: https://theintern.io/docs.html#Intern/4/docs/docs%2Frunning.md/browser.

If globs are being used to define the suites, Intern has to be the web server: 

`./node_modules/.bin/intern serveOnly
`

Any static web server will work if globs are avoided.

**Comment by jason0x43** [comment]
Hmmmm...that page already says something to that effect:

> This command will cause Intern to start a static server on the port set by serverPort. The main utility offered by this server over any other static server is that it allows glob expressions in the suites list to be resolved.

We could call it out a bit better, and update the `suites` config property documentation to say something about that.

Note that this isn’t new behavior — glob resolution from the browser client has always required that Intern’s own static server be used.
