### ISSUE TITLE
Feature request - automatically redirect to browser runner

### ISSUE THREAD

**Issue by edhager** [theintern/intern#817]
If I tell Intern to start a web server using:

`./node_modules/.bin/intern serveOnly
`

Then I point my browser at `http://localhost:9000/`, could it automatically redirect to the browser to the test runner (`http://localhost:9000/__intern/index.html`)?

Thanks!

**Comment by jason0x43** [comment]
That could cause problems if the user has an index.html at the project root. Browsing to just `/__intern/` will work, though, and [@theintern/cli](https://github.com/theintern/cli) can automatically open a browser when you start the server. We could possibly come up with something shorter than __intern.

**Comment by jason0x43** [comment]
Starting intern in serveOnly mode now shows the target address for the browser client:

```
Listening on localhost:9000 (ws 9001)

To use the browser client, browse to

  http://localhost:9000/__intern/

```

**Comment by jason0x43** [comment]
I'm going to close this for now. If someone has any new info we can re-open it, but this seems like it could cause confusion down the road since it would make Intern's server behave differently than other static servers at a basic level.
