### ISSUE TITLE
Executor on IE9 accesses console in unsafe way

### ISSUE THREAD

**Issue by dbow** [theintern/intern#818]
## Expected behavior

There are some calls to `console` methods that don't exist in IE9 in the [Executor.ts file](https://github.com/theintern/intern/blob/master/src/lib/executors/Executor.ts) that seem to break tests on IE9 when running via the Remote Suite.

It looks like this was resolved in PreExecutor in [this bug](https://github.com/theintern/intern/issues/597) but then I think the `console` calls were added to Executor a few months later?

I think there are two `console.warn` calls because of the `serverUrl` and `socketPort` params added to the test harness page in RemoteSuite. When I go to the test harness page in a modern browser, I see:
```
remote.js:104 Config has unknown option "serverUrl"
remote.js:104 Config has unknown option "socketPort"
```
But in IE9 it logs
```
Unable to get value of the property 'warn': object is null or undefined
```

## Current behavior

IE9 returns an error due to console not existing and the remote suite times out.

## Steps to reproduce (for bugs)

1. …
2. …
3. …

## Environment

Intern version: 4.0.1
Node version: 7.1.0
NPM version: 3.10.9
Browser version: IE9

**Comment by jason0x43** [comment]
Intern 4 doesn't currently support IE 9 and hasn't been tested with it. Aside from the console issue, there's an arrow function in the browser client, and it looks like the xhr module from @dojo/core/request may have some issues with IE 9 as well. That's not to say we can't improve IE 9 functionality but it will likely involve some upstream changes as well as updates to Intern itself.

**Comment by jason0x43** [comment]
Now that I think about it, I'm kind of surprised that arrow function hasn't been more of a problem...

**Comment by dbow** [comment]
Got it, yeah I noticed that arrow function too! Might be worth mentioning explicitly in the docs? The main line from the README is "Intern can run unit tests in browsers that support ECMAScript 5" - it sounds like that's not entirely accurate for Intern 4.

**Comment by jason0x43** [comment]
True. I'll mention the lack of IE9 support.
