### ISSUE TITLE
Improve documentation around fixSessionCapabilities, what it does and its configuration

### ISSUE THREAD

**Issue by inad9300** [theintern/intern#822]
## Current behavior
When Chrome gets opened, a bunch of stuff starts to happen, such as the creation of checkboxes that are toggled, select elements that are opened and closed, and so on, which I haven't included on my tests. It looks like some kind of Intern's internal checks, test suite, or something. I have no clue really, but it definitely looks like I shouldn't be seeing those things.

## Steps to reproduce
For me it was enough with just define "chrome" as the target environment, and run some unit tests.

## Environment

Intern version: 4.0.2
Node version: 7.8.0
NPM version: 5.5.1
Browser version: Chrome 61.0.3163.100 on Linux

**Comment by dylans** [comment]
This is to support Leadfoot's ability to improve the WebDriver experience (described in the first two paragraphs at https://theintern.io/docs.html#Leadfoot/2/docs/README.md ), essentially the list at https://theintern.io/leadfoot/global.html#Capabilities (though this is the list from Leadfoot 1.x). 

There is a way to skip this but I don't remember the command flag off the top of my head.

**Comment by inad9300** [comment]
Thanks for the explanation. I still don't understand why the end users see this -- it makes no sense to us at all, creating confusion, and it delays the execution of the tests. (I don't understand either how including this in the shipped runner is even useful to anyone.) In any case, I suppose skipping it by default would be the most sensible option.

If you happen to encounter this magic flag you've mentioned, please share it with us!

**Comment by kitsonk** [comment]
The end user sees it because there is no easy way to hide it from the end user. Most of these probing tests require specific Selenium commands which are not to be hidden from the user.

**Comment by dylans** [comment]
> I don't understand either how including this in the shipped runner is even useful to anyone

Many Selenium WebDriver instances are broken in novel ways, and we can work around them (either by applying a known workaround, or by skipping tests that would otherwise crash the WebDriver instance). So it's very useful to end users to not have to know what is broken in every WebDriver instance out there. :)  And so we do this via feature testing, which requires a quick second or two of tests. It would be possible to provide a known list of capabilities by driver version, but this has the same issues as old browser sniffing techniques.

> If you happen to encounter this magic flag you've mentioned, please share it with us!

In your configuration, under `capabilities`, set `fixSessionCapabilities` to `false`

**Comment by dylans** [comment]
Note, leaving this ticket open as I don't see `fixSessionCapabilities` documented on the Intern website.

**Comment by inad9300** [comment]
Thanks, that works nicely. As you predicted, by setting the flag to `false` I managed to reduce the total time my tests last from ~10s to ~8s, which I appreciate very much. (Running Chrome in headless mode reduces another ~half a second; and bit by bit the feedback loop shortens and the value of the tests increases.)
