### ISSUE TITLE
A programmatic interface for the test runner

### ISSUE THREAD

**Issue by nicojs** [theintern/intern#823]
We're looking into supporting intern in [Stryker, the JavaScript mutation testing framework](https://stryker-mutator.github.io/). 

In order to support intern, we need a programmatic interface to interact with the test runner. Basically what we'll be doing is writing small changes (or mutants) to the input files. Each time we've mutated a file, we will start another test run and report the results. Our adapter interface looks like this: https://github.com/stryker-mutator/stryker/blob/master/packages/stryker-api/src/test_runner/TestRunner.ts

Is it be possible to programmatically interact with the test runner? If not, are there any plans to add it?

Original feature request here: https://github.com/stryker-mutator/stryker/issues/430

**Comment by kitsonk** [comment]
References this discussion on gitter: https://gitter.im/theintern/intern?at=59edb682f7299e8f531f514c

**Comment by jason0x43** [comment]
Intern has a programmatic API that seems like it should work with your TestRunner adapter. We have a simple [how to](https://theintern.io/docs.html#Intern/4/docs/docs%2Fhow_to.md/use-intern-programmatically) section in the docs on using the programmatic API. The included [grunt task](https://github.com/theintern/intern/blob/master/src/tasks/intern.ts) is another example of using this interface.

**Comment by jason0x43** [comment]
Closing this since it should be resolved with the existing API. Feel free to re-open if that's not sufficient.
