### ISSUE TITLE
Intern 4 does not assume a relative root

### ISSUE THREAD

**Issue by kitsonk** [theintern/intern#826]
## Expected behavior

Navigation to `http://localhost/project/node_modules/intern/` works.

I have my various projects hosted where the root of my projects path is the root of my localhost web-server.  I would expect that navigating to `http://localhost/project/node_modules/intern/` would attempt to resolve `http://localhost/project/intern.json`.

## Current behavior

Navigation to `http://localhost/project/node_modules/intern/` fails with:

```
Fatal error

Error: Unable to load /node_modules/intern/loaders/default.js
  at HTMLScriptElement.<anonymous>  <http://localhost/project/node_modules/intern/browser/intern.js:104:5954>
```

In addition, there is an attempt to load `http://localhost/intern.json` which results in a 404.

Adjusting the url to `http://localhost/project/node_modules/intern/?config=project/intern.json` does not resolve the issue, because Intern continues to look for everything from the root.

## Possible solution

Intern does assumes a relative root for its configuration, instead of an absolute one.

## Steps to reproduce (for bugs)

1. Configure a project to be served out of a sub path of a web server
2. Navigate to the `node_modules/intern` and notice how Intern fails.

## Environment

Intern version: 4.0.2
Node version: 8.6.0
NPM version: 5.4.2
Browser version: Chrome 62

**Comment by kitsonk** [comment]
I was able to get it to work if I did the following: `http://localhost/project/node_modules/intern/?basePath=/project/` but it feels like that is something that Intern would be able to resolve itself automatically.

**Comment by jason0x43** [comment]
The Browser executor currently assumes the project root is `/` unless it's told otherwise because it it can be difficult to determine what the project root is from the current browser path. However, it could probably handle the majority of cases by guessing the `basePath` to be the parent of `/node_modules/intern` (assuming that's a path component).

**Comment by jason0x43** [comment]
@kitsonk mentioned this offline, and it sounds like a good starting point: how about we assume the location of `intern.json` (when we know what it is) is the project root?

* The location of the config file will either be provided by the user, or will be assumed to be `intern.json` in a standard location (the parent of `node_modules/intern` in a browser environment, or process.cwd in Node).
* Once we've loaded the config file, it's containing path is the initial `basePath`.
  * If the loaded config contains an absolute `basePath` value, that value will become the new `basePath`.
  * If the loaded config contains a relative `basePath`, that new value will be resolved relative to the config file to create the new `basePath`.

If this seems reasonable we can use this logic for both the browser and Node, which would provide consistency between the two environments.

**Comment by kitsonk** [comment]
Sounds perfect to me!
