### ISSUE TITLE
Add ability to use + with objects in config files

### ISSUE THREAD

**Issue by bryanforbes** [theintern/intern#827]
## Expected behavior
In a config file with the following contents:

```json
{
  "capabilities": {
    "project": "My Project",
    "name": "My Name"
  },
  "configs": {
    "browserstack": {
      "capabilities+": {
        "browserstack.debug": false
      },
      ...
    },
    "saucelabs": {
      "capabilities+": {
        "fixSessionCapabilities": false
      },
      ...
    }
  }
}
```

I would expect the `capabilities` objects to be combined when selecting a config. For instance, for the `browserstack` config, the following would be the `capabilities` resolution:

```json
{
  "project": "My Project",
  "name": "My Name",
  "browserstack.debug": false
}
```

## Current behavior
The `capabilities` object gets overwritten by the selected config, so for `browserstack` above, the following is the result:

```json
{
  "browserstack.debug": false
}
```

## Environment

Intern version: 4.0.2
Node version: Any
NPM version: Any
Browser version: All

**Comment by jason0x43** [comment]
Resolved in https://github.com/theintern/intern/commit/f307a8a062927b9c2527b6bcf7ec66c615431a60
