### ISSUE TITLE
Simplify installation process

### ISSUE THREAD

**Issue by inad9300** [theintern/intern#828]
In the [*TypeScript setup*](https://github.com/theintern/intern#typescript-setup) section of Intern's README file, it is mentioned that people must set `"types": ["intern"]` in their `tsconfig.json` files. I believe this can be simplified away by pointing to the types from Intern's `package.json`, using the `"types"` property, as it is explained in the [TypeScript Documentation - Publishing](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html).

**Comment by jason0x43** [comment]
These two properties (`"types"` in `tsconfig.json` vs `"types"` in `package.json`) serve two different purposes. The one in `package.json` tells TS where to find the main typings for our package. Intern handles that implicitly by putting them in `index.d.ts`. The `"types"` in `tsconfig.json` tells TS to automatically load those types when building. You could, instead, have an `import 'intern';` in one of your source files, but the tsconfig property seems cleaner.

**Comment by inad9300** [comment]
Thanks for the clarification! I think I would personally prefer an explicit `import intern from 'intern';`, so that everyone is clear about where the `intern` variable is coming from. But OK, I understood now, sorry for the inconvenience and thanks for your time :)

**Comment by inad9300** [comment]
Actually, is `"types"` allowed at the root level of `tsconfig.json`? I have stumbled upon this again and remembered this issue. I believe the correct configuration would be
```json
{
    "compilerOptions": {
        "types" : ["intern"]
    }
}
```

**Comment by inad9300** [comment]
This has been merged already.
