### ISSUE TITLE
Intern 4 tests not compatible with Dojo 1 Deferred

### ISSUE THREAD

**Issue by edhager** [theintern/intern#832]
I upgraded a Dojo 1, JavaScript project to Intern 4.  In some of the tests, methods from the application return Dojo 1 Deferred objects so the test was returning those objects to Intern.  I've reduced that down to a couple sample test cases:
```javascript
test.suite('sample', function () {
	test.test('does not work', function () {
		var dfd = new Deferred();
		setTimeout(function () {
			dfd.resolve();
		}, 500);
		return dfd;
	});

	test.test('works', function () {
		var dfd = new Deferred();
		dfd.resolve();
		return dfd;
	});
});
```

This worked in Intern 3. If the returned Deferred object is not resolved when it is returned, Intern 4 throws this error:

```
× node - sample - does not work (0.003s)
    TypeError: resultTask_1.finally is not a function
      at <src/lib/Test.ts:303:19>
      at new Task  <node_modules/@dojo/core/async/Task.ts:210:3>
      at <src/lib/Test.ts:285:22>
      at new Task  <node_modules/@dojo/core/async/Task.ts:210:3>
      at <src/lib/Test.ts:284:12>
      at <node_modules/@dojo/core/async/Task.ts:319:12>
      at handler  <node_modules/@dojo/core/async/ExtensiblePromise.ts:216:14>
      at <anonymous>
```

Here is a test environment that demonstrates the problem: [intern-test.zip](https://github.com/theintern/intern/files/1431277/intern-test.zip)

1.  Unzip the file.
1.  Run `npm install`
1.  Run `node_modules/.bin/intern`

**Comment by edhager** [comment]
Here an example of the work-around I used to allow the tests to run:

```javascript
test.test('work around', function () {
	var dfd = this.async();
	var myDfd = new Deferred();
	myDfd.then(function () {
		dfd.resolve();
	});
	setTimeout(function () {
		dfd.resolve();
	}, 500);
});
```

**Comment by jason0x43** [comment]
Hmmm...it looks like the `isTask` function used in Test isn't discriminating enough. It was initially intended to differentiate Promises from Tasks in a fashion similar to dojo/core/async's own `isTask`, but more safely (dojo's method causes problems with chai-as-promised). Dojo 1 Deferreds have a `cancel` method, which makes `isTask` see them as Tasks, but they don't have a `finally` method, which means they're not actually compatible with Tasks.

This should be a simple enough fix.
