### ISSUE TITLE
Automate handling of Selenium tunnel drivers

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#833]
Currently when SeleniumTunnel is used with a non-native driver (anything but safaridriver), the user must specify the required driver in `tunnelOptions` so that Intern can tell the tunnel to download it. This should be automatic; either Intern or SeleniumTunnel should inspect the list of environments and determine which drivers need to be downloaded based on the browser names.

**Comment by wkeese** [comment]
Hi Jason,

I'm getting an error presumably related to this change... or at least, maybe you need some more work on this change before `tunnelOptions` can really be removed from intern.json.

I downloaded  Intern 4.5.0, removed the `tunnelConfig` from my intern.json, and when running against the latest Chrome (version 76) on Mac, it gives the error that:

> This version of ChromeDriver only supports Chrome version 74

For Intern 4.4.3, a colleague fixed that problem by specifying this in the intern.json file:

```
"tunnelOptions": {
        "drivers": [ "firefox", "internet explorer", "MicrosoftEdge", {"name": "chrome", "version": "76.0.3809.68" } ]
    },
```

**Comment by jason0x43** [comment]
Dig Dug still needs https://github.com/theintern/digdug/issues/71 (in progress) to be fully functional, since it can only auto-download the latest drivers it knows about. That’s generally OK for FF and IE, which change slowly, but Dig Dug hasn’t been good about keeping up with Chrome.

**Comment by wkeese** [comment]
OK.  I hope you don't go with a static JSON file, as it wouldn't be practical to update it every few weeks every time there was a new version of Chrome.   (I worry about not being able to run Intern for a few days every time a new version of Chrome is released.)  Plus which that strategy wouldn't work if someone wanted to test a beta version of Chrome.

**Comment by jason0x43** [comment]
Whether it's a static JSON file that's updated periodically by an automated service, or a live web service (that very well might use a static JSON file that's updated periodically by an automated service), we're going to have to provide something that stays up-to-date with drivers. Chrome's download service has a "latest" version endpoint, but no one else does (that I'm aware of).

In any case, nothing would prevent users from using whatever driver version they need, just as they can now. The only thing the driver version file/service would do is supplement the information digdug already has about drivers; the underlying driver configuration and download processes aren't changing. For example, digdug v2.2.4 currently uses geckodriver 0.24.0 if the user doesn't provide a version. With the file/service in theintern/digdug#71, digdug will still prefer a version provided by the user, but will use whatever version is provided by the service (or stick with the built-in default if no newer version is listed) if the user doesn't provide a version.
