### ISSUE TITLE
runInSync is not running tests in sync

### ISSUE THREAD

**Issue by pottedmeat** [theintern/intern#836]

**Comment by jason0x43** [comment]
When runInSync is enabled and a Promise is returned in an event handler, Intern should wait for the Promise to resolve before continuing execution. This should work both locally and in remote executors. This behavior appears to be broken at least for remote executors (like, if a Promise is returned in a testEnd event handler on the host intern, remote executors aren't waiting for the event handler to finish before running more tests).
