### ISSUE TITLE
Could this test IE edge on windows?

### ISSUE THREAD

**Issue by duckscofield** [theintern/intern#838]
## Expected behavior
I want to test IE edge browser on windows 10, but it runs on chrome.

## Current behavior
No error, but run with the wrong browser to test.

## Possible solution
Could the tutorial list other supported browser and code sample?

## Steps to reproduce (for bugs)
1. in `inter.json`, `environments:[{"browserName":"ie edge"}]`
2. execute `npm test` in shell
3. use `inter tutorial` code sample

## Environment

Intern version: ^4.4.1
Node version: v8.7.0
NPM version: 5.4.2
Browser version: ie edge

**Comment by jason0x43** [comment]
The proper name for MS Edge for WebDriver testing is "MicrosoftEdge". Even with that, though, getting Edge working with Intern locally was a multi-step process. We just published an update to the Dig Dug library (which is what Intern uses to manage Selenium) that simplifies the process a bit.

Install a fresh copy of intern@latest, and you should end up with a `@theintern/digdug` dependency of 2.0.2. Then add the following to your Intern config:

```
{
  "environments": [{"browserName:"MicrosoftEdge"}],
  "tunnelOptions": {
    "drivers":[{"name":"edge"}]
  }
}
```

At that point, you should be good to go.

**Comment by jason0x43** [comment]
Closing this since it should be resolved. Feel free to reopen if there's still an issue.
