### ISSUE TITLE
JSON Schema v4 for intern.json

### ISSUE THREAD

**Issue by justinbc820** [theintern/intern#848]
## Expected behavior
An up to date JSON schema on [JSON Store](http://schemastore.org/json/)

## Current behavior
There isn't one.

## Possible solution
I have created what I think is a pretty complete solution, but I'm new to both JSON Schema creation as well as Intern, so I'm sure there's something missing. Also, I was unsure which properties belong in the v4 intern.json because the docs seem to be incomplete.

Here's the [gist](https://gist.github.com/justinbc820/77c0c6a104e071a03ab60b11c3711187). Feel free to either contribute to that one, or to fork it or whatever you need to do.

**Comment by jason0x43** [comment]
There's also https://github.com/devpaul/intern-json-schema. Hmmm...I wonder if there's a decent vim plugin for using JSON schemas...

**Comment by jason0x43** [comment]
In addition to having a JSON schema, intern should also use something like avs to validate config files.

**Comment by jason0x43** [comment]
A v7 JSON schema was added in 1005066. It's available in the Intern package (`node_modules/intern/schemas/config.json`).
