### ISSUE TITLE
install intern problem

### ISSUE THREAD

**Issue by bright21051** [theintern/intern#856]
According to the document install steps, a week ago it works(install success).  When I installed and used the same steps today, and run npm test,  it displayed the following error:

![123](https://user-images.githubusercontent.com/18577509/33649581-5dd05f88-da99-11e7-8da1-d94f6dc46a42.png)

I think maybe is Dojo releases update(a day ago), cause something has changed.
Now how can I success to install the intern?
Whether the document install steps need to revise and update?
Thanks.

**Comment by jason0x43** [comment]
This issue doesn't happen when installing intern, but when trying to run it, specifically in the tutorial. I created https://github.com/theintern/intern-tutorial/issues/40 to track this.

**Comment by bright21051** [comment]
@jason0x43  Thank you.
Resolved.
