### ISSUE TITLE
No command-line output since 4.1.3

### ISSUE THREAD

**Issue by thegecko** [theintern/intern#858]
Hi, 

Our build system automatically updated to 4.1.4 (semver FTW!) but it looks like some of our reporters are no longer running.

This worked in 4.1.2, but not on 4.1.3. There is no longer any command line output although the chrome runner is running. Config file as follows:

```json
{
    "environments": [
        "node",
        "chrome"
    ],
    "node": {
        "suites": "lib/_tests/**/*.js"
    },
    "browser": {
        "suites": "bundles/_tests/**/*.js"
    },
    "coverage": [
        "lib/**/*.js",
        "!lib/_api/**",
        "!lib/_tests/**"
    ],
    "reporters+": [
        {
            "name": "jsoncoverage",
            "options": {
                "filename": "unit_coverage.json",
                "directory": "coverage"
            }
        },
        {
            "name": "junit",
            "options": {
                "filename": "junit.xml"
            }
        }
    ]
}
``

**Comment by jason0x43** [comment]
It looks like the recent updates to make configuration merging more consistent are causing the default 'runner' reporter to be removed in bin/intern.

A temporary fix is to explicitly add the 'runner' reporter to your config.

**Comment by jason0x43** [comment]
Need more integration tests, it seems...

**Comment by thegecko** [comment]
Ack, I'll pin 4.1.2 for now :)

**Comment by jason0x43** [comment]
This is being tracked in #970
