### ISSUE TITLE
Using Dojo 1 loader, relative package location path fails

### ISSUE THREAD

**Issue by edhager** [theintern/intern#859]
My test case is in this zip: [intern-dojo1-bug.zip](https://github.com/theintern/intern/files/1563989/intern-dojo1-bug.zip)

I have intern configured to only run tests in a browser and to use the Dojo 1 loader.

Steps:
1. Unzip
1. Run `npm i`
1. Run `./node_modules/.bin/intern serveOnly`
1. Point browser at `http://localhost:9000/__intern/`
1. Success!
1. Run `./node_modules/.bin/intern config=@local`
1. Fails!
```shell
Listening on localhost:9000 (ws 9001)
Tunnel started

‣ Created remote session chrome 63.0.3239.84 on Mac OS X (f942a5cde0cc22c0dd1a0ed101872242)
Suite chrome 63.0.3239.84 on Mac OS X FAILED
Error: scriptError
  at makeError  <node_modules/dojo/dojo.js:125:15>
  at HTMLScriptElement.<anonymous>  <node_modules/dojo/dojo.js:1752:21>
TOTAL: tested 1 platforms, 0 passed, 0 failed; suite error occurred
```

The problem is when the test runs through the selenium tunnel, the `location` path of myapp is not correct.  But it works just fine when running the test in a browser using the `serveOnly` parameter.

```json
{
	"browser": {
		"suites": [
			"../../tests/unit/main.js"
		],

		"loader": {
			"script": "dojo",
			"options": {
				"packages": [
					{ "name": "myapp", "location": "../../src" }
				]
			}
		}
	},

	"configs": {
		"local": {
			"tunnel": "selenium",
			"environments": [
				{ "browserName": "chrome" }
			]
		}
	}
}
```

The work around is make the `location` of myapp in `intern.json` an absolute path.
```json
"loader": {
	"script": "dojo",
	"options": {
		"packages": [
			{ "name": "myapp", "location": "/src" }
		]
	}
}
```

**Comment by jason0x43** [comment]
When the dojo loader is used, its `baseUrl` option is set to the the user-supplied `baseUrl` or to the currently configured `basePath`, so there _should_ be no need to use a relative path from the loader.

You can use absolute paths, or you can use MIDs for suites instead of file paths, so that Dojo's normal module resolution logic is used:

```js
"suites": [ "tests/unit/main" ],
"loader": {
    "script": "dojo",
    "options": {
        "packages": [ { "name": "myapp", "location": "src" } ]
    }
}
```

**Comment by jason0x43** [comment]
Closing this as resolved; we can re-open if it's still an issue
