### ISSUE TITLE
No results when using common js style in Node.js

### ISSUE THREAD

**Issue by vladikoff** [theintern/intern#860]
With this code as `intern4.js`: 

```
const intern = require('intern').default;

intern.configure({ functionalSuites: 'tests/unit/**/*.js' });
intern.run();
```

running `node tests/intern4.js`

produces no results, with a 0 exit code status

**Comment by jason0x43** [comment]
You'll also need to configure an environment in which to run functional tests (e.g., `{ environments: 'chrome' }`);

**Comment by jason0x43** [comment]
I created #861 to make this situation a bit more apparent.

**Comment by jason0x43** [comment]
Closing this since #861 handles it
