### ISSUE TITLE
Missing "generic" getInterface(name: string) prototype in Executor.d.ts

### ISSUE THREAD

**Issue by rhpijnacker** [theintern/intern#875]
In `Executor.ts` a bunch of `getInterface` signatures are listed, the last of them being a "generic" one that allows for an arbitrary string to be passed in.
In the generated `Executor.d.ts` this generic signature does not seem to be present.
E.g. when I try to load the 'cucumber' interface, I get the error:
```error TS2345: Argument of type '"cucumber"' is not assignable to parameter of type '"benchmark"'.```

Also, I would like to be able to typecast my interface. Would it not make sense to have a `getInterface<T>(name: string): T` signature, just like for the plugins?

**Comment by jason0x43** [comment]
Possibly, although I think it's probably better in the long run to just use `getPlugin`. Originally there was a bit more functionality involved, but at this point the `getInterface` method is simply an alias for `getPlugin`, and it may be deprecated at some point in the future.

**Comment by jason0x43** [comment]
Closing this since the preferred solution is to use the generic `getPlugin`.
