### ISSUE TITLE
Http Channel does not handle 204 response gracefully

### ISSUE THREAD

**Issue by jamime** [theintern/intern#889]
## Expected behavior

The `remote.html` runner should report a success when it receives a 204 from intern

## Current behavior
Errors are reported in the browser window such as Error sending testStart/testEnd. The results are reported to the intern process correctly.

## Possible solution
When `lib/middleware/post.ts` returns a `204` we should not try to parse the empty body.
https://github.com/theintern/intern/blob/f56177f85a3ee6ff123fb6a7a6ebfa35923dd885/src/lib/channels/Http.ts#L79

## Steps to reproduce (for bugs)
You need to disable the websocket connection by setting `"socketPort": false` in your config. 

## Environment

Intern version: 4.1.5
Node version: v9.7.1
NPM version: 5.6.0
Browser version: Chrome 65

## Additional information
https://github.com/whatwg/fetch/issues/113

**Comment by jason0x43** [comment]
This is included in Intern 4.2.0.
