### ISSUE TITLE
Support for functionalSuites property on specific environment configuration.

### ISSUE THREAD

**Issue by lethevimlet** [theintern/intern#892]
It would be nice, and mandatory in my opinion, to support "functionalSuites" property on specific environment configuration, currently one can choose specific unit test for a given environment using "suites" property but this is not the case for functional tests, "functionalSuites" property does not exist at the time.

For example currently one can do:

```
{
    "leaveRemoteOpen": false,
    "browser": {
        "plugins": [
            "tests/example/browser-example.js"        
        ],     
        "suites": [
            "tests/unit/browser/**/*.js"
        ]
    },
    "node": {
        "suites": [
            "tests/unit/node/**/*.js"
        ]
    },
    "suites": [],
    "functionalSuites": [
        "tests/functional/**/*.js"
    ],
    "environments": [
        "node",
        "chrome"
    ]
}
```

Note how suites can be added inside "browser" or "node" object, but you can't currently do this:

```
{
    "leaveRemoteOpen": false,
    "browser": {
        "plugins": [
            "tests/example/browser-example.js"        
        ],     
        "suites": [
            "tests/unit/browser/**/*.js"
        ],
        "functionalSuites": [
             "tests/functional/**/*.js"
        ]
    },
    "node": {
        "suites": [
            "tests/unit/node/**/*.js"
        ]
    },
    "suites": [],
    "functionalSuites": [],
    "environments": [
        "node",
        "chrome"
    ]
}
```

**Comment by jason0x43** [comment]
The `browser` property describes the resources that will be loaded in a browser (any browser). Since functional suites don't run in browsers (they _drive_ browsers, but don't run _in_ them), it doesn't really make sense to specify them there.

The cleanest way to specify functional suites (or regular suites) that should run only for a specific environment is to use child configs:

```js
{
  "configs": {
    "chrome": {
      "environments": [ "chrome" ],
      "functionalSuites": [ "suites_that_should_run_in_chrome" ]
    },
    "firefox": {
      "environments": [ "fierfox" ],
      "functionalSuites": [ "suites_that_should_run_in_firefox" ]
    }
  }
}
```

Then run intern like `npx intern config=@chrome` to run chrome tests.

**Comment by lethevimlet** [comment]
Nice, that makes total sense, thanks @jason0x43 totally missed  the config syntax.
