### ISSUE TITLE
Interactions on testing machine can break an intern test in progress

### ISSUE THREAD

**Issue by stephenmayer** [theintern/intern#907]
## Expected behavior
I would like to have a way to lock the browser so that I can monitor test progress without keyboard/mouse interactions impacting the test in progress.

## Current behavior
If you start an Intern test and attempt to type an email or use your mouse the focus can be taken from the window you are using by the browser that is executing test via webdriver.

## Possible solution
Perhaps research if webdriver can lock out external keyboard/mouse interactions so that window can not be tampered with?  I don't know enough about webdriver to confirm.

## Steps to reproduce (for bugs)

1. Launch a long(ish) intern test
2. Attempt to type an email while test is running
3. Observe that sometimes keyboard focus is stolen from email window and typing appears to hit the Intern test browser window

## Environment

Darwin 17.2.0

Intern version: 4.2
Node version: v6.10.3
NPM version: v3.10.10
Browser version: Version 66.0.3359.139 (Official Build) (64-bit)

**Comment by jason0x43** [comment]
This is a general issue with webdriver. Newer versions of Firefox, Safari, and Chrome do partially restrict access to browsers being used for tests (for example, you may have noticed a banner in Chrome stating "Chrome is being controlled by automated test software"), but it's not perfect. User actions, such as moving a window or removing focus from it, can still affect tests.

The most reliable way to prevent user actions from breaking functional tests while still getting to monitor them is to run tests in a VM, either locally or using a cloud service such as BrowserStack.
