### ISSUE TITLE
Provide an equivalent to for Intern 3's writeHtml option

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#909]
The `writeHtml` option was used to prevent the runner reporter from writing to the DOM during tests in cases where unit tests might be modifying the page (#435). The Dom reporter in Intern 4 has the same concerns, and it should be made more resilient against DOM modifications and/or Intern should provide an option to disable it.

**Comment by jason0x43** [comment]
A better implementation would be to do as suggested in #435 and host the report nodes in a container node rather than directly in document.body.

**Comment by RoystonS** [comment]
We're getting stung by this at the moment: our devs run unit tests locally using 'serveOnly' mode and the 'html' reporter, and we're getting cases where a set of tests that ran cleanly on a dev box then fail on an automated build as that's using the RemoteSuite, which forces the 'dom' reporter and that makes the page very large, causes scrolling etc.

I'm happy to knock together a PR if you can help spec out what would be a desirable solution?

Putting the dom output into a container node would help a little (as it would then be possible for us to contain it), but being able to switch off the dom reporter (as configured by RemoteSuite) would be even better.
