### ISSUE TITLE
leaveRemoteOpen isn't working in 4.2.0

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#911]
The `leaveRemoteOpen` option should leave a remote browser open after the testing process. This is working in 4.1.5, but not in 4.2.0.

**Comment by AlonMiz** [comment]
+1

**Comment by bthallion** [comment]
I'm also having this problem

**Comment by jason0x43** [comment]
I added a somewhat less aggressive kill function to Dig Dug and that seems to be doing the trick. Assuming the tests pass, I'll release a new version.

**Comment by jason0x43** [comment]
This is fixed in https://github.com/theintern/digdug/commit/8cb1ed2db2ddb8313f6e69aa6f685a84b351f436 and is part of digdug 2.1.1.
