### ISSUE TITLE
Broken link to writing_tests.md

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/intern#914]
https://github.com/theintern/intern/blob/e7d20e54fd41aae03b159c5c911b77025cc80aad/src/lib/common/config.ts#L206

This link appears in the doc page

https://theintern.io/docs.html#Intern/4/api/lib%2Fcommon%2Fconfig/functionalcoverage

as

https://theintern.io/docs.html#Intern/4/api/lib%2Fcommon%2Fwriting_tests.md

which does not exist.

![image](https://user-images.githubusercontent.com/1020541/40932888-b5e58100-6827-11e8-9f0d-433f8d69f1a4.png)

**Comment by jason0x43** [comment]
The code used to process markdown for the website can't properly handle this case yet (a relative doc link in source code). I added an issue in the site generator repo (theintern/theintern.github.io#18).

**Comment by gitgrimbo** [comment]
Related broken link on page https://theintern.io/docs.html#Intern/4/docs/docs%2Farchitecture.md.

![image](https://user-images.githubusercontent.com/1020541/44455945-42249900-a5f7-11e8-9c6d-29bc2d18c5ea.png)

"listening for events" links to URL https://theintern.io/docs.html#Intern/4/docs/docs%2Fapi.md/on

which shows "Oops..."

**Comment by jason0x43** [comment]
Closing this in favor of theintern/theintern.github.io#18
