### ISSUE TITLE
leaveRemoteOpen type is restricted to boolean

### ISSUE THREAD

**Issue by AmirTugi** [theintern/intern#915]
## Expected behavior
According to the doc, `leaveRemoteOpen` should be `boolean | "fail"`

## Current behavior
According to the [source file](https://github.com/theintern/intern/blob/master/src/lib/common/util.ts#L577) - the type is only `boolean`

## Possible solution
Create a different condition for `leaveRemoteOpen`

## Steps to reproduce (for bugs)
Try to put `"fail"` in the `leaveRemoteOpen` option in the json config file

## Environment

Intern version: 4.2.0
Node version: v8.4.0
NPM version: 6.0.1
Browser version: Chrome 66

**Comment by janpe** [comment]
Is this going to be a priority at some point. Hoping for a fix.

**Comment by jason0x43** [comment]
A fix is in and will go out in the next bug fix release (next couple of days).
