### ISSUE TITLE
kill ESRCH error on test finish?

### ISSUE THREAD

**Issue by ryuuji3** [theintern/intern#924]
## Expected behavior
Tests finish, and process exits gracefully.

## Current behavior
Upon tests starting, I see a weird cycle of a bunch of component tests (checkboxes, etc). I think this is normal behavior but I'm not sure. 

But when the tests finish running, I have a weird error message and the CLI process doesn't quit, until I force quit (ie. ctrl+c).

```
(ノಠ益ಠ)ノ彡┻━┻
Error: kill ESRCH
  at process.kill  <internal/process.js:186:13>
  at <node_modules/src/util.ts:46:10>
  at Array.forEach  <anonymous>
  at Object.kill  <node_modules/src/util.ts:45:24>
  at <node_modules/src/Tunnel.ts:566:3>
  at new Promise  <anonymous>
  at SeleniumTunnel.Tunnel._stop  <node_modules/src/Tunnel.ts:555:9>
  at SeleniumTunnel.Tunnel.stop  <node_modules/src/Tunnel.ts:523:24>
  at <src/lib/executors/Node.ts:303:7>
  at <node_modules/@dojo/core/async/Task.ts:318:27>
```

## Possible solution
According to a brief search, it looks like a process couldn't be killed

## Steps to reproduce (for bugs)
1. Run tests in CLI (ie. yarn test)
2. Wait for tests to finish
3. Upon finish, observe error message...

## Environment

Intern version: latest
Node version: 10.4.1
NPM version: 6.1.0
Browser version: 67.0.3396.79 (Official Build) (64-bit)
OS: MacOS Sierra 10.13.1 (17B1003)

## Additional information
Running headless chrome does not produce the fatal error, but I'd like to see my tests being run.

**Comment by Alon87** [comment]
I fixed this on my intern tests by giving the last spec the following  promise command:

 await remote.end();

This will tell the remote (Webdriver) to close the current session. I hope this helps.

**Comment by jason0x43** [comment]
The component tests at the beginning are normal -- those are feature tests Intern performs to determine the browser's capabilities.

The ESRCH error means that Node couldn't find the given process to kill, presumably because the process had already quit. Is this happening all the time? And only with a normal (non-headless) Chrome browser?

**Comment by ryuuji3** [comment]
Yes it happens all the time with a normal chrome instance.
