### ISSUE TITLE
Getting stale element reference exception for most remote instructions when testing in a page with a requestAnimationFrame loop

### ISSUE THREAD

**Issue by nialna** [theintern/intern#926]
## Expected behavior
Functions like `findById`, `click` or `moveMouseTo` work normally

## Current behavior
Calling any remote instruction related to the dom gives the stale element reference exception from Selenium

## Possible solution
I don't know

## Steps to reproduce (for bugs)
I am running functional tests on a game which has a canvas and an update loop with requestAnimationFrame (this might be relevant).

Basic test code that doesn't work:

```ts
registerSuite('Functional Test', {
  'load a page'() {
    return this.remote
    .get('http://localhost:8080/')
      .sleep(5000)
      .findById('playGame')
      .click()
// After this, my game is launched, which creates a requestAnimationFrame loop, and then all future find/click/move instructions fail
      .sleep(2000)
      .moveMouseTo(200, 200) // This gives a stale element reference, even though I'm not passing any element
      .sleep(2000)
      .findById('modal-button') // This does it too, but the element with this ID exists on the page
      .sleep(2000)
  },
});
```

## Environment

Intern version: 4.2.0
Node version: 9.9.0
NPM version: 5.6.0
Browser version: Chrome 65 and 67 - Tested locally and on Browserstack

## Additional information

I'm not _sure_ it has anything to do with having a requestAnimationFrame loop, this is just my best guess for a suspect.

To be more specific: I don't know what is happening exactly, but I've read that this exception can happen if a reference is kept too long before being used, because when the dom is refreshed, those references become stale. So I suspect that maybe, somehow, the request animation frame can interfere with Intern?

Pretty much every remote instruction that involves elements (and even moveMouseTo apparently) fails once the animation frame loop has started. There is no page refresh involved or anything of the kind. None of those dom elements are being modified, there is only a game update loop that draws on a canvas and updates a stat widget.

**Comment by gitgrimbo** [comment]
Does a call to `end` do anything?

```
      .findById('playGame')
      .click()
      .end(Infinity)
```

**Comment by nialna** [comment]
This worked for me, thanks.

It seems that I have to call `end()` after every interaction though. Is that the expected behaviour? I thought running a new `findById` command implied not reusing the previous references, but maybe I misunderstood something from the samples.

**Comment by gitgrimbo** [comment]
Hi, yes I think there is a context associated with each command which can either be a single element (when previous call was something like `findXXX`) or a list of elements (when previous call was something like `findAllXXX`).

This context is chained along in the commands you call.

You 'exit' out of this context by calling `end()` for exiting 1 context, and `end(n)` to exit n contexts.

I might have described this incorrectly, but that's my understanding.

So in your case, I expect `.findById('playGame')` sets the context to the `#playGame` element. The call to `findById('modal-button')` cannot find an element with id `modal-button` 'inside' the `#playGame` element.

I'm not sure about the `mouseMoveTo` command, but I expect there something similar going on, where that call is not applicable 'inside' the `#playGame` element.

Alternatively, it could be that the `#playGame` element is removed from the dom or modified in some way when you click it, and this might also make the element reference stale.

**Comment by nialna** [comment]
Yeah, it seems to be the behaviour.

Also the `mouseMoveTo` command takes an optional `element` parameter, so I assume that when this parameter is omited, behind the scene it automatically takes the current element from the context and use that, which in my previous code caused the same stale reference.

I had to `findById` another element that actually worked, in order to be able to use `moveMouseTo`, so I assume it's relative to the current context.

The [functional tests documentation](https://github.com/theintern/intern/blob/master/docs/writing_tests.md#functional-tests) does use `end()`, but it doesn't really mention why it's necessary and I think I just didn't notice it was there. Maybe it could be edited to make that context system more obvious? (I can make a PR if that's a good idea)

**Comment by gitgrimbo** [comment]
If you think the docs can be improved, I'm sure the maintainers would appreciate a PR.

FYI, this page mentions the element context:

https://theintern.io/docs.html#Leadfoot/2/docs/docs%2Farchitecture.md/element-context

> The retrieved elements are stored internally as the element context of the Command chain. When element methods, such as getVisibleText, are called on a Command, they operate on the current context.

as does this:

https://theintern.io/docs.html#Leadfoot/2/api/Command/command-1

> On the other hand, to perform element interactions, you first need to retrieve one or more elements to interact with. This can be done using any of the find or findAll methods, by the getActiveElement method, or by returning elements from execute or executeAsync calls. The retrieved elements are stored internally as the element context of all chained Commands. When an element method is called on a chained Command with a single element context, the result will be returned as-is:

**Comment by jason0x43** [comment]
There is a context stack maintained for chained commands; this allows earlier commands to change the scope that later commands operate on, and also allows operations to work implicitly on the current context element(s).

```js
this.remote
  .get(page)
  // Find an outer element of interest
  .findById('table-2')
    // Look for all rows in the found table
    .findAllByCssSelector('tr')
      .then(rows => assert.length(rows, 10))
      // Pop the array of table rows off the context stack
      .end()
    .findByCssSelector('tr:nth-child(3) td.label')
      // Get the text of the current context element (the td.label)
      .getVisibleText()
      .then(text => assert.equal(text, 'some label'))
      // Pop the td.label off the context stack
      .end()
  // Pop the #table-2 off the context stack
  .end()
  // other commands
```

Alternatively you can use async/await for a non-chaining syntax:

```js
const page = await this.remote.get(page);
const table = await page.findById('table-2');
const rows = await table.findAllByCssSelector('tr');
assert.length(rows, 10);
const td = await table.findByCssSelector('tr:nth-child(3) td.label');
const text = await td.getVisibleText();
assert.equal(text, 'some label');
```

As @gitgrimbo says, documentation PRs are always welcome :)
