### ISSUE TITLE
Browser report does not expand all (or expand any) in IE11

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/intern#927]
## Expected behavior

Clicking "Expand/collapse all" on the browser report will expand all the tests.

![image](https://user-images.githubusercontent.com/1020541/41900571-f0192d62-7926-11e8-8b20-8836383c9beb.png)

## Current behavior

Clicking "Expand/collapse all" on the browser report does not expand all the tests, but the arrow changes from *pointing-right* to *pointing-down*, indicating the action has been recognised.

![image](https://user-images.githubusercontent.com/1020541/41900600-01aa081c-7927-11e8-8974-899e2350229c.png)

## Steps to reproduce (for bugs)

Click "Expand/collapse all" on the browser report to try and expand all the tests.

## Environment

Intern version: 4.2.0
Node version: Not applicable, but 10.3.0
NPM version: Not applicable, but 6.1.0
Browser version: IE 11

**Comment by gitgrimbo** [comment]
Looks like a dupe of #683, but in the Intern 4 codebase.

**Comment by jason0x43** [comment]
Resolved in aaac9d9
