### ISSUE TITLE
Intern programmatic API has no documented events

### ISSUE THREAD

**Issue by nialna** [theintern/intern#933]
## Expected behavior
I can use various events to know when my tests are finished or fail

## Current behavior
The [documentation](https://theintern.io/docs.html#Intern/4/docs/docs%2Fhow_to.md/use-intern-programmatically) doesn't show any API.

Searching [in the code](https://github.com/theintern/intern/search?p=1&q=emit&unscoped_q=emit) I found a few events:

* error
* suiteStart
* suiteEnd
* testStart
* testEnd

The problem is that even with those, I can't find any way of knowing when Intern has finished running everything in the config. There are multiple tests, and there can be multiple suites. There is no `runEnd` event or similar.

Here is a paste of the logs I am generating from those events so far:

```
index.js:36
Functional Tests Starting: intern-local...
index.js:36
Running: ./node_modules/.bin/intern config=tests/functional-tests/intern-local.json
index.js:36
[14:45:47] Webserver started at http://localhost:8080
log.js:8
Start test: load a page...
index.js:36
✅ Finished test: load a page
index.js:36
✅ Test Suite Finished: Short test
index.js:36
✅ Test Suite Finished: chrome 67.0.3396.99 on Mac OS X
```

The problem is that after the last "Test Suite Finished", I just don't get any new events and have no way of knowing the test ended.

## Possible solution
* Maybe there is a way of knowing tests are finished that I don't know about
* Intern test events should be documented

## Steps to reproduce (for bugs)

In node:

```js
intern.configure(myConfig);
intern.run();
```

## Environment

Intern version: 4.2.0
Node version: 9.9.0
NPM version: 5.6.0

**Comment by jason0x43** [comment]
The docs could definitely use some improvement here.

A list of the main events are in the [Executor.Events](https://theintern.io/docs.html#Intern/4/api/lib%2Fexecutors%2FExecutor/events) API docs. There are `runStart` and `runEnd` events for all tests, `testStart` and `testEnd` for tests, and `suiteStart` and `suiteEnd` for suites. A suite event where the suite doesn't have a parent (i.e., it's a top-level session suite) denotes a session, like an instance of Intern running in a remote browser.
