### ISSUE TITLE
Intern 4.2.x silently consumes some errors

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#940]
At least Intern 4.2.2 is silently consuming some errors.

To reproduce:

1. Clone https://github.com/dojo/cli
2. Checkout version ab67c6c3
3. `npm install`
4. `npx intern`

Intern silently exits. It returns an error code, but displays no error.

The issue appears to be that the error's `reported` flag (which prevents Intern from displaying errors multiple times) is being set on errors that weren't actually reported.

**Comment by janpe** [comment]
+1 for this.

**Comment by jason0x43** [comment]
Try `@dojo/framework` PR 125 (commit 1cb5a94dd4f20aa4d64797898460e2cae815b58).

Also, Intern isn't displaying an error when SeleniumTunnel fails to start due to an incompatible Java version.

**Comment by jason0x43** [comment]
To express the issue with the above PR, run `npm run test:browserstack` (with appropriate credentials).

**Comment by jason0x43** [comment]
It turns out the issue with the above PR is that , the issue is actually with the reporter used in `@dojo/scripts`, which has an error handler but doesn't report errors.

I think Intern will start reporting errors by default, and will rely on a setting to disable default error reporting.

**Comment by jason0x43** [comment]
Or come up with a more definitive way of recording when errors are reported.

**Comment by jason0x43** [comment]
After further consideration, I'm going to leave the behavior as-is. If a user is simply adding custom reporting behavior, like logging messages to a database or something, the default reporter will report errors. If a user is disabling the default reporter and completely replacing it with something else, presumably they're intentionally creating a fully custom UI, in which case they'll need to ensure errors are reported as well as other messages.
