### ISSUE TITLE
Can we use Intern to test video/HTML5/React players?

### ISSUE THREAD

**Issue by MirzaSB** [theintern/intern#942]
Hello,

I am evaluating this framework, and I had a question. Can we use this framework to test a video player implemented by React JS in a browser page?

For example, in Selenium or Webdriver, it would require us to inject JS into the browser. 

For example..

```js
const videoPlayer = document.getElementById('video-player-id');
videoPlayer.play();
const videoDuration = setInterval(function() {
	if (videoPlayer.readyState > 0) {
		var minutes = parseInt(videoPlayer.duration / 60, 10);
		var seconds = videoPlayer.duration % 60;
		clearInterval(i);
                // Check if the video has been played.
               expect(videoDuration).not.toBeLessThan(0);
	}
}, 200);
```

Is this particular feature supported in Intern (as it does in Webdriver or Selenium)?

**Comment by jason0x43** [comment]
Intern uses Selenium + WebDriver for it's functional tests, so you can certainly inject code. For your situation, you might do something like:

```js
'test video'() {
  return this.remote
    .get('test page.html')
    .executeAsync(done => {
      const videoPlayer = document.getElementById('video-player-id');
      videoPlayer.play();
      const videoDuration = setInterval(function() {
        if (videoPlayer.readyState > 0) {
          var minutes = parseInt(videoPlayer.duration / 60, 10);
          var seconds = videoPlayer.duration % 60;
          clearInterval(i);
          done();
        }
      }, 200);
    });
}
```

In this example, Intern opens the test page, injects its code, and waits for the injected code to finish (by calling the `done` function implicitly given to it). If the injected code doesn't return within a timeout (30 seconds by default), the test will fail.
