### ISSUE TITLE
IE 11 hangs during session capabilities fixes?

### ISSUE THREAD

**Issue by gitgrimbo** [theintern/intern#954]
Intern 4.3.2, but also happens in 4.2.0.

![image](https://user-images.githubusercontent.com/1020541/47294143-14ae9880-d604-11e8-81d9-c737e10c7f7d.png)

**Comment by jason0x43** [comment]
I haven't seen any IE11 hangs yet, although I've seen IE10 hang on a selector test. Does it happen all the time, or only sometimes?

**Comment by gitgrimbo** [comment]
Hmm. It was hanging consistently. Then my PC crashed and restarted and now it's working. This is for Intern 4.2.4. The original error could be a false alarm.

**Comment by jason0x43** [comment]
I'm closing this for now, but we can re-open it if the problem comes up again.
