### ISSUE TITLE
Fix dependency on flatmap-stream

### ISSUE THREAD

**Issue by justinballerstein** [theintern/intern#960]
## Expected behavior
npm install to succeed

## Current behavior
npm ERR! 404 Not Found: flatmap-stream@https://registry.npmjs.org/flatmap-stream/-/flatmap-stream-0.1.1.tgz

## Possible solution
https://www.zdnet.com/article/hacker-backdoors-popular-javascript-library-to-steal-bitcoin-funds/
This dependency was removed because it was hacked
see https://github.com/dominictarr/event-stream/issues/116

## Steps to reproduce (for bugs)
npm install intern

## Environment
Intern version: b99fe83a4816578aeb2c4cdf9f02d997e442b7c5
Node version: 8.7.0
NPM version: 5.4.2
Browser version: na

**Comment by jason0x43** [comment]
Intern doesn't depend on flatmap-stream, nor do any of its dependencies. Could the issue possibly have been from something else in your project?

**Comment by justinballerstein** [comment]
Thanks I will track this down, it was a basic template, closing the issue
