### ISSUE TITLE
Opening collapsed sub section on web view hides below child

### ISSUE THREAD

**Issue by tomecho** [theintern/intern#966]
## Expected behavior

The next top level section should be pushed downward and not disappear

## Current behavior
Opening collapsed sub section on web view hides below child 
http://g.recordit.co/T4NwW430Y3.gif

## Steps to reproduce (for bugs)

1. Create two top level sections, the first one should have at least one sub section
2. open the first top level section
3. open the subsection within the first top level section

the second top level section has disappeared

## Environment

Intern version: 4.2.0
Node version: 8.12.0
NPM version: 6.4.1
Browser version: Chrome Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by jason0x43** [comment]
Note: This is still an issue in Intern 4.3.x and 4.4.x. It's probably an off-by-one error in `Html._setCollapsed`.
