### ISSUE TITLE
reporters+ doesn't work properly in base config

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#970]
## Expected behavior

Using `reporters+` in the base config should add the given reporter(s) to the default.

## Current behavior

The given reporter(s) replaces the default.

## Steps to reproduce (for bugs)

1. Clone intern-tutorial
2. Checkout the `completed` branch
3. `npm install`
4. `npm install intern@latest`
5. `npm test showConfig`. Note that the `reporters` property only has `htmlcoverage`. It should also have `runner`.

## Environment

Intern version: 4.4.1
Node version: 11.10.0
NPM version: 6.8.0

**Comment by aciccarello** [comment]
Is this different than #877 or just a dupe?

**Comment by jason0x43** [comment]
It's a duplicate.
