### ISSUE TITLE
I suggest you change the name of the project to a more unique

### ISSUE THREAD

**Issue by NikolayMakhonin** [theintern/intern#971]
Perhaps it is worth using the name "theintern" everywhere. I think it was originally a mistake to use such a popular word in the project name. Now it is difficult to fix. 
Google also searches for the word "internet" instead of "intern" or invites me to get a job as intern

**Comment by dylans** [comment]
It was unfortunate that a year or two after we named the project that a movie called the intern was released.

That said, other testing tools have names like Karma, Jasmine, Chai, Mocha, Jest, and Tape which are all very common names as well.

Perhaps in hindsight we could have branded everything as theintern.io or Intern.js or intern.ts, but that would be a lot less fun.

In general when searching for tech projects, I add a qualifier to google. If you search for "intern js", "intern ts", "intern test" or "theintern test", all give you Intern as the first result. A few projects become big enough to become the first result over their more general usage, but that's pretty rare.
