### ISSUE TITLE
I suggest to improve the documentation

### ISSUE THREAD

**Issue by NikolayMakhonin** [theintern/intern#972]
It seems to me that Intern has almost no documentation. No information about the most simple things. 
Let me give you a list of questions about the simplest things, and you will add the necessary information to the documentation.

**Comment by vladikoff** [comment]
The docs can be found here (just in case you missed it): https://theintern.io/docs.html#Intern/4/docs/README.md

**Comment by NikolayMakhonin** [comment]
For example, I not found in the [documentation](https://theintern.io/) how to use command line. I think it is worthwhile to include such examples in the documentation:
**Command line usage:**
...
```node_modules/.bin/intern help```
```node_modules/.bin/intern config=env/intern.json configParam1=value1 configParam2=value2```
Briefly and clearly

I not sure that this code is correct (I did not find this in the documentation):
```node_modules/.bin/intern configParam1.subParam1.subParams2=value1```

I think the documentation should contain more examples, even if they seem obvious. And even better with links to the project with an example, so that I can see the context of this piece of code.
Now it is very difficult to understand how to set up a project for the full use of the "intern". [These examples](https://github.com/theintern/intern-examples) are insufficient. I think it is worth to make one example project with implementation of the maximum number of intern functions.
It's 100 times easier for me to look at the sample code than to read the text description and guess how the code should look, where to place the files and what the possibilities of using the tool are. For example, after a long study of documentation and examples, I am not sure whether the "intern" can replace the "karma", because only a real example can show it.

**Comment by jason0x43** [comment]
> Let me give you a list of questions about the simplest things, and you will add the necessary information to the documentation.

This would actually be very helpful. Writing documentation that is both introductory and useful to seasoned users can be quite difficult; in particular, it can be hard to know what's not obvious to a new user when you're deeply involved in a project.

**Comment by RoystonS** [comment]
Documentation for the command-line (and many other ways to launch Intern) are here: https://theintern.io/docs.html#Intern/4/docs/docs%2Frunning.md/node

**Comment by dylans** [comment]
Additionally I would add that https://theintern.io/docs.html#Intern/4/docs/docs%2Fconfiguration.md/config-file contains a ton of information about the various ways in which things work in configuring Intern. Some of it is subtle, but for example the information about the command line settings at https://theintern.io/docs.html#Intern/4/docs/docs%2Fconfiguration.md/command-line should make it easy to understand how things passed in via the command line get evaluated.

**Comment by jason0x43** [comment]
Closing this since there's no specific action, and general doc updates are planned for the next major release of Intern.
