### ISSUE TITLE
baseUrl: ".." broken

### ISSUE THREAD

**Issue by wkeese** [theintern/intern#975]
## Expected behavior
All our project's dependencies are at the same level as the project itself, rather than in the `node_modules` directory:

```
/
--- delite  (our project)
--- dcl       (dependency)
--- ...
```

I set the `baseUrl` to point one level above, so that delite can load dcl:

```json
"loader": {
	"script": "dojo",
	"options": {
		"baseUrl": ".."
	}
}

"suites": [ "delite/tests/unit/CustomElement" ],
```

That configuration should load `delite/tests/unit/CustomElement.js`:

```js
define([
	"dcl/dcl",
	"dcl/advise",
	"delite/register",
	"delite/CustomElement",
	"requirejs-domready/domReady!"
], function (dcl, advise, register, CustomElement) {
...
```

And then CustomElement.js should be able to load its dependencies, as listed above.

## Current behavior

```
$ npx intern
...
Error: scriptError: ../../delite/tests/unit/CustomElement.js
```

For some reason the `baseUrl` is getting applied twice to load the original test script, rather than once (or ideally) not at all.

## Possible solution
My actual goal is to use requirejs rather than the dojo loader, but running into issues there too.  Not sure if that would workaround this problem or not.

## Environment

Intern version: 4.4.1
Node version: 10.15
NPM version: 6.8
Browser version: N/A

**Comment by devpaul** [comment]
Hi @wkeese,

I think the issue you're seeing is because Dojo is treating packages as "siblings to Dojo" in addition to having a `baseUrl`. Would you try this as your loader config:

```
"loader": {
	"script": "dojo",
	"has": {
		"config-tlmSiblingOfDojo": 0
	},
	"options": {
		"baseUrl": ".."
	}
}
```

This will force the Dojo loader to only use the `baseUrl`. 

Let me know if this works for you. I'll follow up on the Dojo side and file a bug if appropriate. [According to the docs](https://dojotoolkit.org/reference-guide/1.10/loader/amd.html#module-identifiers), setting a `baseUrl` should automatically turn off `config-tlmSiblingOfDojo`.

**Comment by wkeese** [comment]
Funny, I was just struggling with `baseUrl` yesterday, especially getting the right value for then it's running in the browser.

First off, we've actually successfully moved from the Dojo loader to the RequireJs loader.

 But I still think `baseUrl` is "broken", in the sense that setting the correct value when using `npx intern serveOnly` will be the wrong value when running just `npx intern`, since the former uses the URL `http://localhost:9000/__intern/` and the latter has the URL of `http://localhost:9000/__intern/browser/remote.html?...`.   That means you need more `../..` for the second case.

Worse off, my URL to directly run the unit tests (`http://localhost/delite/node_modules/intern/?reporters=html`) is one more level deep, since my web server was running a level above the project containing intern.  I guess this is unsupported though as your documentation says you have to run the web server in the directory containing the project, i.e. the parent of `node_modules`.

**Comment by wkeese** [comment]
PS: I'm assuming that the web server at port 9000 is independent of the `loader` configuration, even the `loader` configuration for `node`, and that it just serves according to `basePath`, which defaults to `.` but that I had set to `..`.   Let me know if that's incorrect.

**Comment by devpaul** [comment]
Glad to hear you have a working loader 🎉 

Intern's server does support a `basePath` config parameter which should work for your use case. By setting `basePath` the server will serve everything outside of `__intern` using that `basePath` as the root. This will include the config as well, so you may need to specify the config location; e.g. from the browser: localhost:9000/__intern/?config=delite/intern.json. If you need anything more complex you could set up a server [as show here in the docs](https://theintern.io/docs.html#Intern/4/docs/docs%2Fhow_to.md/test-noncors-web-apis).

The web server and the loader are independent of each other. The `serverPort` can be changed in the config. And the `serverUrl` can be set to tell Selenium what URL should be used to run browser & functional tests.

**Comment by devpaul** [comment]
I created #1001 to investigate improving `baseUrl` usage with relative paths. As a stop-gap solution, using an absolute path for package mappings should work between the two runtime environments.

**Comment by wkeese** [comment]
OK thanks.  I think it also works by just using enough dots to handle both cases (leveraging the apparent behavior that ".." from the root just stays at the root).

I ended up leaving `basePath` to point to `..` so that I could get a configuration that worked along with my URL to directly run the tests.
