### ISSUE TITLE
Provide a way to ignore specific global errors

### ISSUE THREAD

**Issue by jason0x43** [theintern/intern#986]
ResizeObserver can cause global errors that [aren't functionally significant](https://stackoverflow.com/a/50387233/10475190). The Browser executor catches unhandled global errors and emits them as error events.

## Expected behavior

Benign ResizeObserver errors should not cause a test suite to fail.

## Current behavior

Unhandled global errors, such as those emitted by ResizeObserver, are treated as suite-level errors.

```
✓ chrome 73.0.3683.103 on Windows NT - <test name> (0s)
Suite chrome 73.0.3683.103 on Windows NT FAILED
Error: ResizeObserver loop limit exceeded
  @ node_modules\intern\browser\remote.html?basePath=%2F&runInSync=false&serverUrl=http%3A%2F%2Flocalhost%3A9000%2F&sessionId=0f288438f37cc2d2403e8c9e0c1f0352&socketPort=9001:0:0
TOTAL: tested 1 platforms, 0 passed, 0 failed, 51 not run; suite error occurred
```

## Environment
Intern version: 4.x
Browser version: Chrome 73
OS: Windows

**Comment by schontz** [comment]
I tested updating https://github.com/theintern/intern/blob/master/src/lib/executors/Browser.ts#L34 to ignore ResizeObserver errors and the error is gone in `serveOnly` mode. It still fails as mentioned above in a headless test.

**Comment by jason0x43** [comment]
@schontz If you get a chance, try out the [ignore-global-errors](https://github.com/theintern/intern/tree/ignore-global-errors) branch. It adds two new config properties, `warnOnUnhandledRejection` and `warnOnUncaughtException` ([description](https://github.com/theintern/intern/blob/ignore-global-errors/docs/configuration.md#properties)) that can be used to treat some or all such errors as warnings rather than failures.

**Comment by schontz** [comment]
Attempted to install it, but npm doesn't like what I'm doing...

```node
C:\dev\_head\cadsrc\client>npm i -D theintern/intern#ignore-global-errors
npm ERR! path C:\dev\_head\cadsrc\client\node_modules\intern\bin\intern.js
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod 'C:\dev\_head\cadsrc\client\node_modules\intern\bin\intern.js'
npm ERR! enoent This is related to npm not being able to find a file.
```

**Comment by jason0x43** [comment]
You'll need to build the package locally. Checkout the `ignore-global-errors` branch, then run `npm run devpack`. That will leave you with a tarball (like `intern-4.5.0-pre.tgz`) that you can install.

**Comment by schontz** [comment]
Great. Can I just untar that into node_modules directly?

**Comment by schontz** [comment]
It works beautifully! I added this to `intern.json`:

```json
"warnOnUncaughtException": "ResizeObserver loop limit exceeded"
```

Thank you.

---

FYI, installing `npm run devpack` fails on Windows:
```
intern-4.5.0-pre.tgz
cp: cannot create regular file `../../': Permission denied
```
But it works using cygwin. Windows is expecting `..\..\`. There may be a `path.join` that needs updating?

**Comment by jason0x43** [comment]
Glad it works! And thanks for catching the Windows install issue. I try to be cross platform, but it's easy for those kinds of issues to slip through.

**Comment by schontz** [comment]
Sure thing. Most folks won't be developing intern on Windows, but, alas, here we are!

**Comment by jason0x43** [comment]
Since this is a new feature, it'll go out in 4.5.
