### ISSUE TITLE
Test fails because JSONP requests returns 404

### ISSUE THREAD

**Issue by Biboba** [theintern/intern#990]
## Expected behavior
Test should be successfull.

## Current behavior

Test is failing because the javascript file loaded with JSONP returns 404 error because of intern webserver.
I am testing a project built with webpack and a library that makes dynamic imports at runtime ([ESRI JS API](https://developers.arcgis.com/javascript/)).
These modules are loaded with JSONP by webpack using "__intern" webcontext:
http://localhost:9000/__intern/85.js

But the file is only accessible at:
http://localhost:9000/~tmp/85.js 
Knowing that '~tmp' is the folder specified for "suites" property of intern.json file:
```js
{
  "environments": [
    {
      "browserName": "chrome",
      "chromeOptions": { "args": [ "headless", "disable-gpu" ] },
      "fixSessionCapabilities": "no-detect"
    }
  ],
  "suites": "~tmp/tests.js"
}
```
## Possible solution

I configured 'serverUrl' of the intern.json file to proxy all the requests to a simple express web server to rewrite url and be able to serve the javascript files.
It works fine in Chrome browser when using 'intern serveOnly' but I don't know why it does not work with headless Chrome using 'intern'.

## Steps to reproduce (for bugs)

Steps are available on the repo I am using where I opened an issue as well but you would need to clone that repo first:
https://github.com/Esri/arcgis-js-cli/issues/35

## Environment

Intern version: 4.4.3
Node version: 8.9.1
NPM version: 6.4.1
Browser version: Chrome Version 75.0.3770.100

Thanks for your help !

**Comment by jason0x43** [comment]
Could you provide a bit more information about how to reproduce the issue? I looked at the referenced issue, but arecgis-js-cli doesn't appear to use Intern, and doesn't provide an `esri/request` module, so I'm not sure where to go with it.

**Comment by Biboba** [comment]
Thanks for having a look. I am preparing a simpler repo.

**Comment by Biboba** [comment]
Here it is:
https://github.com/Biboba/intern-webpack

I forgot to update the README but commands are:
```
npm test
```
and 
```
npm debug
```
to see the 404 error with intern serveOnly option.

Thanks !

**Comment by jason0x43** [comment]
The issue in the example repo is that the public path for the webpack bundle hasn't been defined, so webpack is trying to load files using a relative base. `0.js` is available at `/~tmp/0.js`, but webpack is trying to load from `/intern__

**Comment by Biboba** [comment]
Indeed  ! Many thanks for your help @jason0x43
